alphagov/verify-frontend

- Gemfile
- Gemfile.lock
Trying to install the package on a linux box we get an error when the service starts up
! Unable to load application: ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime.
See https://github.com/rails/execjs for a list of available runtimes.
Rubyracer is the top hit and there was a commented out line in the gemfile.
Single: WillPearson
> 3319: Uncomment rubyracer in gemfile

- packaging/postinst.sh
We need these directories to exist prior to the app first running, as we're going to write the Rack server's
PID files etc there.
> Create Rails tmp directories post package install

- Procfile
- config/puma.rb
- Rails env is always production
- workers set to 2 for now, unknown how many cores production machines
will have for now. (See https://github.com/puma/puma#clustered-mode )
> Initial production Puma config

- jenkins.sh
This was breaking the building of the assets as pkgr wasn't passing the
environment variables properly. This should
allow it to get the environment variable from the dotenv file.
Once this is merged, we can remove a line from our jenkins job.
Single: WillPearson
> 3333: Fix jenkins script to precompile assets seperately

- Gemfile
- Gemfile.lock
- app/controllers/start_controller.rb
- app/views/layouts/application.html.erb
- config/application.rb
- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
The route_translator gem allows route names to be moved into the locale dictionaries. Redirects will need to have `I18n.locale` passed through manually.
> 3321: allow for localised routes

- config/puma.rb
This isn't how we wan't to load up envvars. We will be using the config directory pkgr sets up for us.
> bau: remove .env reading from puma config

- jenkins.sh
As we need to sepcify the iteration number for deploying
new versions we need it to be predictable.
I can't set it to the empty string currently, so 1 it is.
Single: WillPearson
> 3370: Fix the iteration number to 1 for deploys

- app/controllers/start_controller.rb
- app/views/start/index.html.erb
- config/locales/en.yml
- spec/features/user_submits_start_page_form_spec.rb
If there is no answer then we should prompt for one.
@robinwhittleton: please, could you let me know if I should correct the styling for this error
> 3321: show error if no answer to start page question

- app/assets/javascripts/application.js
- app/assets/stylesheets/_application.scss
- app/assets/stylesheets/_govuk-elements-overrides.scss
- app/assets/stylesheets/elements/forms/_form-block-labels.scss
These set the whole label to be highlighted when an input is selected.
This needs reviewing by @robinwhittleton and will probably want to
change.
In particular: I had to modify one of the scss files inside gov uk elements. I'm not sure this was the right thing to do? Will it make upgrading difficult?
(Recreated from #17 which was targetting the wrong branch)
> 3321: Add gov uk selection button styles

- .env
- .pkgr.yml
- Gemfile
- Gemfile.lock
- Rakefile
- app/controllers/service_status_controller.rb
- config/application.rb
- config/initializers/configuration.rb
- config/initializers/cookie_validator.rb
- config/initializers/federation_localisation.rb
- config/initializers/proxies.rb
- config/initializers/service_status_filter.rb
- config/puma.rb
- config/routes.rb
- lib/configuration.rb
- lib/service_status.rb
- lib/service_status_filter.rb
- lib/tasks/zdd.rake
- packaging/postinst.sh
- packaging/postrm.sh
- spec/features/service_set_unavailable_spec.rb
- spec/lib/configuration_spec.rb
- spec/lib/service_status_spec.rb
- upstart/front.conf
The commit provides support for the ZDD orchestration we use in our microservices. It is hoped that with this functionality in place we can drop the new frontend into our architecture without changing how we run our deployments. Our main goal for ZDD compliance is the ability to drain new requests from an instance of our microservices.
Our services are ZDD compliant, or able to drain, when they provide the following functionality:
* An endpoint `/service-status` that reports a 200 when the service is available for new requests or a 503 when it is unavailable and should no longer issue new requests
* A filter/middleware that will add a 'Connection: close' response header to all responses when the service is unavailable and should no longer handle new requests.
* The ability to set a …
> 3347: add support for zdd endpoints

- app/models/api/client.rb
- config/initializers/configuration.rb
- config/initializers/proxies.rb
- lib/configuration.rb
- lib/ssl_context_factory.rb
- spec/lib/configuration_spec.rb
Major aim of this PR is to open up the ability to configure the TLS behaviour of our HTTP client. This is achieved by the supplying a SSLContext object which affects the TLS behaviour (verification mode, certs for verification, protocols etc).
In order to support this, I have adapted the configuration class to support default or missing values.
> bau: support custom ssl context

- app/assets/stylesheets/_application.scss
- app/assets/stylesheets/helpers/_available-languages.scss
- app/views/layouts/application.html.erb
- app/views/shared/_available_languages.html.erb
This replicates the styles and markup used on GOV.UK (for example on https://www.gov.uk/government/organisations/wales-office). We’re doing this because previous user research has indicated that where content is directly translated, Welsh language users sometimes like to flick between the versions to make sure they’re getting correct content.
The placement of these links on Verify is provisional, but has been approved by @alextea for the time being.
> Move language link to below the phase banner

- packaging/postrm.sh
Commenting out the rm command in the postrm.sh as it is causing errors during package removal.
As the link /etc/init/front.conf will not exist when the postrm runs.
> bau: front-packager-postrm

- jenkins.sh
- kill-service.sh
One incorrect hashbang, a couple of warnings about using quotes to
prevent spaces / globs being misintepreted.
> bau: Fix shellcheck warnings

- Gemfile
- Gemfile.lock
- jenkins.sh
- spec/feature_helper.rb
Allows feature tests to be run on jenkins using the headless.
Also, adds tests explicitly to `jenkins.sh`
> bau: use headless gem for headless browsing on jenkins

- jenkins.sh
envvars weren't being set correctly for rspec in jenkins
> bau: fix envvars for headless

- jenkins.sh
Explicity set dotenv for assets precompile rather than relying on the CI node.
> bau: explicity use dotenv for assets precompile

- Gemfile
- Gemfile.lock
- spec/features/users_browser_sends_client_side_analytics_spec.rb
- spec/mock_piwik_middleware.rb
Pact caused issues with testing during Jenkins builds.
We now test Piwik requests using a mock Piwik endpoint implemented with
Sinatra. This gets added as middleware to the Capybara server so
requests made to Piwik can be inspected by us during tests.
Authors: @richardtowers @vixus0
> BAU: Remove Pact and replace with Sinatra middleware

- app/views/about/certified_companies.html.erb
- app/views/about/choosing_a_company.html.erb
- app/views/about/identity_accounts.html.erb
- app/views/about/index.html.erb
Our acceptance tests rely on the 'next' buttons having IDs to locate and
click them
> 3340: Add ids to 'next' buttons for acceptance tests

- app/models/idp_eligibility/rules_loader.rb
- spec/features/user_visits_select_documents_page_spec.rb
- spec/fixtures/bad_rules/stub-idp-one_missing_keys.yml
- spec/fixtures/good_rules/stub-idp-one.yml
- spec/models/idp_eligibility/rules_loader_spec.rb
- stub/rules/stub-idp-no-docs.yml
- stub/rules/stub-idp-one.yml
In the old frontend we support multiple simple ids per IdP to avoid
duplicating config.  This adds minimal support for the same thing.
> 3341: Support multiple simple Ids per IdP

- app/assets/stylesheets/helpers/_available-languages.scss
- app/views/shared/_available_languages.html.erb
- config/locales/cy.yml
As we add new pages to the frontend we will not always have a full
translation ready. This banner which only appears for Welsh language
users explains this
GOV.UK Verify is in the process of being translated into Welsh. We're
translating pages every week between now and the end of April. Your
feedback helps us improve the translation.
The banner includes a link for users to provide feedback.
> 3453: Add banner explaining incomplete translation

- app/assets/javascripts/sign_in.js
- app/controllers/about_controller.rb
- app/controllers/select_idp_controller.rb
- app/controllers/sign_in_controller.rb
- app/models/analytics/federation_reporter.rb
- app/models/display/federation/federation_info_getter.rb
- app/models/federation_info_response.rb
- app/views/sign_in/index.html.erb
- config/initializers/federation.rb
- config/initializers/piwik.rb
- config/initializers/proxies.rb
- lib/analytics/piwik_client.rb
- spec/feature_helper.rb
- spec/features/server_sends_analytics_spec.rb
- spec/features/user_selects_idp_spec.rb
- spec/features/user_submits_start_page_form_spec.rb
- spec/features/user_visits_about_certified_companies_page_spec.rb
- spec/features/user_visits_about_page_spec.rb
- spec/javascripts/sign_in_spec.js
- spec/lib/analytics/piwik_client_spec.rb
- spec/logger_helper.rb
- spec/models/analytics/federation_reporter_spec.rb
- spec/models/display/federation/federation_info_getter_spec.rb
- spec/models/display/idp/display_data_correlator_spec.rb
- spec/models/session_proxy_spec.rb
- stub/locales/rps/headless-rp.yml
- stub/locales/rps/loa1-test-rp.yml
- stub/locales/rps/test-rp-noc3.yml
- stub/locales/rps/test-rp-repudiation.yml
- stub/locales/rps/test-rp.yml
Adds friendly names when reporting custom variables. 
Work was paired, but have since rebased solo to include latest master changes, hence PR.
> 3495 report custom variables with friendly names

- .travis.yml
In between tests we should cache phantomjs so that we don't get intermittent
test failures because Travis is unable to download the phantomjs binary.
> bau: cache phantomjs on Travis

- app/controllers/application_controller.rb
It's useful to see the error and stack trace in the browser when you're
developing.
> BAU: don't rescue standard errors in development

- .env
- .env.test
- config/initializers/configuration.rb
- config/initializers/piwik.rb
- lib/piwik.rb
- spec/lib/piwik_spec.rb
The PORT is never configured outside of the local environment so it seems a bit
wasteful to provide a discrete setting for it when it can be included in the
PIWIK HOST options
> 3517: remove port config for piwik

- app/controllers/start_controller.rb
- app/models/cookie_names.rb
- app/models/session_proxy.rb
- config/routes.rb
- lib/originating_ip_store.rb
Running rubocop with a stricter config than the GDS defaults raises some
interesting things such as freezing strings which are intended to be
constant (strings are mutable by default in Ruby). I think we should
consider making some changes to our rubocop config to catch these
things.
Includes a separate change which will only include the JasmineRails
routes if we are in test or development env, they are currently excluded
by the dependency gem not being available in production.
> bau: Small fixes recommended by rubocop

- config/locales/cy.yml
- config/routes.rb
- spec/features/user_visits_about_certified_companies_page_spec.rb
- spec/features/user_visits_about_choosing_a_company_page_spec.rb
- spec/features/user_visits_about_identity_accounts_page_spec.rb
- spec/features/user_visits_about_page_spec.rb
Once this goes live the about pages should be visible in welsh to welsh language users.
> 3517: start localising the routes to the about pages

- lib/metrics/controller_action_reporter.rb
- spec/lib/metrics/controller_action_reporter_spec.rb
Rails only sets view_runtime when rendering views. This means it's nil
when performing redirects or responding to AJAX requests.
> 3521: Do not send invalid view_runtime metrics to statsd

- app/models/api/response_handler.rb
- spec/models/api/response_handler_spec.rb
This commit introduces a more consistent approach to logging api errors. This
way we can ensure we get the full content of the error response.
> 3517: use more consistent error messages for api failures

- app/controllers/application_controller.rb
- config/initializers/raven.rb
- lib/support/raven/logger.rb
- spec/features/user_encounters_error_page_spec.rb
- spec/lib/support/raven/logger_spec.rb
Now when we send error messages to the Rails logger they will be sent to Sentry
using Raven as well as our other loggers. This should allow us to not have to explicitly capture exceptions
where we are currently logging errors.
In order to integrate with the Rails logger we provider a logger for raven that
implements the ::Logger interface. It is then added to the Rails logger as an
additional output using ActiveSupport::Logger::broadcast.
Also, provided an integration test.
> 3517: integrate raven into the rails logger

- config/locales/cy.yml
- config/locales/en.yml
So far, we have been using google translate for welsh text. We are now moving
into a model where we only have welsh in the translations file which is
officially translated. Everything else will be in English. This way it
will be easier to spot what needs translations.
@yolinas
> bau : only officially translated Welsh in the cy.yml file

- app/models/cookie_validator.rb
- app/models/cookie_validator/session_id_cookie_validator.rb
- app/models/cookie_validator/successful_validation.rb
- app/models/cookie_validator/validation_failure.rb
- spec/models/cookie_validator_spec.rb
When a session is completed the sessionId is set to 'no-current-session' and
this should prevent a user from being view pages on the Hub.
Currently, this check is happening within our backend API and the FE is
receiving a 403 response, that's sent to Sentry, and which isn't very clear or
convenient.
By performing the check within the FE we remove the call to the API and the
Sentry output.
> 3517: Bar access when session is in completed state

- app/models/evidence.rb
- app/models/idp_eligibility/checker.rb
- app/models/idp_eligibility/evidence.rb
- app/models/select_documents_form.rb
- app/models/select_phone_form.rb
- lib/evidence_query_string_parser.rb
- spec/lib/evidence_query_string_parser_spec.rb
- spec/models/evidence/select_documents_form_spec.rb
The IdpEligibility::Checker class defined a mask consisting of all the
document evidence. This was duplicated in Evidence::DOCUMENT_ATTRIBUTES
which would mean two places to maintain a list of document-related
evidence items. Evidence has now been made a submodule of
IdpEligibility which had the added bonus of removing some requires from
specs.
> BAU: Remove duplicated code from IDP eligibility checker

- jenkins.sh
- pre-commit.sh
Running all tests together would allow features tests to pass even if
they were missing require statements. This is because the require
statements were present in the unit tests, so the classes were already
available when feature tests ran.
e.g. Removing "require 'select_phone_form_mapper'" from
select_phone_controller would not cause failures when running
pre-commit.
Using the exclude pattern means that if any new test folders added, they
will get picked up in the normal test run.
Also changes jenkins.sh to use commands from pre-commit.sh
Author: @lloydnye
> BAU: Split feature test runs from other tests

- config/routes.rb
- spec/features/user_visits_no_mobile_phone_page_spec.rb
This was merged prematurely. We need to release without these changes to prevent 404 errors.
Reverts alphagov/verify-frontend#64
> Revert "3531: Enable localised route for no mobile phone"

- app/controllers/select_documents_controller.rb
- app/controllers/select_phone_controller.rb
- app/models/idp_eligibility/checker.rb
- app/models/idp_eligibility/document_checker.rb
- app/models/idp_eligibility/masking_rules_repository.rb
- app/models/idp_eligibility/rules_repository.rb
- config/initializers/idp_eligibility.rb
- spec/models/idp_eligibility/checker_spec.rb
- spec/models/idp_eligibility/document_checker_spec.rb
- spec/models/idp_eligibility/masking_rules_repository_spec.rb
- spec/models/idp_eligibility/rules_repository_spec.rb
Document eligibility checking is now performed using a separate checker `DocumentChecker`.
This checker works by applying an attributes mask to the rules defined by its supplied `RuleRepository` through `MaskingRulesRepository`. The masked rules are then supplied to the regular checker as it is a delegate of the `DocumentChecker`.
NOTE: I'm unsure about using DelegateClass here for the document checker. We could probably just use plain old inheritence, but I wanted to imply that the `DocumentChecker` was composed of the `Checker`, `MaskingRulesRepository` and the attribute masked which I think using inheritance confuses things.
> 3491: introduce a separate checker for documents

- config/locales/cy.yml
- config/locales/en.yml
The title needs to be 
Why might this not work for me
rather than
Why this might not work for me
The acceptance tests are failing:
Timed out after 20 seconds waiting for title to be "Why might this not work for me - GOV.UK Verify - GOV.UK". Current title: "Why this might not work for me - GOV.UK Verify - GOV.UK"
> 3532: Fix page title for why-might-this-not-work-for-me

- app/controllers/application_controller.rb
- app/controllers/saml_controller.rb
- app/controllers/select_documents_controller.rb
- app/controllers/select_phone_controller.rb
- spec/feature_helper.rb
- spec/features/user_visits_select_documents_page_spec.rb
- spec/features/user_visits_select_phone_page_spec.rb
Stores the selected evidence answers in the session, but for now they will not
be read anywhere in the application.
The intention is that we will use the session store to remove the use of the
propagated query params.
Answers are currently stored and associated with a key for the type of
evidence/page they are related to. This way we should be given a guarantee that
only the most recent answers to questions are stored in the cache.
> 3568: start storing evidence answers in session cookie

- app/views/why_companies/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
The template shouldn't constrain how the content for the why-companies
page can be formatted (within reason).
> 3342: Move HTML formatting into localisation file

- app/controllers/unlikely_to_verify_controller.rb
- app/views/unlikely_to_verify/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
- spec/features/user_visits_unlikely_to_verify_page_spec.rb
This adds the dead-end page that the user will see if no IdPs can verify
at the 'select documents' stage.  It's not currently possible to hit
this page because at least one IdP can verify with no documents, but
it's good to have this page as a fall-back in case that changes.
> 3530: Add dead-end page for no documents

- Gemfile
- Gemfile.lock
- spec/features/requests_fingerprint_asset_spec.rb
Currently the fingerprint JS test can fail if the browser used has lots of plugins installed.  This fixes that by using Puma instead of WEBrick when a server is required in the tests.
> 3559 fix fingerprint test issues

- config/locales/cy.yml
- config/locales/en.yml
Remove ‘identity assurance’ from the about page title.
> 1977: fix about page title

- config/locales/cy.yml
- spec/features/user_visits_about_choosing_a_company_page_spec.rb
There are a few places in the translation where straight quotes have been used instead of the typographically correct curly quotes we use in the en-GB version. This corrects those places.
@joelanman suggested that this typographical convention was also correct in Welsh on Slack, and Microsoft’s Welsh style guide (http://download.microsoft.com/download/0/c/f/0cf9e2e7-a7a7-4e9d-a77c-8591d66541c9/wel-gbr-styleguide.pdf) uses curly quotes.
> BAU: fix straight quotes in Welsh translation

- app/assets/stylesheets/_application.scss
- app/assets/stylesheets/_govuk-elements-overrides.scss
- app/assets/stylesheets/pages/_cookies.scss
- app/assets/stylesheets/pages/_start.scss
- app/views/choose_a_certified_company/_idp_option.html.erb
- app/views/choose_a_certified_company/about.html.erb
- app/views/cookies/index.cy.html.erb
- app/views/cookies/index.en.html.erb
- app/views/layouts/application.html.erb
- app/views/select_documents/index.html.erb
- app/views/select_phone/index.html.erb
- app/views/shared/_idp_list.erb
- app/views/start/index.html.erb
- app/views/will_it_work_for_me/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- stub/locales/idps/stub-idp-no-docs.yml
- stub/locales/idps/stub-idp-one.yml
Grab bag of mini accessibility improvements, but as a quick list:
- fix the specified language of the remaining footer links
- update the cookies page to make it more legible
- fix broken `<p>` tags on the about page
- `<form>` tags need a non-empty action according to the specs
- make sure that all radio buttons are programmatically associated with their labels
- fix the red-on-yellow error text contrast
> 3632: accessibility amends

- app/assets/stylesheets/_application.scss
- app/assets/stylesheets/helpers/_panels.scss
- app/assets/stylesheets/pages/_slides.scss
- app/helpers/application_helper.rb
- app/views/about/certified_companies.html.erb
- app/views/about/identity_accounts.html.erb
- app/views/choose_a_certified_company/index.html.erb
- app/views/errors/no_cookies.html.erb
- app/views/static/cookies.cy.html.erb
- app/views/static/cookies.en.html.erb
We had carried over some CSS from the old frontend for panels (elements
that were distinguished from surrounding text with a left border). The
panels CSS already exists in GOV.UK elements and our templates should
be using those classes as they are visually nearly identical.
> BAU: Remove custom panels CSS

- app/controllers/about_controller.rb
- app/controllers/confirm_your_identity_controller.rb
- app/controllers/confirmation_controller.rb
- app/controllers/sign_in_controller.rb
- app/models/session_proxy.rb
- spec/models/session_proxy_spec.rb
All usages of federation_info_for_session could be replaced with identity_providers so it can now be private.
Now the API can be updated to only return the list of identity providers for that session.
> Make federation_info_for_session a private method

- app/assets/javascripts/select_documents.js
- app/views/select_documents/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/javascripts/select_documents_spec.js
Sighted users can see the checkboxes change to ‘no’ when the checkbox on the select documents form is checked. To replicate this behaviour for screenreader users we need to announce this change dynamically.
A visually hidden message is read out at the point that the checkbox is activated. When it is deactivated the message is blanked, but that doesn’t get read out because it’s empty.
> 3626: announce form changes when selecting no documents checkbox

- app/controllers/application_controller.rb
- spec/features/user_encounters_error_page_spec.rb
When an exception is thrown from within a controller a class method `rescue_from` is used to rescue and render an error page. As this is a occuring within the context of the class method, the locale set within an instance of a controller is lost and we need to call set_locale witin the error page rendering methods.
> 3648: set the locale for rescued errors

- app/controllers/other_ways_to_access_service_controller.rb
- app/views/other_ways_to_access_service/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
- spec/features/user_visits_other_ways_to_access_page_spec.rb
routes.rb includes other-ways-to-access-service-cy to ensure ZDD compliance
when we get to releasing the localized version in a later release.
@oswaldquek
> 3642: Other ways to access service page

- app/controllers/choose_a_certified_company_controller.rb
- app/controllers/redirect_to_idp_warning_controller.rb
These endpoints are now served by the new FE only so the CSRF check should be
enabled.
> bau: enable CSRF check for migrated endpoints

- app/assets/javascripts/analytics.js
- app/helpers/application_helper.rb
- app/views/about/index.html.erb
- app/views/choose_a_certified_company/index.html.erb
- app/views/confirm_your_identity/index.html.erb
- app/views/confirmation/index.html.erb
- app/views/errors/404.html.erb
- app/views/errors/cookie_expired.html.erb
- app/views/errors/no_cookies.html.erb
- app/views/errors/session_error.html.erb
- app/views/errors/session_timeout.html.erb
- app/views/errors/something_went_wrong.html.erb
- app/views/failed_registration/index.html.erb
- app/views/failed_sign_in/index.html.erb
- app/views/other_ways_to_access_service/index.html.erb
- app/views/redirect_to_idp_warning/index.html.erb
- app/views/response_processing/matching_error.html.erb
- app/views/select_documents/index.html.erb
- app/views/select_documents/unlikely_to_verify.html.erb
- app/views/select_phone/index.html.erb
- app/views/select_phone/no_mobile_phone.html.erb
- app/views/shared/_page_title.html.erb
- app/views/sign_in/index.html.erb
- app/views/start/index.html.erb
- app/views/why_companies/index.html.erb
- app/views/will_it_work_for_me/index.html.erb
- app/views/will_it_work_for_me/may_not_work_if_you_live_overseas.html.erb
- app/views/will_it_work_for_me/why_might_this_not_work_for_me.html.erb
- app/views/will_it_work_for_me/will_not_work_without_uk_address.html.erb
- spec/features/users_browser_sends_client_side_analytics_spec.rb
This PR will render page titles in english in a meta tag so that we could use english titles irrespective of the language chose to report to analytics.
> 3475 welsh titles in english

- app/views/errors/no_cookies.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Instead of manually calling .html_safe on our translation string in the
view, use the I18n module's convention for automatically allowing HTML
in translation keys that end in _html. This has the added benefit of
making clear in the translation file that the translation string will
NOT be sanitised for HTML.
> BAU: Use the I18n module's html convention

- lib/support/raven/logger.rb
- spec/lib/support/raven/logger_spec.rb
We currently hook up sentry to the raven logger to capture exceptions and error
messages. 404s are logged as errors using the `ActionController::RoutingError`.
As 404s are not something we can action usually this change will remove them
from Sentry.
> 3657: stop sending 404s to sentry

- config/locales/cy.yml
- config/locales/en.yml
We are changing the text that appears under private transaction
names in the transaction list of the timeout page so that it is
more generic.
Authors: @yolinas
> z21168 : changing hint text for private transactions

- app/controllers/about_controller.rb
- app/controllers/application_controller.rb
- app/controllers/choose_a_certified_company_controller.rb
- app/controllers/confirm_your_identity_controller.rb
- app/controllers/select_documents_controller.rb
- app/controllers/select_phone_controller.rb
- app/controllers/sign_in_controller.rb
- app/models/identity_provider.rb
- spec/features/cache_identity_providers_in_session_spec.rb
- spec/models/identity_provider_spec.rb
Identity Providers will be lazily loaded into the session object as they're
required. This should reduce the number of internal API calls needed when we
need to work with the list of available IDPs.
This has been taken as a step towards returning the list of IDPs at the start of
a session alongside the session's transaction.
I'm of two minds regarding whether this code should be placed inside a mixin or
interstitial controller base class (e.g. ChooseACertifiedCompanyController
< FederationController < ApplicationController) so I'm open to opinions.
> 3628: store current identity providers in session

- app/assets/stylesheets/pages/_slides.scss
- app/views/confirmation/index.html.erb
- app/views/start/index.html.erb
The confirmation page is using the `.hub-start` class to get a bigger heading than usual, but that has the side effect of pushing the button left by 15px (we do this on the start page to align with the radio buttons).
If we use [elements’ `.heading-x` classes](http://govuk-elements.herokuapp.com/typography/#typography-headings) to control heading styles we can remove our custom weights and the class from the confirmation page that was affecting the button margin. The only change we need to make to our CSS is to remove the top margin on headings.
> BAU: fix confirmation button alignment

- app/views/response_processing/matching_error.html.erb
Fixes issue where RP name was hard coded as 'Test RP'.
> Use RP name on matching error page

- app/views/errors/cookie_expired.html.erb
- app/views/errors/session_timeout.html.erb
- spec/features/user_encounters_error_page_spec.rb
`session_timeout` and `cookie_expired` pages have broken feedback links. This updates their link paths, and adds a check to the session_timeout spec to make sure it’s there.
> 3638: fix error page feedback links

- app/controllers/sign_in_controller.rb
- app/models/analytics/federation_reporter.rb
- spec/models/analytics/federation_reporter_spec.rb
Move the code to build the Piwik request setting the IdP selection for
login custom variable into FederationReporter.  This means the code can
be unit tested, and there's less code in the controller.
> BAU: move reporting of IdP login to FederationReporter

- lib/support/raven/logger.rb
- spec/lib/support/raven/logger_spec.rb
If raven-ruby encounters an error while sending a message to Sentry (e.g.
a network error) it will use the rails logger to log an error message.
Unfortunately, we try to log error messages from the Rails logger to Sentry
using Raven so this introduces a bit of a loop which can result in a segfault if
the network error persists.
This change instructs our mechanism that logs messages to sentry from the Rails
logger to ignore messages that start with the Raven log message prefix.
> bau: don't send raven log messages to sentry

- app/assets/javascripts/continue_to_idp.js
- app/controllers/application_controller.rb
- app/controllers/choose_a_certified_company_controller.rb
- app/controllers/sign_in_controller.rb
- app/models/idp_eligibility/checker.rb
- app/views/choose_a_certified_company/_idp_option.html.erb
- app/views/choose_a_certified_company/_select_idp_form.html.erb
- app/views/shared/_idp_list.erb
- spec/features/user_visits_choose_a_certified_company_page_spec.rb
- spec/features/user_visits_sign_in_page_spec.rb
- spec/features/user_visits_the_choose_a_certified_company_about_idp_page_spec.rb
- spec/javascripts/continue_to_idp_spec.js
- spec/models/idp_eligibility/checker_spec.rb
There are a few places where we rely on form params to provide
information about the IdP selected by the user, for instance the entity
id and display name.
There's no need to do this any more, because this information can be
retrieved from the session given the simple id, and doing it this way
reduces the opportunity for a malicious user to introduce bad data.
This change removes the entity id and display name from IdP selection
forms, and just uses the simple id to look up the IdP and get the rest
of the information.
> 3685 dont trust user input

- app/models/session_proxy.rb
- spec/api_test_helper.rb
- spec/models/session_proxy_spec.rb
The IP address for the user is sent as the X-Forwarded-For header
> 3729: proxy ip addr as header when request RP response

- app/controllers/application_controller.rb
- app/controllers/choose_a_certified_company_controller.rb
- app/controllers/redirect_to_idp_warning_controller.rb
- app/controllers/select_documents_controller.rb
- app/controllers/select_phone_controller.rb
- app/models/select_documents_form.rb
- app/models/select_phone_form.rb
- app/models/selected_answer_store.rb
- spec/features/idp_selections_reported_to_piwik_spec.rb
- spec/features/user_visits_choose_a_certified_company_page_spec.rb
- spec/features/user_visits_confirm_your_identity_page_spec.rb
- spec/features/user_visits_redirect_to_idp_warning_page_spec.rb
- spec/features/user_visits_select_documents_page_spec.rb
- spec/features/user_visits_select_phone_page_spec.rb
- spec/features/user_visits_the_choose_a_certified_company_about_idp_page_spec.rb
- spec/models/select_documents_form_spec.rb
- spec/models/select_phone_form_spec.rb
- spec/models/selected_answer_store_spec.rb
**Please do not merge** - 1a0ab09 needs to have been live for at least one session length (2 hours) to ensure all the users have the `selected_answers` hash in their sessions.
We are now using selected answers exclusively for determining which IDPs
are displayed to the user. SelectedAnswerStore is responsible for
mapping the user's answers to the evidence array that is used for IDP
filtering.
Authors: @vixus0 @andrien.ricketts @richardTowers
> 3668: Remove selected evidence from session

- app/assets/javascripts/feedback.js
- app/assets/javascripts/vendor/jquery.inputevent.js
- spec/features/user_visits_feedback_page_spec.rb
- spec/javascripts/feedback_spec.js
IE9 advertises support for the `input` event, but has bugs with backspace / deletion and pasting text. As the `keydown` event is currently removed if `input` is supported, this means IE9 will never update the character account if a backspace is used, and will permanently be off from the correct amount from that point.
We can integrate a jQuery `input` event normalisation plugin to fix this. This also has the side benefit of fixing IE8’s event to allow for updates during a held down keypress, something it previously couldn’t do with the `keydown` event it was using.
> Fix feedback character counter in IE9

- app/controllers/choose_a_certified_company_controller.rb
- app/controllers/sign_in_controller.rb
This removes support for the original form params used when selecting an
IdP - we needed to accept them for a while after rolling out the new
code to just use the entity id to identity the IdP, to avoid breaking
the journey for users who had already loaded one of the selection pages
at the time of the roll-out.
> 3685: Remove support for old form params

- config/initializers/rp_config.rb
Build is failing because 'allow_continue_on_failed_registration' is not
set in the verify-frontend-federation-config configuration. This change
allows for the flag not being set, returning empty array instead of nil.
> 3712: Allow flag to not be in config

- app/controllers/about_controller.rb
- app/controllers/application_controller.rb
- app/controllers/select_phone_controller.rb
- app/controllers/will_it_work_for_me_controller.rb
- app/views/about/choosing_a_company.html.erb
- app/views/will_it_work_for_me/may_not_work_if_you_live_overseas.html.erb
- app/views/will_it_work_for_me/why_might_this_not_work_for_me.html.erb
- spec/features/user_visits_about_choosing_a_company_page_spec.rb
- spec/features/user_visits_may_not_work_if_you_live_overseas_spec.rb
- spec/features/user_visits_select_phone_page_spec.rb
- spec/features/user_visits_why_might_this_not_work_for_me_page_spec.rb
- spec/features/user_visits_will_it_work_for_me_page_spec.rb
This adds support for a flag in the session which if set will show the
'Age' questions first.  By default it isn't set - the next release will
make it the default, but it's necessary to do it in two steps to avoid
breaking journeys that are in flight at the time of the roll-out.
> 3733 move age questions to start

- app/assets/javascripts/application.js
- spec/features/user_visits_select_phone_page_spec.rb
This is shipped with jquery-rails: it binds Rails’s helper methods through to the frontend. We’re not using any of the helpers currently and I don’t see us using them in future (we have dedicated per-page Javascript for that).
This saves us 25Kb unminified and un-gzipped.
(also included - a trivial fix for a lint failure)
> BAU: reduce js payload

- app/models/idp_eligibility/filter.rb
- spec/features/user_visits_choose_a_certified_company_page_spec.rb
- spec/models/idp_eligibility/filter_spec.rb
- spec/models/idp_eligibility/recommendation_grouper_spec.rb
- stub/idp-rules/stub-idp-demo.yml
IDPs returned from profile filters are not being returned as a Set. This has caused
a problem for sessions from a RP where we do not want demos to be enabled as
the IDP was appearing twice as it had both demo and non-recommended profiles
defined so was introduced in both lists that were joined.
> 3717: return IDPs from profile fitlers in sets

- config/initializers/cookie_validator.rb
- config/initializers/proxies.rb
In development mode, rails will unload certain constants
and reload certain files before each request. It does this to
reduce the cycle time required before a developer sees their
changes.
When classes are reloaded, existing values don't get their
class references updated to point at the new class (after all,
the class definition might have changed since the value
was created). If you hold on to a value having the type of
the unloaded class, Ruby will get confused when it tries to
reference constants defined on that class, since it no
longer exists.
We can work around this by creating our global values with
`to_prepare`, which runs a block before every request in
development mode, but just once in production mode.
Links:
https://github.com/rails/rails/blob/375d9a0a7fb329b0fbbd75a13e93e53a0 …
> Fix Rails per-request constant reloading

- spec/features/user_encounters_error_page_spec.rb
- spec/spec_helper.rb
When hitting a path we set the locale using I18n to the correct locale for that path (:en or :cy), but because all our tests run in the same thread the locale was kept until we hit a different locale path in another example. 
As the _path helper uses the locale to choose an appropriate path we were seeing tests hit welsh routes when we were intending for english ones if the the example followed a welsh language example.
> bau: reset locale to english before examples

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/select_documents.js
- app/assets/javascripts/vendor/jquery.validate.js
- spec/javascripts/feedback_spec.js
- spec/javascripts/select_documents_spec.js
- spec/javascripts/startpage_spec.js
- spec/javascripts/will_it_work_for_me_spec.js
Currently we use a [3rd-party gem](https://github.com/danryan/jquery-validation-rails) that seems to be mostly unsupported. jQuery Validate is two minor versions ahead of the gem, and the gem as it stands would block us upgrading to Rails 5. Given that, this PR removes the gem and directly includes a copy of the library.
There are numerous updates between 1.13.1 and 1.15.1: https://github.com/jzaefferer/jquery-validation/compare/1.13.1...1.15.0 . Most of them seem to be general code maintenance, better code localisation and small bug fixes in parts of the system we don’t use.
> BAU: upgrade jQuery Validate library

- pre-commit.sh
This automates the manual step of installing changed dependencies,
saving a few back and forth commands. With no dependencies changed, it
doesn't add noticable time to the build.
Solo: @lloydnye
> BAU: Automatically install dep changes in pre-commit

- config/routes.rb
Since we are still in the middle of migrating cycle3 to
the new frontend, some tests break when run without
nginx to do redirection to the old frontend to get at
the unmigrated page.
Introduce an environment variable we can set in dev-land
to do the redirection for us.
We should introduce this redirect even though we are about to migrate the last bit of cycle3 since
we shouldn't leave tests broken for any significant length of time.
@benhyland and @christopherholmes
> Special-case route for cycle3 further-information page

- lib/support/raven/logger.rb
- spec/lib/support/raven/logger_spec.rb
We currently hook up sentry to the raven logger to capture exceptions and error
messages.
Rails is currently logging 404s as errrors using the string representation of
the error (not just the exception).
As 404s are not something we can usually action this change will stop them from
being sent to Sentry.
> bau: don't send 404 messages to sentry

- app/controllers/application_controller.rb
- app/models/cookie_validator.rb
- app/models/cookie_validator/missing_cookies_validator.rb
- app/models/cookie_validator/no_cookies_validator.rb
- app/models/cookie_validator/session_id_cookie_validator.rb
- app/models/cookie_validator/session_start_time_cookie_validator.rb
- app/models/cookie_validator/transaction_simple_id_presence.rb
- app/models/cookie_validator/validation.rb
- app/models/cookie_validator/validation_failure.rb
- spec/feature_helper.rb
- spec/features/redirects_with_see_other_spec.rb
- spec/models/cookie_validator_spec.rb
We've had a few journeys  occur where after a user submits a duplicate SAML
message (perhaps after hitting the back and forwards button) they are treated
with an error message, but after a refresh are able to continue on for a few
pages despite their session missing a transaction simple id.
We want users to be see errors page as soon as they see an unhealthy state
so this PR introduces a check for the user's transaction simple as part of our
exisitng cookie validation. If the simple id is missing then the user will see
the standard something went wrong page.
> bau: Check for transaction simple id presence

- pre-commit.sh
When the $TERM is not set, on jenkins,  we don't want to set terminal colours as tput will
error.
> bau: don't set colours when TERM unset

- pre-commit.sh
If $TERM is undefined then we should skip the funky banner as this might cause
the build to fail.
Also, we should return the exit code using $success
> bau: skip funky banner on jenkins

- lib/tasks/zdd.rake
We occasionally run into a problem in some of our environments where we're missing
an envvar required for the service thats causes our zdd rake tasks to fail (as
they were dependent on the full Rails environment).
This currently requires some manual intervention before we can fix the
environment. By only using config that is required for ZDD we can mitigate the
impact of missing config on our build pipeline and hopefully remove these manual
steps form our process.
> bau: only use minimal config for ZDD

- app/controllers/application_controller.rb
- app/models/api/response_handler.rb
- app/models/api/upstream_error.rb
- spec/features/user_encounters_error_page_spec.rb
- spec/models/api/response_handler_spec.rb
If an error/problem occurs upstream within the Hub we receive a formatted
error message. As our upstream services also log their errors it shouldn't
be necessary to log them at a high level at the FE so I have changed it to only
log if it sees a message in an unexpected format (missing a type field).
Connection and Timeout errors will still be logged at error.
> 3580: log API server errors at warn

- app/views/redirect_to_idp/index.html.erb
- app/views/redirect_to_service/redirect_to_service.html.erb
- app/views/shared/_continue_to_idp_form.html.erb
SAML forms generally only include SAMLRequest and RelayState, with the
exception of our extensions (registration, hints) we shouldn't go beyond
these standard form parameters.
Rails includes an authenticity_token to prevent cross-site request
forgery however in this case the form 'action' is a separate domain
beyond our control so csrf tokens like this are not useful.
Rails docs say the utf8 ✓
> enforces browsers to properly respect your form's character encoding
Given the content of these forms is generated and not user submitted we
can be confident that we don't place any unicode characters in there.
Generally the bodies of these forms are base64 encoded XML so there is
very little room for unicode characters in any case.
> Remove Rails authenticity_token from SAML forms

- app/controllers/about_controller.rb
- app/controllers/further_information_controller.rb
- app/controllers/sign_in_controller.rb
- app/models/analytics/federation_reporter.rb
- app/models/display/rp_display_data.rb
- config/initializers/piwik.rb
- spec/models/analytics/federation_reporter_spec.rb
Rather than calling the federation translator directly and having to encode
knowledge of the locales inside the analytics reporter we can pass in the
RpDisplayData object that is available for our transaction.
In addition, we now check the locale files for the RP's analytics description
on start up of the app so we shouldn't get into a state where it is missing.
> refactor: use rp display data for reporting analytics

- app/views/feedback/index.html.erb
- app/views/further_information/index.html.erb
- app/views/select_documents/index.html.erb
- app/views/select_phone/index.html.erb
- app/views/start/index.html.erb
- app/views/will_it_work_for_me/index.html.erb
- lib/verify_form_builder.rb
- spec/lib/verify_form_builder_spec.rb
Repeat the work done for custom radios for custom check boxes. The standard `check_box` helper has a different argument order to `radio_button`; I’ve mirrored that but could be persuaded to match `radio_button`’s argument order.
> 3795: form helper for custom check boxes

- app/assets/stylesheets/helpers/_validation-message.scss
Some users were seeing problems with the select-phone page where the JS
to show the conditional questions would not work. This left them in a
state where the form was invalid, but they were unable to fill in the
mandatory questions.
This ensures that we always show hidden questions when they are marked
as invalid.
@robinwhittleton - we think this might be best pushed upstream to govuk_elements. Not sure where to put it though.
Authors: @richardtowers @andrien.ricketts
> ZD22311: Show validation errors even when js-hidden

- app/controllers/start_controller.rb
The start form needed to cope with old parameters being passed in. Now that the new form is live and users of the old system have drained we can remove the mitigation code.
> 3795: remove start form ZDD protection

- spec/feature_helper.rb
The javascript-tests are written against Firefox and
easily fail on another browser. Selenium chooses another
browser when there is no Firefox available in the system.
Pair: @vixus0 @tunylund
> BAU Explicitly depend on Firefox browser

- Gemfile.lock
- app/assets/javascripts/analytics.js
- app/assets/javascripts/auto_submit_form.js
- app/assets/javascripts/continue_to_idp.js
- app/assets/javascripts/feedback.js
- app/assets/javascripts/further_information.js
- app/assets/javascripts/select_documents.js
- app/assets/javascripts/select_phone.js
- app/assets/javascripts/validation.js
- app/assets/javascripts/verify_fingerprint.js
- app/assets/javascripts/will_it_work_for_me.js
- spec/javascripts/auto_submit_form_spec.js
[govuk_frontend_toolkit](https://github.com/alphagov/govuk_frontend_toolkit) has a [new module pattern](https://github.com/alphagov/govuk_frontend_toolkit/pull/290). Our JS should match the standard where possible for simplicity. This commit updates govuk_frontend_toolkit to the latest version and brings our JS in line.
It also updates jasmine_rails to the latest point version, which fixes a potential memory leak issue.
> BAU: update JS to follow new GOV.UK module pattern

- Gemfile
- Gemfile.lock
- README.md
- app/views/test_saml/index.html.erb
- kill-service.sh
- pre-commit.sh
- startup.sh
- stub/stub_api.rb
- stub/stub_api_conf.ru
- stub/stub_api_spec.rb
**Don't merge yet - wants discussion**
This moves the experimental `richardTowers/mock-verify-hub` code into verify-frontend proper. There are some basic unit tests which hopefully should be enough (just about) to prevent the stub-api from diverging from the real API. See the changes to the README to get an idea of how it would work.
The main reason we'd want to do this is to give non-verify developers an easy way to run the frontend on their machines. At the moment this isn't possible because (for now) there's still closed-source code running behind the API.
Feedback on whether this is the best way to do this / the right place for the code / a good idea in the first place welcome.
> Stub api calls

- app/views/confirmation/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_visits_confirmation_page_spec.rb
Feedback from services is that the button can be too big, depending on
the service name. 
Suggestion from UX folks is to replace the service name by 'Continue' on the button and introduce a new paragraph that informs the user can proceed to the service.
Authors: @adityapahuja @phss
> 3843: Move service name out of the button

- app/views/further_information/index.html.erb
- spec/features/user_visits_further_information_page_spec.rb
The nullable attribute form was being nested within the main input form which
was causing it to be overriden. Unfortunately, this was not caught by the non-js tests.
This change moves the button to below the continue button and above the
cancellation button.
> 3342: stop nesting nullable attribute form

- spec/feature_helper.rb
The check to force firefox in the feature tests had caused FF to start
on every test. This is super annoying, so we think we should just remove
the check for now.
Authors: @richardtowers @datamineruk
@chrisholmes @tunylund - discussion / premature merges welcome :trollface:
> bau: fix firefox instances starting up for all tests

- app/controllers/authn_request_controller.rb
- spec/features/user_sends_authn_request_spec.rb
We will be using a temporary cookie to enable routing through to the new cycle
three page. It will be set on all new journeys and users will be routed via nginx to the new cycle 3 page only if the cookie is set correctly.
After 2 hours we will remove the cookie routing on nginx followed by the removal
of the cookie.
> 3342: set a cookie to enable routing to new cycle 3 page

- app/controllers/authn_request_controller.rb
- spec/features/user_sends_authn_request_spec.rb
Reverts alphagov/verify-frontend#185
This is no longer necessary as we're not using the cookie for page routing any more.
> 3332: remove setting cookie for cycle 3 page routing

- app/controllers/feedback_controller.rb
- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
- spec/features/user_submits_feedback_page_spec.rb
- spec/features/user_visits_feedback_page_spec.rb
Query params are no longer required because we're using the flash cookie now.
Moves the feedback-sent route into the localized block. This is safe from a ZDD perspective because we've already deployed routes for both the english and welsh journeys.
> 3704 feedback sent page - localize routes and remove query params

- spec/feature_helper.rb
This tests was failing consistently for me when firefox was popping up
on my laptop screen. I had a play around with screen resolutions and it
looks like the test fails on low resolutions and passes on high
resolutions. I think this is due to a bug (?) in Capybara / Selenium
where it can't click on an element that is "below the fold".
This fix is definitely a hack. Better suggestions welcome.
> bau: Fix a test that seems to depend on resolution

- README.md
- startup.sh
This avoids problems where the real API tries to start on a port that's
already been grabbed by the stub API.
> BAU: Run stub-api on a different port to the real API

- app/controllers/application_controller.rb
- config/initializers/store_session_id.rb
- lib/store_session_id.rb
- spec/lib/store_session_id_spec.rb
The session is missing from some of our logs because it is only captured for
logstash when we reach the controller and after the CSRF check is performed.
This isn't helpful in some cases when trying to understand a user's journey and
session flows.
By switching to a middleware approach we can capture the session id before request
based logs are made.
> bau: use middle to store session id for logging

- spec/models/ab_test/ab_test_spec.rb
Setting the const in test cases results in warnings in the logs. This approach fixes that.
We've used stub_const elsewhere to test code that uses const values.
Solo: @lloydnye
> 5017: Use stub_const

- app/controllers/application_controller.rb
We're encountering a few InvalidAuthenticityToken errors in production which are
raising errors in our logs. It appears that these errors are occuring because
somebody is submitted something when they don't have a valid session.
If we validate the session early then we should be able to remove these errors
and display something more appropriate for the user.
> bau: validate session before CSRF

- lib/store_session_id.rb
- spec/lib/store_session_id_spec.rb
When we send an error to sentry it would be helpful if we include the session id
as a parameter so that we can correlate it easily against other logs/errors.
Usually, we wouldn't have to do this ourselves with Raven as it usually includes
cookies with the error, but we have disabled this so that we don't leak the
user's secure cookie. To work around this we can set a user context containing
the session id.
> bau: add session id to raven user context

- app/views/layouts/application.html.erb
The [Subresource Integrity specification](https://www.w3.org/TR/SRI/) adds a new `integrity` attribute to `<script>` and `<link>` elements that is a hash of the asset they point to. [sprockets-rails](https://github.com/rails/sprockets-rails) will now automatically generate this attribute if you supply an `integrity: true` parameter to either `javascript_include_tag` or `stylesheet_link_tag`, which this commit does. Browsers that support SRI can then hash the downloaded asset and check that it matches the hash specified in the integrity attribute.
The real benefit of SRI is for people using CDNs where you can’t be sure the assets haven’t been tampered with. In our case, it’s a cheap enough win that it’s probably worth doing it anyway as another barrier against MitM attacks. Browsers that …
> BAU: validate Verify JS and CSS with SRI

- app/models/session_validator.rb
- app/models/session_validator/cookie_size_validator.rb
- spec/models/session_validator_spec.rb
We store a lot of stuff in the session cookie. This commits add code
to log a warning if it's getting too large.  Without going too deep
into Rails we can log an approximation of the size, at a slightly
lower threshold.
Perhaps we can move this into the ApplicationController; I don't mind
too much as long as we can have some sort of visibility of this
becoming an issue.
Pair: WillPa
> bau: log session cookie size if it's large

- config/initializers/metrics.rb
- lib/metrics.rb
- lib/metrics/response_status_reporter.rb
- spec/lib/metrics/response_status_reporter_spec.rb
We would like to see the occurrences of different status codes in our responses
to users so that we can provide a visualisation relating to the health of our
system (count of 2xxs vs 3xxs vs 4xxs vs 5xxs).
I have used the statsd/notifications metric reporter system to provide these metrics
> 5072: report metrics around HTTP status code counts

- Gemfile.lock
- app/assets/javascripts/application.js
- app/views/about/certified_companies.html.erb
- app/views/about/choosing_a_company.html.erb
- app/views/about/identity_accounts.html.erb
- app/views/about/index.html.erb
- app/views/confirmation/index.html.erb
- app/views/failed_registration/index_continue_on_failed_registration.html.erb
- app/views/failed_sign_in/index.html.erb
- app/views/shared/_unavailable_idp_list.erb
All links styled to look like buttons should have a `role="button"` attribute to correctly define to assistive tech what the expectation of their use is. To make sure that they behave as buttons to the user, we also add the spacebar-to-activate behaviour with Javascript.
> 5078: make link buttons behave like buttons to assistive tech

- app/helpers/application_helper.rb
- app/views/about/certified_companies.html.erb
- app/views/about/choosing_a_company.html.erb
- app/views/about/identity_accounts.html.erb
- app/views/about/index.html.erb
- app/views/confirmation/index.html.erb
- app/views/failed_registration/index_continue_on_failed_registration.html.erb
- app/views/failed_sign_in/index.html.erb
- app/views/shared/_unavailable_idp_list.erb
- spec/helpers/application_helper_spec.rb
Creating a `button_link_to` helper reduces the chance that link buttons won’t have the correct role applied. If a `class` attribute is supplied it’ll append `button` to the existing one, but we’d only ever want a `role="button"` so that is overridden. Other parameters are passed straight through.
> 5078: make sure that link buttons have roles

- app/assets/javascripts/verify_fingerprint.js
By default Fingerprint2 logs messages like "you don't have flash
installed, so skipping flash fingerprinting" to the user's console. This
message is not useful for the average user, and at worst may persuade
some users to install flash (horror).
Also, if someone needs to report an error to the support team and they
happen to be technical enough to send us the logs from the console this
will remove irrelevant noise from that report.
Authors: @adityapahuja @richardtowers
> bau: Disable console logging of fingerprint diagnostics

- spec/features/user_visits_sign_in_page_spec.rb
have_not_been_made does not match requests as expected. It requires the very specific request to have been made in order to fail.
The actual page here does make a request to Piwik (because the user hits the sign in page), so I have changed the test to show that.
Solo: @lloydnye
> BAU: Remove use of have_not_been_made

- app/models/session_validator/validation_failure.rb
- spec/features/user_visits_start_page_spec.rb
Discussion in code quality meeting came to consensus that this is a client error so should have a 400 series http response.
Solo: @lloydnye
> BAU: Cookie mismatch is a bad request

- config/application.rb
Content-Security-Policy (CSP) is applied to restrict browser behavior to
the features used within the verify-frontend.
This policy is purposefully quite lenient, allowing any inline-scripts
to execute. We intend to add a reporting-uri in the future and iterate
our policy to further restrict browser behavior.
Specifically this policy only allows resources to be fetched from
'self' (origin of the document being served) it further restricts the
fonts to load using the 'data' scheme as they are provided from the
frontend_toolkit. We disallow embedding any object/applets. Scripts can
be loaded from self or as inline html, the same policy is applied to
stylesheets.
> Set a basic, lenient CSP header

- app/views/static/cookies.cy.html.erb
- app/views/static/cookies.en.html.erb
- spec/features/user_visits_cookies_page_spec.rb
the cookie notice must be changed to reflect the removal of the secure cookie.
@gdsamit has reviewed the changes and has given it an OK.
> 5026: update cookie notice

- lib/store_session_id.rb
The cookies names were being re-evaluated during the jasmine run due to this
require statement and spewing warnings we'd rather avoid.
> bau: fix CookieNames constants warning

- app/controllers/choose_a_certified_company_controller.rb
- app/controllers/redirect_to_idp_warning_controller.rb
- app/models/analytics/federation_reporter.rb
- app/views/choose_a_certified_company/_idp_option.html.erb
- app/views/choose_a_certified_company/index.html.erb
- spec/features/idp_selections_reported_to_piwik_spec.rb
- spec/features/user_visits_redirect_to_idp_warning_page_spec.rb
- spec/models/analytics/federation_reporter_spec.rb
- spec/piwik_test_helper.rb
This was needed to gather data on whether IdPs at the top of the list
are selected more often than those further down. We have enough data to
be confident that it does now, so this extra logging is no longer
required.
We'd leave it in place, but having such a large number of permutations
for this virtual page title confuses the piwik UI, and that will be
annoying for the analytics team. More seriously, the page title we
modified is used for calculating the success rate in demo periods. We're
not sure if the change might have skewed the results a bit, so we'd like
to go back to the old format for the next demo period.
If we need similar behaviour in the future (which we probably will) we
should have a bit more of a think about where to put it and what the
effect on the piwik UI will be. …
> 5057: Revert all commits adding "(position x of n)"

- app/views/about/certified_companies.html.erb
- app/views/about/choosing_a_company.html.erb
- app/views/about/identity_accounts.html.erb
- app/views/redirect_to_idp_warning/_recommended.html.erb
- app/views/select_phone/no_mobile_phone.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_visits_redirect_to_idp_warning_page_spec.rb
In several content sections individual paragraphs are being internationalised. If in the future we change the number of paragraphs we’d have to rework the keys in the localisation. The current method also fixes both translations to the same number of paragraphs, which might not be ideal.
This commit migrates these content sections into extended _html sections in the YAML. It also changes a spec that was testing for text node equality: as Capybara’s output for the page lacks HTML tags the content of the YAML file wasn’t matching.
> BAU: allow for changes in content without introducing new keys

- app/views/start/index.html.erb
- config/application.rb
- spec/features/user_visits_start_page_spec.rb
Rails 5 automatically disables submit buttons after they’ve been clicked on once. If you go back on our pages it remembers the disabled state, thus breaking the system. We can turn this functionality off globally.
> BAU: stop Rails 5 automatically disabling submit buttons

- app/controllers/errors_controller.rb
Not all non matching routes were returning our 404.html. A request like
/doesnotexist.html would, but not /doesnotexist.{png,jpeg} - which would return
a 500 internal server error page. This commit enables ErrorsController to deal
with requests with weird/unknown/not-applicable mime types and returns our
normal 404.html.
Unfortunately doing format.all { render '404', status: 404 } in the
ErrorsController didn't work - it would still return the 500 internal server
error page - hence the redirection to '/404'.
@oswaldquek
> bau: return 404.html for all non matching routes

- app/views/layouts/application.html.erb
- config/locales/cy.yml
- config/locales/en.yml
The current cookies banner points at GOV.UK’s cookies page, but should point at Verify’s. This also enables Welsh translation.
> BAU: point cookies message at Verify

- app/controllers/errors_controller.rb
It is possible that some assets on the page might request invalid resources as
well. In this case it's better to return a head 404 rather than redirect.
@oswaldquek
> bau: return head 404 instead of redirection

- config/environments/production.rb
- jenkins.sh
Separated assets from front package so we can install assets before
installing app package, to prevent 404s of assets during deployment.
Front package depends on front-assets, in order to guarantee being
installed.
Authors: @joerayme @tunylund @phss
> 5024: Generate static assets separately

- stub/api/Gemfile.lock
- stub/api/stub_api.rb
- stub/api/stub_api_spec.rb
The session API endpoints pass session_id in as part of the URL now. (See [session_endpoints.rb](https://github.com/alphagov/verify-frontend/blob/d7543b566c614fc2f36643aec0f9ad88fc01fd2f/app/models/session_endpoints.rb)).
Updates the stub API to serve requests from these URLs now.
Authors: @richardtowers
> BAU: Fix stub API paths (fixes #231)

- Gemfile.lock
[govuk_template 0.18.2](https://github.com/alphagov/govuk_template/releases/tag/v0.18.2) adds the ability for the styling to recover in the event that external JS has failed to load. These scenarios are rare but potentially problematic.
> BAU: cope with broken JS in some situations

- Gemfile
- Gemfile.lock
- config/puma.rb
Puma doesn't support multiple workers on windows. Gem config file needed
3 extra dependencies for windows.
Puma also doesn't support being run in daemon mode, which means that
./startup.sh doesn't work. It's possible to work around this by manually
running puma without the daemonize flag.
Authors: @niyi @richardtowers
> Bau: Improve windows support

- pre-commit.sh
- startup.sh
This adds a few 100ms to the time taken to run the script, but it
ensures that you don't get the horrible "you need to run bundle install"
error.
Authors: @richardtowers
> bau: Add bundle install to startup.sh

- app/models/hints_mapper.rb
- spec/models/hints_mapper_spec.rb
Introducing {has/not}_ukphotolicense_{gb/ni} to distinguish between gb and ni
licences.
Note that not_ukphotolicense is sent when user has selected NO to both gb and ni
licences but has_ukphotolicense is not sent when user has selected YES to both
gb and ni licences.
These changes will eventually be reverted when DCS can verify ni licences as
well.
@oswaldquek @sfkamath
> 5175: Add new hints for driving licences

- jenkins.sh
- packaging/postinst.sh
Make pkgr use the current Heroku Ruby buildpack
Update postinst.sh to allow deployer to access files under
/opt/front/vendor/bundle as these files are owned by root
Authors: @adityapahuja @maurorappa @mmhmm
> 5065: Use Heroku Ruby buildpack

- config/application.rb
Also add script to generate checksums of inline JS, and add them to the
policy.
Tested with reporting in latest Firefox, Chrome & Safari
Pair: WillPa / DavidK
> bau: add csp checksums

- .env
- .gitignore
- app/controllers/test_analytics_controller.rb
- app/controllers/test_csp_reporter_controller.rb
- config/application.rb
- config/routes.rb
CSP errors were happening locally because Piwik requests were not
being routed via the frontend. Therefore, rewrite requests through to
local Piwik when running locally.
This also adds a test CSP reporter that can be turned on to view what
browsers are sending.  It's not enabled by default; see how to enable
it in routes.rb.  Interesting to note that we have to do this because
Firefox requires the CSP reporter to be on the same host/port as the
site.  Safari and Chrome are ok with it being a different host/port.
Also fixes the linting issues that I should have fixed before the last
PR :(
Pair: WillPa
> bau: route test analytics and test csp reporter via frontend

- app/controllers/feedback_controller.rb
- app/controllers/feedback_sent_controller.rb
- app/models/feedback_source_mapper.rb
- app/views/feedback_sent/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_submits_feedback_page_spec.rb
- spec/models/feedback_source_mapper_spec.rb
- spec/rails_helper.rb
Using a map to link feedback sources to corresponding paths after feedback has been submitted.
Authors: @DataMinerUK @phss
> 3262 feedback link with mapper

- app/controllers/application_controller.rb
- app/controllers/select_documents_controller.rb
- app/controllers/start_controller.rb
- spec/features/user_visits_select_document_page_ab_test_spec.rb
- spec/features/user_visits_start_page_spec.rb
- stub/ab_test.yml
Since we were reporting to piwik on start page, the performance team was
getting unreliable results.
Author: @DataMinerUK @phss
> 5404: Only report to piwik on select documents page

- config/application.rb
There was a short downtime on verify frontend due to a missing
configuration that needs to be put in place by hand. The error could
have been noticed sooner if the application would have raised an error
on the missing configuration.
Solo: @tunylund
> 5226: Raise an error on startup if missing a secret

- .env
- app/controllers/choose_a_certified_company_controller.rb
- app/models/display/identity_provider_display_decorator.rb
- app/models/display/idp_ranker.rb
- config/initializers/00_configuration.rb
- config/initializers/30_federation.rb
- spec/features/user_visits_choose_a_certified_company_page_spec.rb
- spec/features/user_visits_start_page_spec.rb
- spec/models/display/identity_provider_display_decorator_spec.rb
- spec/models/display/idp_ranker_spec.rb
- stub/ab_test.yml
- stub/idp-rules/stub-idp-demo.yml
- stub/idp-rules/stub-idp-three.yml
- stub/idp-rules/stub-idp-two.yml
- stub/idp_rankings.yml
Adds a ranking step to the Choose a Certified Company page. The ranking
is defined in verify-frontend-federation-config.
NOTE: we are still waiting for Olly's ranking data. Therefore we are
not sending requests to piwik!
We have test data in place to test it only in the Joint
environment.
Authors: @srinivasmurty @phss
> 5482: AB test for IDP rankings

- app/controllers/about_controller.rb
- app/models/display/rp_display_data.rb
- app/views/about/certified_companies.html.erb
- app/views/about/identity_accounts.html.erb
- app/views/about/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/ab_test_rp_slides_spec.rb
- spec/features/server_sends_analytics_spec.rb
- spec/features/user_visits_about_identity_accounts_page_spec.rb
- spec/features/user_visits_start_page_spec.rb
- spec/models/display/rp_display_data_spec.rb
- stub/ab_test.yml
- stub/locales/rps/headless-rp.yml
- stub/locales/rps/loa1-test-rp.yml
- stub/locales/rps/test-rp-noc3.yml
- stub/locales/rps/test-rp-repudiation.yml
- stub/locales/rps/test-rp-with-continue-on-fail.yml
- stub/locales/rps/test-rp.yml
Adding RP context for about page,
more info about registering with IDPs on about certified companies page
and more details about Verify journey on the about identity accounts page
for B group only
Author: @DataMinerUK
> 5500: Add alternative views for RP slides ab test

- spec/feature_helper.rb
- Setting the FIREFOX_PATH env var to point to a specific `firefox-bin`
will force Selenium to use that in its web driver tests.
- This allows you to have the current Firefox installed in Applications
and kept up to date alongside an older version (probably 47.0.1)
somewhere else.
> BAU: Specify Firefox binary for Selenium

- kill-service.sh
pid file is stub_api.pid, not stub-api.pid.
Also removes a useless use of cat (replacing it with a probably useless
use of xargs, but hey-ho).
Authors: @richardtowers
> bau: Fix kill-service.sh to kill the stub api properly

- app/models/display/rp/display_data_correlator.rb
- spec/models/display/rp/display_data_correlator_spec.rb
This commit makes it such that the RP's listed in relying_parties.yml's
transaction_type.display_name_and_homepage property are listed in that
order when a list of services is shown on the session timeout page, and
the 'about identity accounts' page.
A test in display_data_correlator_spec.rb that throws an error when a simpleId
json field is missing from the transaction data returned by the config service
API has been removed as we think this shouldn't stop the list of services from
being shown on the pages. If a simpleId field json field is missing, the code
deals with that and doesn't shown that RP.
@oswaldquek @sgreensmith
> TT-227: Order Verify servies by volume of use

- app/controllers/other_identity_documents_controller.rb
- app/models/selected_answer_store.rb
- spec/models/selected_answer_store_spec.rb
Author: @DataMinerUK
This fixes the issue with hints and ensures evidence is the same for all groups in the AB test
> TT-356 Update selected answer store for other identity documents

- app/controllers/authn_response_controller.rb
- app/models/analytics/federation_reporter.rb
- lib/analytics/custom_variable.rb
- spec/features/user_sends_authn_response_spec.rb
- spec/models/analytics/federation_reporter_spec.rb
Verify front-end reported to piwik the events 'successfully registered/signed-in with an IDP' followed by the 'LOA level Achieved'. Due to the asynchronous nature of the reporting mechanism these events would sometimes be sent in the wrong order .
This has been resolved by combing those two separate events into one.
The 'LOA Level Achieved' custom variable has subsequently been removed.
> TT-386: Piwik analytics ordering for IDP sign-in/register and LOA achieved

- app/controllers/choose_a_country_controller.rb
- app/controllers/redirect_to_country_controller.rb
- app/models/country_response.rb
- app/models/session_endpoints.rb
- app/models/session_proxy.rb
- spec/features/user_visits_redirect_to_country_spec.rb
- spec/models/session_proxy_spec.rb
- Updated setup_countries not to return session id to avoid causing confusion.
- Updated get_countries method to validate response and returns a list of country objects.
- Replaced hard coded URL with API endpoint in select_a_country method.
- Updated redirect to country page to stop non-eIDAS users from visiting this page.
Solo: @adityapahuja
> BAU: Tidy up countries method calls

- pre-commit.sh
Travis runs the spec tests through `rake` whereas the pre-commit script
(used for local dev and Jenkins) runs them directly via `rspec`. This
led to issues where the tests ran locally but failed on Travis. The
`RAILS_ENV` environment variable must be set to `test` for Rake to work.
> BAU: Make pre-commit run specs through Rake

- app/models/select_phone_variant_form.rb
- spec/models/select_phone_variant_form_spec.rb
- this will allow us to determine if a user actually chose an IDP that required an app to be installed despite originally preferring not to
- analytic is set in the evidence using the identifier smart_phone_prefer_not_to (adding this to the evidence doesn't affect IDP rules matching)
> TT225 - Added analytic to record when the "Yes, but I prefer not to" option is chosen on select phone page

- spec/controllers/choose_a_certified_company_spec.rb
- spec/controllers/choose_a_certified_company_variant_spec.rb
- spec/controllers/confirmation_spec.rb
- spec/controllers/select_phone_controller_spec.rb
- spec/features/user_visits_choose_a_certified_company_variant_page_spec.rb
See issue #295 
We were unnecessarily stubbing/mocking parts of the application in our
controller tests. Instead, we should be using existing fixtures and let
the Rails app handle initialising constants etc.
I've also removed `render_views` from all the controller tests and no
longer assert on the contents of the rendered view. That
should only be done in feature tests.
> GH295: Tidy up some controller tests

- app/assets/javascripts/analytics.js
- app/helpers/application_helper.rb
- spec/features/users_browser_sends_client_side_analytics_spec.rb
- spec/helpers/application_helper_spec.rb
We currently report the requested and achieved LOAs to Piwik via custom variables. However, attempting to partition user journeys by custom variables through the Piwik UI leads to Piwik only using a subset of all the data available. Until a more permanent solution is found, we can report the requested LOA along with the page title (action name in Piwik terms).
> TT-664: Send requested LOA in page titles to Piwik

- app/controllers/application_controller.rb
- app/controllers/authn_response_controller.rb
- app/controllers/choose_a_country_controller.rb
- app/controllers/further_information_controller.rb
- app/controllers/redirect_to_idp_controller.rb
- app/controllers/redirect_to_idp_warning_controller.rb
- app/controllers/redirect_to_service_controller.rb
- app/controllers/response_processing_controller.rb
- app/controllers/sign_in_controller.rb
- app/helpers/application_helper.rb
We currently use a mix of strings and symbols to refer to the same
Rails session values which is confusing. Symbols feel somewhat more
appropriate for defining session keys as Ruby hashes typically use
symbols for keys.
> BAU: Make session keys consistently symbols

- config/locales/en.yml
By using the other_ways_description we ensure that the service name is
lower cased when prefixed with 'Continue'
> ZD33435 Ensure service name is lower cased

- app/assets/javascripts/application.js.erb
- config/routes.rb
- spec/constraints/select_route_spec.rb
- spec/controllers/choose_a_certified_company_variant_controller_spec.rb
- spec/controllers/select_phone_variant_controller_spec.rb
- spec/features/user_visits_choose_a_certified_company_variant_page_spec.rb
- spec/features/user_visits_select_phone_variant_page_spec.rb
- stub/ab_test.yml
- App transparency test was disabled by setting the control to 100%.
This was fine for new users but if previous users aleady had the app
transparency cookie set to variant they still saw the variant page.
Remedied by removing the cookie and ab logic from routes.rb
- Controller/Feature tests for the variant pages have been commented out
as they will fail to run when no ab test routes present.
- The variant version of controllers/templates have not been removed as
a decision on which version to keep has not been made yet
Author: @NasAshrafThoughtworks
> TT671 - Fixed issue for disabling App Transparency AB test

- app/views/failed_registration/index_continue_on_failed_registration.html.erb
- app/views/will_it_work_for_me/why_might_this_not_work_for_me.html.erb
- app/views/will_it_work_for_me/will_not_work_without_uk_address.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/controllers/will_it_work_for_me_response_spec.rb
- spec/features/user_visits_will_not_work_without_uk_address_page_spec.rb
- spec/support/will_it_work_for_me_examples.rb
- stub/locales/rps/test-rp-with-continue-on-fail.yml
Code changes mainly focus on two themes: streamlining the appearance of failed_registration and will_not_work_without_uk_address views for rps with continue-on-fail and to improve the tests that exercise the controller that routes to the will_not_work_without_uk_address view.
Changing views and message properties
Much of this story has related to designing UI messages that can be parameterised by properties of the relying party and still provide a uniform look to Verify’s web pages that show how it may not, will not or has not verified a user’s identity.  Changes to the UI messages sometimes had a side effect of appearing on some of these pages which were not the focus of the story.  
More broadly, there is an emerging design issue about how fine-grained you can make some UI messages so …
> Tt 563: Streamlining behaviour of failed_registration and won’t work pages

- config/locales/cy.yml
- config/locales/en.yml
The changes were made to improve user understanding. The word 'security'
has been replaced here with 'evidence' to provide a better clarity to
users. These changes will positively effect the following LOA1 pages:
- about-identity-accounts
- confirmation
- choose-a-certified-company
Authors: @cobainc0
> TT-722 Change language in the LOA1 journey

- Rakefile
- lib/tasks/lint.rake
- pre-commit.sh
Currently, the linters are only run when explicitly called in the
`pre-commit.sh` script. We use Travis to provide us with feedback on
test status when reviewing pull requests but it only runs Rake. This
means we can miss linter errors when merging a PR which will proceed
to fail later in our build system.
> BAU: Run linters by default in Rake

- app/controllers/redirect_to_idp_warning_variant_controller.rb
- spec/api_test_helper.rb
- spec/controllers/redirect_to_idp_warning_controller_spec.rb
- spec/controllers/redirect_to_idp_warning_variant_controller_spec.rb
registration
- a method in the variant version of a controller was accidentally
removed in the last release which is used to determine whether user
chose an recommended or non recommended idp when reporting to piwik
- this resulted in a NoSuchMethod error causing the idp regisrtation not
to be reported t piwik
- restoring this method remedies the idp registration reporting
> TT-792: Fix bug to allow front end to report which idp was chosen for

- app/assets/javascripts/interstitial_question.js
- app/controllers/redirect_to_idp_question_controller.rb
- spec/features/user_visits_redirect_to_idp_question_page_spec.rb
- stub/locales/idps/stub-idp-one-doc-question.yml
In the course of fixing TT-809, I discovered a bug that was in the redirect_to_idp_question controller where the idp name was not being made available to the view idp_wont_work_for_you.html.erb.  This has been fixed.
The redirect_to_ip_question page has been modified so that when user clicks "No" on the interstitial question, there is no warning that appears under the radio button.  Much of the text for this already appears after the Continue button so the same warning by the radio button was eliminated.  Removing the text made it necessary to change some of the tests.
The text for the stub-idp-one-doc-question was also changed to make it more informative.
> Tt 809 - Changing one doc IDP and fixing bug from TT-721

- app/assets/stylesheets/helpers/_verify-logo.scss
- app/assets/stylesheets/pages/_redirect-to-idp-warning.scss
- app/views/redirect_to_idp_warning/logos.html.erb
- app/views/sign_in/index.html.erb
Move header on sign-in page into two-thirds width column. Left-align logo to match the language options text.
Also adjust logo widths on redirect-to-idp-warning page
Authors: @hugh-emerson
> TT-811 adjustments

- .travis.yml
- app/controllers/authn_response_controller.rb
- app/controllers/test_saml_controller.rb
- app/models/country_authn_response.rb
- app/models/session_endpoints.rb
- app/models/session_proxy.rb
- app/views/test_saml/index.html.erb
- config/routes.rb
- spec/api_test_helper.rb
- spec/features/user_sends_authn_response_spec.rb
Country response in authn response controller will be used to receive eIDAS Authn Response from a country proxy node and will be forwarded to a new endpoint in saml-proxy. This will enable saml-proxy to process eIDAS Authn Response in a different way compared to Verify Authn Response (e.g. verifying country's signature using metadata aggregator instead of federation metadata).
Authors: @adityapahuja @lamerexter @sfkamath
> EID-153: Add a new endpoint country_response

- spec/api_test_helper.rb
- spec/features/user_visits_redirect_to_country_spec.rb
Import a test where a user lands directly on a redirect to country page
without first choosing a country from acceptance tests.
Authors: @timothyspence @adityapahuja
> EID-208: Cleanup eIDAS tests

- .env
- .env.test
- app/controllers/application_controller.rb
- app/models/api/client.rb
- app/models/display/rp/display_data_correlator.rb
- app/models/display/rp/transactions_proxy.rb
- app/models/session_endpoints.rb
- config/initializers/00_configuration.rb
- config/initializers/20_api_proxies.rb
- spec/api_test_helper.rb
- spec/controllers/about_spec.rb
- spec/features/redirects_with_see_other_spec.rb
- spec/features/user_encounters_error_page_spec.rb
- spec/features/user_sends_authn_request_spec.rb
- spec/features/user_visits_choose_a_country_page_spec.rb
- spec/features/user_visits_further_information_page_spec.rb
- spec/features/user_visits_sign_in_page_spec.rb
- spec/models/api/client_spec.rb
- spec/models/display/rp/display_data_correlator_spec.rb
- spec/models/session_proxy_spec.rb
- startup.sh
- stub/api/stub_api.rb
- stub/api/stub_api_spec.rb
[TT-732](https://govukverify.atlassian.net/browse/TT-732): Get Transactions directly from Config
Make the verify-frontend talk to Config service directly, instead of going via ida-frontend.
**Note:** This has to go **after** [app-config PR-15](https://github.digital.cabinet-office.gov.uk/gds/verify-frontend-app-config/pull/15) and [webops PR-3656](https://github.digital.cabinet-office.gov.uk/gds/ida-webops/pull/3656)
Authors: @jakubmiarka @MichaelWalker @hugh-emerson
> TT-732: Get Transactions from Config - implementation changes

- app/controllers/redirect_to_idp_warning_controller.rb
- app/models/analytics/federation_reporter.rb
- spec/controllers/redirect_to_idp_warning_controller_spec.rb
- spec/models/analytics/federation_reporter_spec.rb
We're seeing a few errors cropping up where no idp_was_recommended value
is available in the session. This can occur for a number of reasons, but
leads to an irrecoverable journey from the user perspective.
The point of failure is currently at the reporting stage, which should
not cause the entire request to fail, therefore the error is now being
rescued from and a message will be included in the reporting explaining
why and where it failed.
> BAU: Rescue from KeyError when no session data retrieved

- app/models/config_endpoints.rb
- spec/api_test_helper.rb
- spec/controller_helper.rb
- spec/feature_helper.rb
- spec/models/session_proxy_spec.rb
- stub/api/stub_api.rb
Reverts alphagov/verify-frontend#344
Temporarily to confirm this is the cause of staging failure
> Revert "TT-963: update tests to stub and use the transaction entity id"

- app/assets/javascripts/ab_test_selector.js
[JIRA TT-1065](https://govukverify.atlassian.net/browse/TT-1065)
Replacing const keyword with var to work in IE<11.
> TT-1065: bugfix for JS syntax

- app/assets/stylesheets/pages/_slides.scss
During sign-off it was decided the logo should have a fixed width to roughly match the font size and not use percentage sizing
> TT-942: set fixed width on Verify logo on mobile - sign-off refinement

- app/views/failed_uplift/index.html.erb
The link to 'Find another company to verify you' changed from /start to /about-choosing-a-company.
Authors: @jakubmiarka @hugh-emerson
> TT-981: changed a link on the failed uplift page

- app/assets/stylesheets/pages/_company.scss
- app/views/shared/_idp_list.erb
- app/views/shared/_unavailable_idp_list.erb
- spec/features/user_submits_start_page_form_spec.rb
- spec/features/user_visits_confirm_your_identity_page_spec.rb
Made logos clickable and used same styles on mobile devices for button. Also updated tests to click the correct button.
> TT-1078: Made sign-in IDP picker page consistent on mobile

- app/assets/javascripts/piwik_idp_picker_tracking.js
Bugs were idenitifed with scrolling event firing more than once. Also, due to Piwik bug event action names having "0" were considered as null. Changing that to null.
Authors: @jakubmiarka @michaelwalker
> TT-1119: Fixes for scrolling event and piwik action name

- app/controllers/application_controller.rb
- app/models/display/rp/transaction_taxon_correlator.rb
- app/views/errors/_transaction_list.html.erb
- config/initializers/30_federation.rb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_encounters_error_page_spec.rb
- spec/models/display/rp/transaction_taxon_correlator_spec.rb
- stub/locales/rps/loa1-test-rp.yml
- stub/locales/rps/test-rp-repudiation.yml
- stub/locales/rps/test-rp.yml
Previously the timeout page just showed a list of RPs. This list was
getting too long, so we have changed it so that it is grouped by taxon.
(ie group together all RPs related to Benefits etc)
To do this, a new correllator has been added which groups the transactions
by taxon, and a 'taxon_name' parameter has been added to the rp config.
The transaction list view has also been updated.
Authors: @michaelwalker @jakubmiarka
> TT-988: Implement grouping by taxon for timeout page.

- app/models/display/rp/transaction_taxon_correlator.rb
- config/initializers/30_federation.rb
- spec/models/display/rp/transaction_taxon_correlator_spec.rb
The previous implementation of TT-988 allowed all enabled transactions to
appear in the transaction list. However this allowed in some test data that
should not be present.
The list now filters out transactions which are not explicitly in the
allowed in the transaction types display list in federation config.
Authors: @michaelwalker @jakubmiarka
> TT-988: Limit the number of services that appear.

- .env.test
- app/controllers/authn_response_controller.rb
- app/models/api/client.rb
- app/models/api/response_handler.rb
- app/models/country_authn_response.rb
- app/models/saml_proxy_api.rb
- app/models/saml_proxy_endpoints.rb
- app/models/session_endpoints.rb
- app/models/session_proxy.rb
- config/initializers/20_api_proxies.rb
- spec/api_test_helper.rb
- spec/features/user_sends_authn_response_spec.rb
- spec/models/api/client_spec.rb
- spec/models/api/response_handler_spec.rb
- spec/models/session_proxy_spec.rb
- spec/support/authn_response_examples.rb
- stub/api/stub_api.rb
- stub/api/stub_api_spec.rb
Add saml_proxy_api for sending HTTP requests to saml proxy
Add saml_proxy_endpoints
api_client.handle_response no longer requires expected_status
Add the saml proxy endpoint to stub api
Authors: @hugh-emerson, @michaelwalker
> TT-1209: post country authn responses to SAML Proxy directly

- app/models/display/rp/transaction_taxon_correlator.rb
- config/initializers/30_federation.rb
Duplicate RPs were appearing in the front end due to accidently mutating
the list of name and homepage rps.
To fix this, we now use '+' instead of 'concat' to avoid mutating the
original object, and we clone the original list so that each correlator
has a unique version of the list.
Authors: @jakubmiarka, @hugh-emerson, @michaelwalker
> BAU: Fix duplicate RPs appearing in the frontend.

- app/controllers/other_identity_documents_controller.rb
- app/models/select_documents_form.rb
- spec/controllers/other_identity_documents_controller_spec.rb
- spec/models/select_documents_form_spec.rb
Select other documents page was overwriting the data for the first set of documents
Give non-uk id its own key in the evidence hash to avoid replacing other evidence.
No longer show the other documents page for users who select NI driving licence
Authors: @DataMinerUK, @hugh-emerson
> TT-1165: recommend RPs correctly for NI DL users

- app/controllers/choose_a_certified_company_controller.rb
- app/controllers/choose_a_certified_company_variant_create_account_controller.rb
- app/controllers/choose_a_certified_company_variant_get_setup_controller.rb
- app/controllers/redirect_to_idp_question_controller.rb
- app/views/redirect_to_idp_question/index.html.erb
- app/views/redirect_to_idp_question/redirect_to_idp_question_LOA1.html.erb
- app/views/redirect_to_idp_question/redirect_to_idp_question_LOA2.html.erb
- config/initializers/30_federation.rb
- spec/controllers/choose_a_certified_company_controller_spec.rb
- spec/controllers/redirect_to_idp_question_controller_spec.rb
- spec/features/user_visits_redirect_to_idp_question_page_spec.rb
- stub/api/stub_api.rb
- stub/idp-rules/stub-idp-loa1.yml
- stub/locales/idps/stub-idp-loa1.yml
In preparations for a new LOA1 IDP we want to show additional question before redirection. This is using the current interstitial logic but excluding the LOA1 if flag is not set.
Pair: @rachelthecodesmith @jakubmiarka
> TT-1259: Add interstitial page for LOA1 journey

- app/models/feedback_source_mapper.rb
- spec/models/feedback_source_mapper_spec.rb
Added binary return to feedback mapper to return as vaild if feedback source is from any about company page. Tests updated to cover new logic.
pair: @rachelthecodesmith @jakubmiarka
> TT-1284: fixed 404 error from about company page to feedback from

- app/controllers/sign_in_variant_create_account_controller.rb
- app/controllers/sign_in_variant_get_setup_controller.rb
AB test variant sign in controllers were trying to call a method that no longer exists
The frontend was changed to call policy directly for selecting the idp but the variants were not updated.
> BAU: fix ab test variants

- app/views/failed_registration/_continue_rp.html.erb
- app/views/failed_registration/_non_continue_rp.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Tweak the wording in the list of reasons for failure.
Make those lists on the two pages match.
Delete 'you can try the following' on the registration non-continue failure page
> TT-1410: update text on uplift and registration failure pages

- app/models/analytics/federation_reporter.rb
- spec/controllers/start_controller_spec.rb
- spec/features/user_submits_start_page_form_spec.rb
- spec/features/user_visits_sign_in_page_spec.rb
- spec/models/analytics/federation_reporter_spec.rb
Make the sign in and registration virtual page names meaningful.
Make the ab test virtual page name more generic (the custom variable is still set as before)
Removing the action name altogether would result in "Page Name not defined" page views
Add a test for the federation reporter report_ab_test method
Authors: @hugh-emerson, @jakubmiarka
> TT-1399: update the sign-in/registration virtual page names

- app/assets/stylesheets/pages/_slides.scss
Buttons on blue slides used default green shadow. Changed to dark blue (15% darker of the main blue colour) after a chat with Mike Thomas.
> TT-1489: Fixed green shadow on buttons

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/browserslist
- app/assets/stylesheets/pages/_slides.scss
Adding autoprefixer for CSS to automatically add vendor prefixes for CSS properties requiring prefix in browsers specified in browserlist.
> BAU: Add autoprefixer

- app/controllers/authn_response_controller.rb
- app/models/idp_authn_response.rb
- app/models/saml_proxy_api.rb
- app/models/saml_proxy_endpoints.rb
- app/models/session_endpoints.rb
- app/models/session_proxy.rb
- spec/api_test_helper.rb
- spec/features/user_sends_authn_response_spec.rb
- spec/models/saml_proxy_api_spec.rb
- spec/models/session_proxy_spec.rb
- spec/support/authn_response_examples.rb
- stub/api/stub_api.rb
- stub/api/stub_api_spec.rb
This allows IdpAuthnReponse's to be passed onto Saml Proxy by Verify Frontend directly without going through Frontend Api.
> Tt 1437 remove idp authn response api resource

- Gemfile.lock
- app/controllers/metadata_controller.rb
- spec/features/service_retrieves_metadata_spec.rb
XML endpoints shouldn't start returning HTML when they throw an error
> TT-1462: metadata endpoints no longer return html on errors

- app/controllers/choose_a_country_controller.rb
- app/models/policy_endpoints.rb
- app/models/policy_proxy.rb
- app/models/session_endpoints.rb
- app/models/session_proxy.rb
- spec/api_test_helper.rb
- spec/features/user_visits_choose_a_country_page_spec.rb
- spec/models/policy_proxy_spec.rb
- spec/models/session_proxy_spec.rb
- Frontend calls policy endpoint directly and gets list of countries instead of session proxy
- Updated tests and stubs to call policy and not the session
Authors: @mahmudh @jakubmiarka
> TT-1623: Get list of countries from policy directly

- Gemfile.lock
rubyzip 1.2.0 has a directory traversal vulnerability - CVE-2017-5946.
It doesn't look like this would be a problem in verify-frontend, since
we do not allow uploading zips.
As far as I can tell rubyzip is only a dependency as a transitive of
selenium.
Authors: @richardtowers
> bau: Update rubyzip to 1.2.1

- .rubocop.yml
- app/controllers/clever_questions/start_controller.rb
- app/views/clever_questions/start/start.html.erb
- config/clever_questions_ab_test_routes.rb
- config/locales/cy.yml
- config/locales/en.yml
- config/main_routes.rb
- config/routes.rb
- spec/controllers/clever_questions/start_controller_spec.rb
- spec/features/clever_questions/user_visits_start_page_spec.rb
- spec/features/user_sends_authn_request_spec.rb
- stub/ab_test.yml
Clever questions AB test is more of an AB test epic as it will drastically change the normal journey. To allow continuous integration the routes files have been split into two:
* main_route : normal routes 
* clever_questions_routes: new routes for the new change
Note: the clever questions AB test is toggled off until it is complete, it'll be switched on by releasing the fed config
Author: @NasAshrafThoughtworks
> TT-1606: Add new start page for clever questions AB test

- app/assets/javascripts/application.js.erb
- app/assets/javascripts/clever_questions/select_phone.js
- app/controllers/clever_questions/select_phone_controller.rb
- app/models/clever_questions/select_phone_form.rb
- app/models/idp_eligibility/evidence.rb
- app/views/clever_questions/select_phone/index.html.erb
- app/views/clever_questions/select_phone/no_mobile_phone.html.erb
- config/clever_questions_ab_test_routes.rb
- config/locales/cy.yml
- config/locales/en.yml
- spec/controllers/clever_questions/select_phone_controller_spec.rb
- spec/features/clever_questions/user_visits_select_phone_page_spec.rb
- spec/javascripts/clever_questions/select_phone_spec.js
Added a version of the select-phone page, to ask for mobile phone only, including a model and locales changes.
Author: @jakubmiarka
> TT-1606: Select phone page added for the clever questions AB test

- app/constraints/select_route.rb
- app/models/cookie_names.rb
- config/loa1_shortened_journey_ab_test_routes.rb
- config/routes.rb
- config/threshold_policy_ab_test_routes.rb
- spec/constraints/select_route_spec.rb
We'd like to test AB test variants in non-dev environments without enabling the test and issuing cookies to all visitors. This change will enable to set AB test to accept trial cookies and when the trial cookie is present and the value matches the experiment, it will enable user to see the variant without actually having the AB test cookie. This is immediately allowing the trial for the Clever Questions AB test.
Pair: @jakubmiarka @NasAshrafThoughtworks
> BAU: Implement trial function for AB testing

- app/assets/javascripts/clever_questions/select_documents.js
- app/assets/javascripts/select_documents.js
- app/models/clever_questions/select_documents_form.rb
- app/models/select_documents_form.rb
- app/views/clever_questions/select_documents/index.html.erb
- app/views/select_documents/index.html.erb
- spec/controllers/clever_questions/select_documents_controller_spec.rb
- spec/controllers/select_documents_controller_spec.rb
- spec/features/clever_questions/user_visits_select_documents_page_spec.rb
- spec/features/user_visits_select_documents_page_spec.rb
- spec/javascripts/clever_questions/select_documents_form_spec.js
- spec/javascripts/select_documents_form_spec.js
- spec/models/clever_questions/select_documents_form_spec.rb
- spec/models/select_documents_form_spec.rb
It's legally impossible to hold two driving licenses issued by two different EU countries. However, currently we allow users to select both.
This is to change the check boxes to radio buttons which consequently will also simplify our profiles.
Authors: @jakubmiarka
> TT-1737: Change checkboxes to radio buttons for driving licence question

- app/views/about/about.html.erb
- app/views/certified_company_unavailable/index.html.erb
- app/views/choose_a_certified_company/about.html.erb
- app/views/confirm_your_identity/index.html.erb
- app/views/errors/cookie_expired.html.erb
- app/views/errors/session_error.html.erb
- app/views/errors/session_timeout.html.erb
- app/views/failed_registration/_continue_rp.html.erb
- app/views/failed_registration/_non_continue_rp.html.erb
- app/views/failed_uplift/index.html.erb
- app/views/further_information/index.html.erb
- app/views/layouts/application.html.erb
- app/views/no_idps_available/no_idps_available.html.erb
- app/views/other_ways_to_access_service/index.html.erb
- app/views/redirect_to_idp_question/idp_wont_work_for_you.html.erb
- app/views/redirect_to_idp_question/redirect_to_idp_question_LOA1.html.erb
- app/views/redirect_to_idp_question/redirect_to_idp_question_LOA2.html.erb
- app/views/select_documents/unlikely_to_verify.html.erb
- app/views/shared/_feedback_link.html.erb
- app/views/shared/_other_ways.html.erb
- app/views/will_it_work_for_me/why_might_this_not_work_for_me.html.erb
- app/views/will_it_work_for_me/will_not_work_without_uk_address.html.erb
'raw' is a rails method wrapping 'html_safe' and is defined as
def raw(stringish)
stringish.to_s.html_safe
end
For use in views, it has 2 advantages over html_safe
1) Its nil safe.
html_safe is only defined on strings. Therefore nil.html_safe causes a
NoSuchMethod error to be thrown.
raw(nil) is fine however, as nil.to_s returns an empty string, which you
can then call html_safe on (again to return an empty string).
This means that using nil acts as a defensive measure against variables
in our template unexpectedly being nil.
2) Its a clearer name.
'html_safe' is potentially confusing, as it can sound like it is making
the string safe in some way (ie sanitising the input). In reality, its
marking the string as safe - ie telling rails that it doesn't need to
escape the string at all.
Raw …
> TT-1756: Use 'raw' in preference to 'html_safe'

- app/controllers/choose_a_certified_company_loa2_controller.rb
- spec/controllers/choose_a_certified_company_loa2_controller_spec.rb
The interstitial question is adding an 'interstitial' property to the evidence string/selected_answers, so when the user comes back after answering the interstitial question no IDPs will match as there are no segments for the 'interstitial evidence'.
> HUB-59: Production bug in the interstitial logic

- app/controllers/confirm_your_identity_controller.rb
- app/controllers/partials/idp_selection_partial_controller.rb
- app/controllers/partials/journey_hinting_partial_controller.rb
- app/controllers/redirect_to_idp_controller.rb
- app/controllers/sign_in_controller.rb
- app/models/analytics/federation_reporter.rb
- app/views/sign_in/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/controllers/redirect_to_idp_controller_spec.rb
- spec/controllers/sign_in_controller_spec.rb
- spec/features/user_visits_confirm_your_identity_page_spec.rb
- spec/features/user_visits_sign_in_page_spec.rb
If we have a journey hint cookie, modify the sign-in page to display that IDP prominently as per the design on the ticket.
Changes to piwik events:
* New event fired whenever we show a hint "Sign In Journey Hint Shown - ${idp_name}"
* Existing sign in event has " - Hint Followed" appended if the user followed a journey hint
* Existing sign in event has " - Hint Ignored" appended if the user ignored a journey hint
In the non-JS case we need a new session param to tell the idp redirect controller to send the correct event type - that controller can't check the hint cookie itself because the cookie has already been overwritten to the new IDP choice that was just clicked
> HUB-11 IDP journey hint

- config/locales/cy.yml
- config/main_routes.rb
- spec/features/user_visits_about_choosing_a_company_page_no_questions_variant_spec.rb
- spec/features/user_visits_about_choosing_a_company_page_spec.rb
- spec/features/user_visits_choose_a_certified_company_page_no_questions_variant_spec.rb
- spec/features/user_visits_choose_a_certified_company_page_spec.rb
Fix the routing so that users can't go off the rails and see the questions (e.g. by clicking a link or a bookmark, or url-hacking)
Fix a bug in the welsh yaml, which was spotted by the new tests (yay tests)
Adding feature tests for the two affected pages
> HUB-71 feature tests and routing fix

- app/controllers/choose_a_certified_company_loa1_controller.rb
- app/controllers/choose_a_certified_company_loa2_controller.rb
- spec/controllers/choose_a_certified_company_loa2_controller_spec.rb
We are adding 0 docs segments to an IDP with an interstitial question.
We want the question to show up for 0-docs users as well as for 1-doc
users.
Also removed a dead method from the loa1 version of the controller.
> HUB-79 show interstitial idp question when 0 docs

- stub/api/Gemfile
- stub/api/Gemfile.lock
This CVE doesn't affect us because:
a) We don't run Sinatra in production (it's only used to stub the API
locall)
b) We don't run things on Windows
But upgrading is probably a good idea anyway.
> CVE-2018-7212: Upgrade Sinatra

- config/locales/en.yml
This has been incorrect since May 2016:
d8187da8df84dd1cc238b54bf9107abffb4ae70c
Pair: @rhowe-gds @sgreensmith
> ZD48070: Fix typo on the error page 'others ways'

- app/controllers/start_controller.rb
- config/main_routes.rb
- spec/features/server_sends_analytics_spec.rb
- spec/features/user_sends_authn_request_spec.rb
- stub/ab_test.yml
To find out our margin of error we'll be running an AA test. The journey
is identical between the control and variant, the users will just be
tagged only.
Co-Authored-By: Rylan Gooch <rylan.gooch@digital.cabinet-office.gov.uk>
> HUB-120: AA test

- public/google7abe5aa505b89660.html
In order to hide the /start page from Google Search results, we need to remove it manually from the Google Search Console. This commit adds a file to enable the Search Console for the Verify domain (www.signin.service.gov.uk). The Search Console will be tied to the special account created in the GDS G-Suite domain to manage it (details in the Jira ticket).
> TT-1783: Visibility of Verify journey pages to search engines

- config/application.rb
It can cause errors but gives no benefit. From Rails release notes:
"The fact that Rails checks for IP spoofing can be a nuisance for sites that do heavy traffic with cell phones, because their proxies don't generally set things up right."
In our case, we think it’s some misconfiguration at the Welsh Assembly causing errors in the frontend.
> BAU: disable the Rails IP spoofing check

- config/main_routes.rb
We have applied the piwik reporting on the begin-registration virtual page,
but not all journeys hit that. Therefore moving the reporting to the about
page.
> HUB-109: Fix for incorrect reporting of AB test

- app/assets/javascripts/analytics.js
- app/controllers/application_controller.rb
- app/controllers/authn_request_controller.rb
- app/controllers/partials/analytics_partial_controller.rb
- app/controllers/start_controller.rb
- app/helpers/application_helper.rb
- app/views/shared/_piwik.html.erb
- pre-commit.sh
- spec/features/redirects_with_see_other_spec.rb
- spec/features/server_sends_analytics_spec.rb
- spec/features/users_browser_sends_client_side_analytics_spec.rb
- spec/spec_helper.rb
**READY TO BE MERGED AND DEPLOYED FOR TUESDAY (22/05/2018) TEST**
To improve our analytics data we're going create new visits for visitors
each time they come from an RP.
Also updated the pre-commit hook with check on focusing RSpec tests.
Co-Authored-By: Rachel Smith <rachel.smith@digital.cabinet-office.gov.uk>
> HUB-113: Force new Piwik visit on each SAML request

- app/controllers/hint_controller.rb
- config/main_routes.rb
Adds endpoint allowing us to test whether we can retrieve data from verify-frontend using a request from GOV.UK
Co-Authored-By: Jakub Miarka <jakub.miarka@digital.cabinet-office.gov.uk>
> Hub-135 Spike: recognise existing GOV.UK users on interstitial page

- app/controllers/partials/analytics_partial_controller.rb
- app/views/shared/_piwik.html.erb
For non-JS visitors we report only page title using the image tracker,
but missing out the key custom variables such as RP and LOA. We already
append the custom variables with any JS reporting.
This is to add it to the non-JS one too.
> HUB-150: Add custom variables to piwik img tracker

- app/controllers/authn_response_controller.rb
- app/controllers/partials/analytics_partial_controller.rb
- app/controllers/partials/idp_selection_partial_controller.rb
- app/controllers/redirect_to_idp_controller.rb
- app/controllers/start_controller.rb
- app/models/analytics/federation_reporter.rb
- spec/controllers/redirect_to_idp_controller_spec.rb
- spec/models/analytics/federation_reporter_spec.rb
- spec/support/authn_response_examples.rb
First release to test new string for analytics on one segment on successful registration journey. If this does not conflict with existing reporting and if it provides useful information we will roll this out for sign in and all registration journeys else the code will be removed.
> Hub 114 report attempts registration

- app/controllers/partials/idp_selection_partial_controller.rb
- app/controllers/redirect_to_idp_controller.rb
- spec/controllers/redirect_to_idp_controller_spec.rb
Add attempt reporting to ajax request and move logic for limitation by segment and increase attempt number to partial.
solo: @Rachelthecodesmith
> HUB-114: Add reporting to ajax request

- app/controllers/choose_a_certified_company_loa2_controller.rb
- app/controllers/choose_a_certified_company_loa2_variant_controller.rb
Should fix https://sentry-hub-prod-a-dmz.ida.digital.cabinet-office.gov.uk/sentry/front/group/194/
See the following for more information on the safe navigation operator: http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/
> Sentry/Front/194: Delete from selected answers safely

- config/main_routes.rb
- spec/features/user_sends_authn_request_spec.rb
- stub/ab_test.yml
Made the necessary changes to the frontend to update the current AB test.
Added new routes for the updated iteration of the AB test, as well as updating
to reflect the new cookie name.
> HUB-178: Update IDP order

- app/assets/stylesheets/pages/_choose-a-country.scss
- app/models/display/country_display_decorator.rb
- app/models/display/eidas_scheme_display_decorator.rb
- app/views/choose_a_country/choose_a_country.html.erb
- Sort countries and schemes correctly. Previously, the sort_by wasn't taking case into account
- Reformat the SCSS to be easier to understand
- Better handle missing images: make alt text for flags and logos empty so the browser would hide them instead of displaying a broken image graphic and the unnecessary alt text. This is also better for screen readers and accessibilty as the users don't need to hear, e.g. 'Austria flag. Austria'.
> EID-457: Improvements to the country picker

- app/controllers/partials/analytics_partial_controller.rb
- app/controllers/partials/idp_selection_partial_controller.rb
- app/controllers/redirect_to_idp_warning_controller.rb
- app/controllers/sign_in_controller.rb
- app/models/analytics/federation_reporter.rb
- spec/models/analytics/federation_reporter_spec.rb
Refactor to remove surplus hint_details session varable as user_followed_journey_hint stored the same value and used the same logic.
Co-Authored-by: Jakub Miarka <jakub.miarka@digital.cabinet-office.gov.uk>
> HUB-116: Refactor to reduce session variables

- app/controllers/authn_response_controller.rb
- spec/controllers/authn_response_controller_spec.rb
- spec/controllers/authn_response_spec.rb
- spec/support/tracking_cookie_examples.rb
rearrange the cookie tracking specs to allow for overwriteable variables so we can add the same for the country response endpoints
> Update verify-front-journey-hint tracking cookie for Country Responses too

- app/assets/javascripts/analytics.js
- app/controllers/authn_request_controller.rb
- spec/features/redirects_with_see_other_spec.rb
Performance analyst team analysed the data from the day we forced
the new piwik visit for each RP request and they are happy to enable it
as a default. We also identified a small issue when on start page we do
an additional JS reporting, the flag was still present, so added a fix
to remove it as soon as it gets used.
> HUB-113: Re-enable forcing a new piwik visit

- app/controllers/feedback_controller.rb
- app/views/feedback/disabled.html.erb
- config/initializers/00_configuration.rb
- config/initializers/30_federation.rb
- config/locales/cy.yml
- config/locales/en.yml
- spec/controllers/feedback_controller_spec.rb
- spec/features/user_visits_feedback_page_spec.rb
The reason behind this is that since the IP whitelist has been removed the integration environment
has been visible to the public, including the feedback form, which on integration lacks any
zendesk config and merely throws an error when submitted. We decided to modify the frontend so that
when in integration if the feedback form is accessed a gov.uk styled error is shown to the user
stating that feedback is disabled in this environment.
To make these changes I have added a new view to the feedback folder, and made some changes to the
respective controller, that now checks the value of a new environment variable named
FEEDBACK_DISABLED, if true it renders the new view with the error message, if false renders the
feedback form as normal.
I have also added some unit tests for the additional …
> HUB-190: Hide feedback form from integration.

- app/controllers/select_documents_variant_controller.rb
When a user is on variant, has a JS disabled and submits invalid form,
the select_documents_variant controller tries to re-render the page with
the error message. However, we don't use that view and so it isn't present.
The fix is to render the control views (instead of adding the variant view)
> ZD-56753: Fix for incorrect view rendering

- app/controllers/partials/journey_hinting_partial_controller.rb
- app/controllers/partials/user_cookies_partial_controller.rb
Logic that checked for a journey hint cookie would set an empty string
if no hint present. This has been removed to allow checks against nil to
return intended results.
Co-Authored-by: Jakub Miarka <jakub.miarka@digital.cabinet-office.gov.uk>
> BAU: Fix to logic in setting journey hint

- spec/models/display/rp_display_repository_spec.rb
- spec/services/rp_translation_service_spec.rb
The tests re-initialize the global RP_TRANSLATION_SERVICE and CONFIG_PROXY
instances resulting in warnings in the results.
> BAU: Remove warnings about already initialized constants

- config/main_routes.rb
We're baselining our data to validate our performance management and therefore switching off the test
for the duration of the baseline. Not tearing down as we want to re-iterate
it and potentially make it a control.
> HUB-203: Turn off the questions light AB test for a week

- app/controllers/authn_response_controller.rb
- spec/controllers/authn_response_controller_spec.rb
Previously there were a lot of lambdas being passed around and called so
tracing through the code was a bit difficult. Since these lambdas are
all called immediately after fetching anyways, they've been moved into
named methods. Hopefully this looks more readable and easier to trace
through a journey.
Bigger changes with this commit include:
* Removing OTHER status - This means changes to current behaviour of:
* when receiving unknown status, send FAILED to piwik
rather than OTHER. The special 'OTHER' case always maps to FAILED
scenarios anyways, except piwik. Changing this will make the code much
easier to generalise.
* CANCEL country journey sets tracking cookie to CANCEL rather
than FAILED. nothing really uses the tracking cookie for country yet.
Previous value of FAILED probably …
> EID-637: Refactor Authn Response Controller for readability

- app/controllers/authn_response_controller.rb
- app/controllers/failed_sign_in_controller.rb
- app/controllers/partials/user_session_partial_controller.rb
- app/controllers/redirect_to_country_controller.rb
- app/models/country.rb
- app/models/feedback_source_mapper.rb
- app/views/failed_sign_in/country.html.erb
- app/views/failed_sign_in/idp.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/main_routes.rb
- spec/controllers/authn_response_controller_spec.rb
- spec/features/user_visits_verify_services_picker_page_spec.rb
This adds an eIDAS-specific error page for users that come back from an EU proxy node with a failed status.
There are still a bunch of TODOs that are blocked, so we're going to merge this now and deal with them later.
- The grammar for the Welsh translations isn't quite correct because sometimes the country names change when prefixed with "in". Content design is working on an alternative.
- Still need a translation for the URL. Welsh language unit have been contacted.
> EID-637: Adding eIDAS specific error page

- app/models/feedback_service.rb
- spec/models/feedback_service_spec.rb
We're migrating the feedback form from Verify Zendesk to GOV.UK Zendesk.
To enable proper routing of all the tickets in GOV.UK instance we need to
prepend the subject with [GOV.UK Verify].
solo: @jakubmiarka
> ZD-64417: Migrate feedback to GOV.UK Zendesk

- app/controllers/response_processing_controller.rb
- app/views/failed_sign_in/country.html.erb
- app/views/response_processing/matching_error.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- Updated text content for matching error page
- failed sign in for country now also redirects to RP service error for
consistency
Co-authored-by: Felix Millne <felix.millne@digital.cabinet-office.gov.uk>
> EID-795: updated error pages

- config/routes.rb
There are regular Sentry alerts when bots (?) are trying to query our URLs
with an appended ".json" at the end. This is erroring out as a MissingTemplate error and
surfacing in Sentry. This change is to constraint the "view" routes by html format, so
any non-html requests are treated as 404 without trying to render start.json etc...
Error:
https://sentry-hub-prod-a-dmz.ida.digital.cabinet-office.gov.uk/sentry/front/group/212/
Suggestion:
https://makandracards.com/makandra/15831-how-to-not-die-with-actionview-missingtemplate-when-clients-request-weird-formats
solo: @jakubmiarka
> ZD-64635: Constraint routes against bots

- app/models/display/rp/service_list_data_correlator.rb
- spec/controllers/metadata_controller_spec.rb
Update ServiceListDataCorrelator to reflect attribute name change.
> HUB-236: Rename taxon to serviceCategory in list of services endpoint

- app/views/further_information/index.html.erb
- spec/features/user_visits_further_information_page_spec.rb
- In response to an issue raised by RPA, this PR removes the
capitalisation on the further information page.
- The capitalise method makes all other letter lowercase so this has
been changed to a custom method that only capitalises the first letter
leaves the rest as defined by the RP
(thanks @jakubmiarka)
Co-Authored-By: Jakub Miarka
<jakub.miarka@digital.cabinet-office.gov.uk>
> CVQ2-146 ZD-67992: frontend content changes

- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
- jenkins.sh
- spec/feature_helper.rb
- spec/features/user_submits_feedback_page_spec.rb
- spec/features/user_visits_other_identity_documents_page_spec.rb
- spec/features/user_visits_other_identity_documents_page_variant_spec.rb
- spec/features/user_visits_select_phone_page_spec.rb
- spec/features/users_browser_sends_client_side_analytics_spec.rb
- spec/mock_piwik_middleware.rb
Changes:
- Upgrade selenium and capybara
- Switch to using headless chrome via chromedriver
- Fixes to tests that were failing due to Chrome honoring our CSP rules
- Updated .travis.yml to use Chrome
> bau: upgrade selenium and capybara

- .travis.yml
- Gemfile
- Gemfile.lock
- spec/feature_helper.rb
There's been some issues with running chromium headless on Jenkins so
this changes the browser back to Firefox but with its new headless
functionality and geckodriver support.
> bau: switch to firefox headless

- app/views/static/privacy_notice.en.html.erb
Removed "d" from "used" in first paragraph. New copy should read "...prove
your identity when using digital government services like the service
you use to..."
> BAU: Tiny change to privacy notice

- app/services/rp_translation_service.rb
- spec/api_test_helper.rb
- spec/services/rp_translation_service_spec.rb
When fetching locales we should fetch both the english and welsh translations. 
This makes sure that we will always have the welsh and english translations available.
> CVQ2-177: update both locales on translation fetch

- app/models/display/display_data.rb
- app/models/display/rp/display_data_correlator.rb
- app/models/display/rp/service_list_data_correlator.rb
- app/models/display/rp/transaction_taxon_correlator.rb
- app/models/display/rp_display_data.rb
- config/initializers/30_federation.rb
- spec/models/display/display_data_spec.rb
- spec/models/display/rp/display_data_correlator_spec.rb
- spec/models/display/rp/service_list_data_correlator_spec.rb
- spec/models/display/rp/transaction_taxon_correlator_spec.rb
The Transactions listers`TransactionTaxonCorrelator`,
`ServiceListDataCorrelator`, and `DisplayDataCorrelator` were using
`I18n` directly to provide the content for the RP. This introduced a
problem where the lists were being generated but the correct localisation
was not being fetched, if missing, from the ConfigService.
This meant that the Welsh version of the list was mostly being rendered
in English despite the translations existing upstream.
Hooking the listers up to the `RP_DISPLAY_REPOSITORY` will guarantee
that the correct localisation is provided when generating these lists.
CVQ2-177: use RP Display Repository in DisplayDataCorrelator
> CVQ2-177: use rp display repo in service listers

- app/controllers/application_controller.rb
- app/controllers/service_status_controller.rb
- app/models/display/repository_factory.rb
- app/models/display/rp_display_data.rb
- app/models/display/rp_display_repository.rb
- app/services/rp_translation_service.rb
- lib/loading_cache.rb
- spec/lib/loading_cache_spec.rb
- spec/models/display/rp_display_repository_spec.rb
- spec/rails_helper.rb
- spec/services/rp_translation_service_spec.rb
- spec/spec_helper.rb
Implements a 'cache' inside the `RpDisplayRepository` that will refresh
the translations that support `RpDisplayData` every 30 minutes. The
refresh action on the cache allows for us to call off to config service
and fetch some new translations.
This removes the need for using the `before_action` in
`ApplicationController` to refresh a user's transaction's translations.
This also means that when we generate a transaction list each
transaction's display data will be refreshed if it has become stale.
One alternative to this approach might be to use the Rails.cache support
but I've decided to skip this for now as it looked a bit confusing with
the call into the translation service and it's not possible current to
cache the `display_data` object.
The caching behaviour has also been extract …
> Make rp display repo threadsafe

- config/environments/development.rb
In dev env the eager_load is set to false which causes the
app the hang when it looses the reference to the TransactionTranslationResponse class. This is a quick fix.
> BAU: Fix for translations being on a separate thread

- startup.sh
startup.sh relies on relative paths. Ensure that we know what the current
working directory is.
> BAU: Ensure we know what the working directory is in startup.sh

- app/models/display/rp_display_repository.rb
- lib/loading_cache.rb
- spec/lib/loading_cache_spec.rb
It's currently possible that two requests to the frotend could try to write into the repository's store at the same time when a value hasn't been set. This change introduces blocking calls to prevent two writes from happening the override  one another.
The `LoadingCache` was being passed an object at creation that could then be used to replace itself when a refesh event happenend. This was a little awkward so I've changed the interface to loading cache so that the way to refresh is passed to #fetch as a block. This is similar to how `Hash#fetch` works.
> Improvement to rp display repository

- app/controllers/authn_response_controller.rb
- app/controllers/confirm_your_identity_controller.rb
- app/controllers/hint_controller.rb
- app/controllers/partials/idp_selection_partial_controller.rb
- app/controllers/partials/journey_hinting_partial_controller.rb
- app/controllers/partials/user_cookies_partial_controller.rb
- app/controllers/redirect_to_idp_warning_controller.rb
- app/controllers/sign_in_controller.rb
- app/controllers/single_idp_journey_controller.rb
- app/controllers/test_journey_hint_cookie_controller.rb
- app/views/static/cookies.en.html.erb
- spec/controllers/authn_response_controller_spec.rb
- spec/controllers/hint_controller_spec.rb
- spec/support/tracking_cookie_examples.rb
Changed the cookie structure to log RP as well and only keep the latest state.
Added a temporary piece of code to clean existing cookies in users browsers.
Kept the ATTEMPT and SUCCESS states in to stay backwards compatible and
also make sure we know if there ever was a success.
> HUB-278: Update journey hint cookie to support P&R

- app/views/paused_registration/without_user_session.html.erb
- config/locales/cy.yml
- config/locales/en.yml
The paused page for users without a session has a bug and
renders the encoded HTML as it's missing '_html' in name.
> BAU: Fix wrong html encoding

- app/controllers/authn_response_controller.rb
- spec/features/localisation_set_from_different_sources_spec.rb
- spec/support/authn_response_examples.rb
We've recently changed how we store selected IDP and selected Country in session.
At the same time we changed how we set the journey hint cookie using what's in the session.
When rebasing I missed the line where we read the value and used the old
syntax accessing the object. Which was returning nil and thus no hint was set.
This is to use the helper method to read from the session. It has a side
effect when processing authn response it is now strictly required to have a selected
IDP in the session. I think that's fine as it's part of the session anyway.
I updated the tests to setting the selected IDP.
> BAU: Bugfix for journey hints not being set

- .env
- .env.test
- app/controllers/authn_request_controller.rb
- app/controllers/partials/journey_hinting_partial_controller.rb
- app/controllers/paused_registration_controller.rb
- app/controllers/test_journey_hint_cookie_controller.rb
- app/models/feedback_source_mapper.rb
- app/views/paused_registration/resume_with_idp.html.erb
- app/views/test_journey_hint_cookie/index.html.erb
- config/initializers/00_configuration.rb
- config/initializers/30_federation.rb
- config/locales/cy.yml
- config/locales/en.yml
- config/main_routes.rb
- spec/controllers/authn_request_controller_spec.rb
- spec/controllers/paused_registration_controller_spec.rb
- spec/features/user_visits_resume_registration_page_spec.rb
Add resume page (similar to single IDP handover page)
Modify authn_request_controller to check cookie for pending status and redirect if present
> HUB-174: Show hub resume page to paused users

- app/controllers/paused_registration_controller.rb
- app/views/paused_registration/resume_with_idp.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_visits_resume_registration_page_spec.rb
I believe the RP should refer to the service/transaction name instead of
the actual RP name. Also added a full stop at the sentence.
> BAU: Small fixes to the resume page

- app/controllers/authn_response_controller.rb
- app/controllers/partials/analytics_partial_controller.rb
- app/controllers/partials/idp_selection_partial_controller.rb
- app/controllers/paused_registration_controller.rb
- app/controllers/redirect_to_idp_controller.rb
- app/models/analytics/federation_reporter.rb
- app/views/paused_registration/resume.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/main_routes.rb
- config/routes.rb
- spec/controllers/authn_response_controller_spec.rb
- spec/controllers/paused_registration_controller_spec.rb
- spec/features/user_visits_resume_registration_page_spec.rb
- spec/support/authn_response_examples.rb
Updating the reporting to add the custom variable for the resume page.
Changed the authn response reporting to report RESUME_WITH_IDP instead of SIGN_IN_WITH_IDP.
Switched the Resume button to start using resume method and reporting instead of the sign-in logic.
> HUB-293: Update reporting for P&R journey

- app/controllers/authn_response_controller.rb
- app/views/failed_registration/_continue_rp.html.erb
- app/views/failed_registration/_custom_failed_registration.html.erb
- app/views/failed_registration/_non_continue_rp.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/controllers/authn_response_controller_spec.rb
- spec/support/authn_response_examples.rb
Update failed registration error page designs as per story.
Update AuthnResponseController to ensure single IDP journeys always go to regsitration failure regardless of journey type.
> HUB-267: Implement single-idp specific fail page

- app/controllers/authn_response_controller.rb
- spec/controllers/authn_response_controller_spec.rb
- spec/support/authn_response_examples.rb
Add method to delete single idp journey cookie after all saml responses.
AC's:
The single IDP cookie is deleted when the user is on a single-idp journey and we receive any SAML response (SUCCESS, FAIL, PENDING ... ) from an IDP
The single IDP cookie is deleted when the user chooses a different IDP and we receive any SAML response from that IDP (SUCCESS, FAIL, PENDING ... ) from an IDP
The SIDP cookie is retained when the user closes the browser during the IDP portion of the journey
The SIDP cookie is retained when the user clicks Continue on the handover page, then clicks back from the IDP journey
> HUB-294: Delete single idp cookie after any SAML response.

- spec/api_test_helper.rb
- spec/controllers/metadata_controller_spec.rb
- spec/features/user_encounters_error_page_spec.rb
- spec/features/user_selects_an_unavailable_idp_for_signin_spec.rb
- spec/features/user_visits_about_identity_accounts_page_spec.rb
- spec/features/user_visits_cancelled_registration_page_spec.rb
- spec/features/user_visits_choose_a_country_page_spec.rb
- spec/features/user_visits_confirm_your_identity_page_spec.rb
- spec/features/user_visits_confirmation_page_spec.rb
- spec/features/user_visits_failed_registration_page_spec.rb
- spec/features/user_visits_may_not_work_if_you_live_overseas_spec.rb
- spec/features/user_visits_prove_your_identity_page_spec.rb
- spec/features/user_visits_resume_registration_page_spec.rb
- spec/features/user_visits_start_page_spec.rb
- spec/features/user_visits_verify_will_not_work_for_you_page_spec.rb
- spec/features/user_visits_why_might_this_not_work_for_me_page_spec.rb
- spec/services/rp_translation_service_spec.rb
- stub/api/stub_api.rb
- stub/locales/rps/test-rp-non-eidas.yml
Renaming test-rp name "register for an identity" profile to "test GOV.UK Verify user journeys" to make the content more readable.
Related PRs:
✅ https://github.com/alphagov/verify-acceptance-tests/pull/37
✅ https://github.com/alphagov/ida-hub-acceptance-tests/pull/107
✅ https://github.com/alphagov/verify-hub-federation-config/pull/202
✅ https://github.com/alphagov/verify-local-startup/pull/53
✅ https://github.com/alphagov/verify-stub-idp/pull/53
✅ https://github.com/alphagov/verify-test-rp/pull/19
> FIREBREAK: Rename test-rp

- app/models/display/rp/transaction_taxon_correlator.rb
- app/views/paused_registration/from_resume_link.html.erb
- app/views/shared/_transaction_list_prefer_headless_start.html.erb
- spec/api_test_helper.rb
- spec/features/user_visits_an_idp_emailed_link_to_paused_page_spec.rb
- spec/models/display/rp/transaction_taxon_correlator_spec.rb
Add new partial to render RP list using headless links (if present).
Use new partial in resume link page.
> HUB-306: Add headless RP links to e-mail resume links (HUB-185)

- app/controllers/cancelled_registration_loa1_controller.rb
- app/controllers/cancelled_registration_loa2_controller.rb
- app/views/cancelled_registration_loa1/cancelled_registration_LOA1.html.erb
- app/views/cancelled_registration_loa2/cancelled_registration_LOA2.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_visits_cancelled_registration_page_spec.rb
We have recently updated the design of the fail page (HUB-257). Consequently, we have updated the cancel page to match this content. These commits will display the new content.
todo: Welsh translations for these content changes.
Co-authored-by: Callum Knights <callum.knights@digital.cabinet-office.gov.uk>
> HUB-298: Update cancel page to match new fail page

- config/locales/cy.yml
- config/locales/en.yml
> BAU: Fix typo in locales

- app/controllers/authn_response_controller.rb
- spec/controllers/authn_response_controller_spec.rb
Update AuthnResponseController to redirect user appropriately on Single IDP journeys.
> HUB-292: Show Single IDP users registration success page

- app/views/static/privacy_notice.cy.html.erb
- app/views/static/privacy_notice.en.html.erb
Updated the translations on the privacy notice along with fixing the page formatting.
Updated English privacy notice to to fix missing DOB for digital identity for another European country,
Also fixed some missing closing tags within the English privacy notice.
> EID-1001: Updated Welsh translations for eIDAS

- app/controllers/choose_a_country_controller.rb
- app/controllers/partials/user_session_partial_controller.rb
- app/controllers/prove_identity_controller.rb
- app/controllers/start_controller.rb
- app/models/policy_endpoints.rb
- app/models/policy_proxy.rb
- spec/api_test_helper.rb
- spec/controller_helper.rb
- spec/controllers/choose_a_country_controller_spec.rb
- spec/controllers/prove_identity_controller_spec.rb
- spec/controllers/start_controller_spec.rb
- spec/features/user_visits_failed_sign_in_page_spec.rb
- spec/features/user_visits_prove_your_identity_page_spec.rb
- spec/features/user_visits_response_processing_page_spec.rb
Currently, if a user selects a country or an IDP without completing verification and clicks the back button to the journey picker page and then attempts a different type of journey, they receive a "service unavailable" error page as Policy doesn't allow a transition between `IdpSelected` and `EidasCountrySelected` states. The solution to this is to allow the frontend to ask Policy to restart the journey back to `SessionStartedState` when a user goes back to the journey picker page (`/prove-identity`) and selects a different type of journey. We already allow this for some eIDAS states. This piece of work makes the interfaces more general so that we can apply the same to Verify journeys as well.
Summary of changes:
- rename `restart-eidas-journey` Policy endpoint to `restart-journey`
-  Add …
> EID-1004: Fix transition between Verify and eIDAS journeys

- config/initializers/00_configuration.rb
Currently we configure a bunch of things externally, but they are the same in
all environments. Make those things have a sane default.
> BAU: Add various configuration defaults

- app/views/cancelled_registration_loa1/cancelled_registration_LOA1.html.erb
- app/views/cancelled_registration_loa2/cancelled_registration_LOA2.html.erb
The footer feedback link contains the cancelled source but the new link didn't.
> HUB-298: Add feedback source to additional feedback link on cancel page

- app/controllers/partials/retrieve_federation_data_partial_controller.rb
- app/controllers/single_idp_journey_controller.rb
- spec/api_test_helper.rb
- stub/api/stub_api.rb
Changed single idp endpoint to match change in hub, as well as a small refactor to the
retrieve_federation_data_partial_controller.
Co-authored-by: Chris Clayson <chris.clayson@digital.cabinet-office.gov.uk>
> HUB-274: Add alternate start page for single IDP

- conf.d/zdd_latch
- packaging/postinst.sh
The location of the ZDD marker file is currently configured externally. Package
its configuration up with the rest of the app.
> BAU: Add ZDD_LATCH configuration

- .env
- .env.test
- config/initializers/00_configuration.rb
This is enabled everywhere except the performance testing environment and our
vagrant test boxes. Enable it everywhere by default.
> BAU: Enable the single IDP feature by default

- app/controllers/choose_a_certified_company_loa1_controller.rb
- app/controllers/choose_a_certified_company_loa2_controller.rb
- spec/controllers/choose_a_certified_company_loa1_controller_spec.rb
- spec/controllers/choose_a_certified_company_loa2_controller_spec.rb
We've had a few 500s come through on Sentry due to the `entity_id` param
not being present when posting to /choose_a_certified_company.
This adds a check to ensure that the parameter is present, and if not
returns a 400.
> EID-1076: Check `entity_id` param

- app/controllers/single_idp_journey_controller.rb
- spec/controllers/single_idp_journey_controller_spec.rb
This mostly adds logging for failure cases, which are going to be the most interesting. Also, the referrer URL is included in those log entries.
Some considerations:
- I tried to keep the flow of the endpoint code as smooth as possible w/o adding too many disruptive logging statements - I indeed tried to "confine" them to the controller private methods
- In the testcases, I used regexp for the error message (rather than strings) so that I could ignore the referrer URL (which would have been `nil` in the test cases) and make things easier
Something I am not particularly happy about is that I tried to add logging for successful journeys in `continue_to_your_idp` but there were some technical issues with logging an info message there. However, we can use the existing logging to infer whether …
> Add logging for successful and failed journeys

- spec/feature_helper.rb
Disabled auto upgrade on Firefox so a System Version of Firefox at 62 can be used.
> EID-1053: Work around for bug in Firefox 63 which stops Selenium tests running.

- app/assets/stylesheets/pages/_slides.scss
Alter _slides.css so that .list-companies text align is centred and .list-companies > li are 32% wide rather than 24%
> HUB-358: Fix the alignment of IDP logos on the slides

- app/views/redirect_to_idp_question/redirect_to_idp_question_LOA1.html.erb
- app/views/redirect_to_idp_question/redirect_to_idp_question_LOA2.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Currently the redirect-to-idp warning and redirect-to-idp-question pages
are using the same page title making it inaccurate in terms of reporting.
> HUB-386: Rename page title for additional question page

- app/controllers/partials/analytics_cookie_partial_controller.rb
- app/controllers/paused_registration_controller.rb
- app/controllers/redirect_to_idp_warning_controller.rb
- app/controllers/sign_in_controller.rb
- app/controllers/single_idp_journey_controller.rb
- app/models/policy_endpoints.rb
- app/models/policy_proxy.rb
- lib/cookie_names.rb
- spec/feature_helper.rb
- spec/features/idp_selections_reported_to_piwik_spec.rb
- spec/features/user_visits_continue_to_your_idp_page_spec.rb
- spec/features/user_visits_redirect_to_idp_warning_page_spec.rb
- spec/features/user_visits_resume_registration_page_spec.rb
- spec/features/user_visits_sign_in_page_spec.rb
- spec/models/policy_proxy_spec.rb
Update PolicyProxy to send new variables to Policy Service
> HUB-380: Add Piwik Session ID and Journey Type to Audit

- app/assets/stylesheets/pages/_choose-a-country.scss
- Previously the country scheme logos would wrap
onto a new line when the layout was narrow.
This was because they took up a fixed width.
- Mitigate this by not specifying a manual width
which works for all layouts.
With:
Without:
> EID-1005: Fix mobile layout of country picker

- app/assets/javascripts/application.js.erb
- app/assets/javascripts/modal_dialog.js
- app/assets/javascripts/vendor/dialog-polyfill.0.4.3.js
- app/assets/stylesheets/_application.scss
- app/assets/stylesheets/helpers/_modal-dialog.scss
- app/controllers/authn_response_controller.rb
- app/controllers/further_information_controller.rb
- app/models/feedback_source_mapper.rb
- app/models/idp_authn_response.rb
- app/views/further_information/_modal_dialog.html.erb
- app/views/further_information/index.html.erb
- app/views/further_information/timeout.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/main_routes.rb
- config/routes.rb
- spec/controllers/authn_response_controller_spec.rb
- spec/controllers/further_information_controller_spec.rb
- spec/features/user_visits_further_information_page_spec.rb
- spec/support/authn_response_examples.rb
With HUB-348 we exposed the NotOnOrAfter expiry date of the assertions sent by an IDP. This is to present this information to the user when they're close (<5mins) to the expiry time. And also prevent users to submits Cycle3 attributes with an expired assertion.
It's using amended `GOVUK.modalDialog` component to maintain accessibility of the modal box. The functionality has been changed to satisfy our requirements (triggered by a hard limit rather by inactivity).
It might be easier to review the PR commit by commit.
> HUB-363: Show user session timeout message based on NotOnOrAfter

- app/controllers/further_information_controller.rb
- app/controllers/partials/user_session_partial_controller.rb
- app/views/further_information/timeout.html.erb
For the timeout modal we now display the IDP name, this was getting broken on the EIDAS
journey as there was no IDP name. This handles both cases
> HUB-363: Make the cycle3 timeout page work with EIDAS

- app/controllers/authn_request_controller.rb
- app/controllers/start_controller.rb
- app/controllers/test_saml_controller.rb
- app/helpers/application_helper.rb
- app/views/start/start.html.erb
- config/routes.rb
- spec/feature_helper.rb
- spec/features/redirects_with_journey_hint_authn_request_spec.rb
- spec/features/user_sends_authn_request_spec.rb
Extend journey hint processing in AuthnRequestProcessing to read from Rails session if no query parameter passed.
Modify journey hint processing routes for uk_idp_sign_in and registration hints
Add journey hint to page title on start page
> HUB-377: Process Journey Hint Cookie

- config/application.rb
After recent gem updates, the fonts are loaded differently and were
being blocked by our strict CSP.
> BAU: Fix CSP policy for fonts

- app/controllers/initiate_journey_controller.rb
- spec/controllers/initiate_journey_controller_spec.rb
Change the joruney hint handler so that it still routes to RP, but discards hint, rather than throwing error.
> BAU: Fix Invalid Journey Hint Handling

- config/locales/cy.yml
Follow-up on EID-1060
[Translation spreadsheet](https://docs.google.com/spreadsheets/d/1PyGbtFbQT5_4dvqybvIwFq_BlBEvNQ7-tKG4ziwWExU/edit#gid=0)
_Note:_ Due to the Welsh morphology, the `in %{country_name}` had to be omitted since it's not easy to translate that programatically into Welsh.
> EID-1177: Add Welsh translation for eIDAS scheme unavailable page

- app/assets/stylesheets/_govuk-elements.scss
The issue is caused by the css element line 46 `govuk_frontend_toolkit-8.1.0/app/assets/stylesheets/_shims.scss` where it creates an `:after` element which has the content of `""`, if the content is set to `none` rather than `""` the focus selection box is the correct shape.
> EID-1170: Work around for oddly shaped focus selectors

- app/controllers/single_idp_journey_controller.rb
- app/helpers/application_helper.rb
- app/models/transaction_translation_response.rb
- app/views/single_idp_journey/rp_start_page.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/main_routes.rb
- spec/api_test_helper.rb
- spec/controllers/single_idp_journey_controller_spec.rb
- spec/features/user_visits_rp_single_idp_start_page_spec.rb
Add endpoint and route for Hub Hosted Customised Start Pages for Single IDP
Read new attribute from config service translations to display content.
Co-authored-by: Kerr Rainey <kerr.rainey@digital.cabinet-office.gov.uk>
> HUB-399: Create a SIDP customised start page for an RP in the hub

- app/models/display/rp/service_list_data_correlator.rb
- spec/models/display/rp/service_list_data_correlator_spec.rb
In order to help IDPs to map services internally we expose
simpleId to use as a reference for their own mapping.
[Tech spec update here.](https://github.com/alphagov/verify-architecture/pull/67)
> BAU: Add simpleId to the returned results for SIDP

- app/controllers/single_idp_journey_controller.rb
- config/locales/cy.yml
- config/locales/en.yml
- spec/controllers/single_idp_journey_controller_spec.rb
Adding some more information to the error message when session doesn't match
the cookie.
Also fixed the missing translation for the route.
> BAU: Add more reporting for SIDP

- .gitignore
local.env file is generated by generate-env.rb in verify-local-startup repo. This file is used for running application locally and it should not be in GitHub. Please note that .gitignore file will not ignore .env file.
Author: @adityapahuja
> BAU: Ignore local.env file

- app/models/feedback_service.rb
- spec/models/feedback_service_spec.rb
Change template so that Zendesk agents can inspect tickets using tooltip rather than opening ticket.
Co-authored-by: Alan Carter <alan.carter@digital.cabinet-office.gov.uk>
> ZD-3565728 Alter layout of feedback tickets

- app/controllers/initiate_journey_controller.rb
- spec/controllers/initiate_journey_controller_spec.rb
* if headless start page isn't known, we can redirect to the service's homepage instead
* fixes a crasher in live for timed-out sessions.
https://govuk.zendesk.com/agent/tickets/3572104
> Zendesk 3572104: fix init-journey when headless start unknown

- app/controllers/single_idp_journey_controller.rb
- spec/controllers/single_idp_journey_controller_spec.rb
(Plan to do another PR with the piwik change, but I can't get it to work yet :/ )
- these events are often (tho not always) a legitimate change of
journey for the user, so we shouldn't log them as errors.
- the information may still be useful in diagnosing cases where the
user did not intend to change from one transaction to another,
which is also a separate issue:
https://govuk.zendesk.com/agent/tickets/3559335
https://trello.com/c/Xymb17Ua/39-single-idp-journey-interruptions-should-not-log-an-error
https://govuk.zendesk.com/agent/tickets/3576498
> ZD-3576498 avoid logging an error for a Single IDP journey interruption.

- app/controllers/authn_response_controller.rb
For this Zendesk ticket: https://govuk.zendesk.com/agent/tickets/3571167
We've had a few users end up unexpectedly on the fail page after
logging in to an IDP. This will happen if the IDP sends back a few
different statuses, which we translate to `OTHER` in policy
and return to the frontend. We currently don't have any insight into 
when this happens. This should help.
> BAU Add logging for failed IDP response statuses

- app/controllers/single_idp_journey_controller.rb
- app/models/analytics/federation_reporter.rb
- spec/controllers/single_idp_journey_controller_spec.rb
- spec/models/analytics/federation_reporter_spec.rb
- spec/piwik_test_helper.rb
Add piwik event reporting to enable analysis of user journeys that start at one service and end at another.
Co-authored-by: Benjamin Gill <benjamin.gill@digital.cabinet-office.gov.uk>
> HUB-7 report single idp service mismatch

- kill-service.sh
Allow users to run kill-service.sh from any other directory. Copies the pattern in startup.sh
> BAU: kill service from any directory

- lib/api/hub_response_handler.rb
- spec/lib/api/hub_response_handler_spec.rb
Improve the generic error message when unexpected error is received from the Hub.
We had an incident recently where eIDAS was disabled in DR and the logs showed this message:
`Received 404 with error message: 'NONE', type: 'NONE' and id: 'NONE'`
This is not a great way to handle unexpected errors when sending a request to the Hub.
We already handle error responses from the Hub when they are known exceptions. These include anything to do with the logic and flow of a Verify journey. For any other issues, such as network errors or services being down, we throw an exception with a generic message. This message should reflect the fact that the problem is related to communication with the Hub rather than a problem with the user's journey.
> EID-1269: Handle unexpected error response from Hub better

- app/controllers/single_idp_journey_controller.rb
- spec/controllers/single_idp_journey_controller_spec.rb
This is to fix the Sentry alert triggered when an cookie expires and invalidates the session.
https://govuk.zendesk.com/agent/tickets/3588200
> ZD3588200: Turn down the logging on missing or expired cookies

- app/controllers/partials/single_idp_partial_controller.rb
- app/controllers/redirect_to_idp_controller.rb
- app/controllers/single_idp_journey_controller.rb
- spec/controllers/redirect_to_idp_controller_spec.rb
Move cookie checking code to single_idp_partial_controller as it is now used in two controllers.
Turn off caching for pages generated by single idp controller so that the proper page is shown if the user clicks back after cookie has expired.
Co-authored-by: Alexander Newton <alexander.newton@digital.cabinet-office.gov.uk>
> ZD3584380: handle expired single idp cookie on continue-to-your-idp page

- app/controllers/authn_response_controller.rb
- spec/controllers/authn_response_controller_spec.rb
and enable the non-matching journey for eIDAS flows. 
When testing with no-matching, the response falls through as it's not in accepted responses.
Cross-checking with https://github.com/alphagov/verify-hub/blob/8802e2dc66976bfc0d2930f16059ff4c8c2c4668/hub/policy/src/test/java/uk/gov/ida/hub/policy/services/AuthnResponseFromCountryServiceTest.java#L227
I believe the NON_MATCHING_JOURNEY_SUCCESS should be on the list.
> BAU: Add a non-matching response for country

- app/models/session_validator.rb
- app/models/session_validator/transaction_entity_id_presence.rb
- spec/features/user_visits_start_page_spec.rb
- spec/models/session_validator_spec.rb
Transaction entity ID is required for the single IDP journey, and should always be available. Add log to catch any false positives of this new validation. Prepare for replacing log with validation error if there are no false positives. Commented out code will be re-instated by follow-on PR.
Co-authored-by: Benjamin Gill <benjamin.gill@digital.cabinet-office.gov.uk>
> ZD3579186: Add error log for missing entity ID

- app/models/analytics/federation_reporter.rb
- spec/models/analytics/federation_reporter_spec.rb
The `idp_name_history` value in the user's session is sometimes
unset, possibly due to the single IDP journey. In this case, the
analytics reporter should just fall back to using the `idp_name` value.
> BAU: Deal with idp_name_history being nil

- app/views/choose_a_country/choose_a_country.html.erb
- config/locales/cy.yml
- config/locales/en.yml
We're doing some E2E tests and currently it's difficult to pick a country using CSS
as they're all buttons. This change is using the Rails built-in
button tag to append name and value to the button.
> BAU: Refactor eIDAS button

- app/assets/stylesheets/pages/_company.scss
- app/controllers/sign_in_controller.rb
- app/views/shared/_disconnected_suggested_idp_list.erb
- app/views/sign_in/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/api_test_helper.rb
- spec/features/user_visits_sign_in_page_spec.rb
Inform users who may be expecting to see their IDP that said IDP is gone.
See https://trello.com/c/dCnwuq3t/112-use-cookie-to-remind-sign-in-users-that-those-rm-cs-will-no-longer-work
Co-authored-by: Alex Newton <alex.newton@digital.cabinet-office.gov.uk>
> 0tLSIi4H: provide users with hint for disconnected IDP

- app/views/shared/_disconnected_idp_list.erb
- config/locales/cy.yml
- config/locales/en.yml
Royal Mail and Citizensafe come to the end of their continued assurance period on March 1st. Therefore, we need to have the copy in place to explain to users why they can no longer use those IDPs to log in any more.
I've not done any testing of this PR, and we need to get the Welsh translation before merging.
See https://trello.com/c/vi7RV11M
> Add copy for IDP disconnect

- app/controllers/sign_in_controller.rb
- app/models/display/rp_display_data.rb
- app/models/transaction_translation_response.rb
- app/views/shared/_disconnected_suggested_idp_list.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/api_test_helper.rb
- spec/features/user_visits_sign_in_page_spec.rb
See https://trello.com/c/dCnwuq3t/112-use-cookie-to-remind-sign-in-users-that-those-rm-cs-will-no-longer-work
Co-authored-by: Alex Newton <alex.newton@digital.cabinet-office.gov.uk>
> dCnwuq3t: Add special text for UC users on IDP disconnection

- app/controllers/partials/single_idp_partial_controller.rb
- app/models/analytics/federation_reporter.rb
- spec/controllers/single_idp_journey_controller_spec.rb
- spec/piwik_test_helper.rb
Help us understand why (and how often) these errors are happening.
> ZD3590202: Add matomo event for missing/malformed cookie

- app/controllers/partials/idp_selection_partial_controller.rb
- app/controllers/partials/single_idp_partial_controller.rb
- app/controllers/redirect_to_idp_controller.rb
- app/controllers/single_idp_journey_controller.rb
- spec/controllers/single_idp_journey_controller_spec.rb
Cope with users who mysteriously lose their single IDP cookie between landing on the 'continue to your IDP' page and clicking on the button.
>  ZD3590202: handle loss of IDP cookie 

- .rubocop.yml
Disable and adjust a few rules to align with our conventions:
- `private` access modifiers align with `class` keyword (not methods)
- Increase max line length to 160 characters
- Don't require documentation comment for every class and module
- Don't require comments to start with a space
> BAU: Adjust Rubocop rules

- Gemfile.lock
The docker image for ruby 2.4.2 uses bundle 1.6 which is different from our lockfile
The bump from 1.6 to 1.7 is minor and does cause conflict, but 2.0.0 causes conflicts
Reverting for now
> BAU - reverting an accidental bump of Bundler form 1.7.1 to 2.0.0

- app/controllers/authn_response_controller.rb
- spec/controllers/authn_response_controller_spec.rb
Give more information on the IDP response received if the relay state is missing. Also update test to actually test an invalid relay state.
See https://trello.com/c/tocxYVRS/150-understand-and-fix-relay-state-was-nil-error
> tocxYVRS: check for empty IDP response

- app/controllers/authn_request_controller.rb
- lib/api/hub_response_handler.rb
- spec/lib/api/hub_response_handler_spec.rb
When the Hub receives an invalid SAML request from a Relying Party, the `saml-proxy` service will send a 400 response to Verify `frontend`. The `frontend` logs should contain more information to help Verify diagnose the reason for the invalid payloads from the Relying Party.
This PR provides more data in `frontend` logging:
* the HTTP Referer (in all cases, to identify RP)
* the RelayState from Relying Party, when `saml-proxy` errors with an `INVALID_SAML` message
* the base64 encoded AuthRequest, when `saml-proxy` errors with an `INVALID_SAML` message
These attributes are attached to the request-scoped `RequestStore` module.
> EID-1389: Log AuthnRequest information in hub response handler when error from saml-proxy

- app/models/cycle_three/cycle_three_attribute.rb
- app/models/display/cycle_three_display_data.rb
- app/views/further_information/index.html.erb
- spec/features/user_visits_further_information_page_spec.rb
- spec/models/cycle_three/cycle_three_attribute_spec.rb
- spec/models/display/cycle_three_display_data_spec.rb
- stub/locales/cycle3/DrivingLicenceNumber.yml
* Land Registry (HMLR) want to customise their 'sign your mortgage deed' service matching page.
https://trello.com/c/GETxCo0p/142-sign-your-mortgage-deed-revision-to-page-content
https://govuk.zendesk.com/agent/tickets/3622311
> Allow cycle three page customisation with `intro_html`

- Gemfile
- Gemfile.lock
See http://sass.logdown.com/posts/7081811
> BAU - replacing sass-ruby dependency with sassc as the former is deprecated

- app/controllers/authn_request_controller.rb
- app/controllers/partials/user_errors_partial_controller.rb
- spec/controllers/authn_request_controller_spec.rb
Currently, when the authn request comes in we pass it on to saml-proxy to validate.
However, if the request doesn't have a SAML, the saml-proxy service raises an exception.
This commit adds the validation to frontend so we fail earlier
and don't pass the request on to saml-proxy.
> ZD-3643231: Do not accept requests without a SAML message

- Dockerfile.heroku
- README.md
- app.json
- app/controllers/test_saml_controller.rb
- app/views/test_saml/idp_request.html.erb
- config/initializers/00_configuration.rb
- config/initializers/30_federation.rb
- config/routes.rb
- heroku-startup.sh
- heroku.yml
- stub/api/stub_api.rb
With the removal of the joint environment, we no longer have an environment where people (e.g. content designers) could go and review/try content changes.
This PR adds some Heroku config in order to allow us to automatically deploy PRs to a temporary environment. It makes use of [Heroku review apps](https://devcenter.heroku.com/articles/github-integration-review-apps). It also introduces a new config variable called `STUB_MODE` to enable the test/stub flows and routes while running in a production mode (in Heroku).
Next steps:
> FIREBREAK: Deploy PRs as temporary apps

- app/assets/javascripts/modal_dialog.js
- app/controllers/further_information_controller.rb
- app/views/further_information/_modal_dialog.html.erb
Currently, Verify Frontend uses JavaScript to compare session's expiry time in UTC taken from the server against the user's browser system clock. The issue with this approach is that when the user's browser system clock is set to a wrong time unintentionally (e.g. adding 2 hours forward from the true time), the user will always be redirected to timeout page since the user's browser clock is always after the session's expiry time taken from the server. Verify Frontend should do session expiry validation on the server side instead of the client side.
This commit changes Verify Frontend to calculate the number of seconds it takes for the session to timeout or expire and provide it instead of the session's expiry time to the JavaScript. The JavaScript then uses it to add the timeout to the …
> BAU: Stop relying on a user's browser system clock

- app/controllers/further_information_controller.rb
Verify frontend is comparing notOnOrAfter field (assertion_expiry) against the current system clock. The clock can be in different timezone e.g. British Summer Time (GMT+0100). According to SAML specification, notOnOrAfter specifies the time instant at which the assertion has expired. The time value is encoded in UTC. This commit updates verify frontend to compare notOnOrAfter field against the system clock in UTC. This will prevent users from getting session timeout errors.
Author: @adityapahuja
> BAU: Fix timezone issue

- Gemfile
- Gemfile.lock
prometheus/client_ruby#95 has been merged (although not yet released
to rubygems) so we can use the official client git repo instead of the
gocardless fork.
This bumps us from 5dce3e5 (the latest commit on the gocardless
branch) to 460c2bb (the commit that merged the gocardless branch into
master) so it's a pretty minimal change.
> use official prometheus client repo again

- pre-commit.sh
In response to an incident, we're adding a check to our pre-commit scripts
to ensure no AWS credentials are being committed. It's using the AWS-provided
git secrets script - https://github.com/awslabs/git-secrets
> BAU: Check for AWS credentials being committed

- pre-commit.sh
We're currently using the pre-commit script in concourse when running the tests.
By forcing the git-secrets to be installed it can't run. Make it run for now.
> BAU: Don't force git secrets in pre-commit

- Gemfile
- Gemfile.lock
The enormous rewrite from prometheus/client_ruby#95 has been merged,
and a prerelease version of it is now available on rubygems (as of
prometheus/client_ruby#124).  We should use the rubygems version
rather than the git version; when 0.10.0 is properly released we
should use that.
> Use prometheus client from rubygems

- app/controllers/single_idp_journey_controller.rb
- spec/controllers/single_idp_journey_controller_spec.rb
We handle missing params by redirecting users to another page so we don't need to see these logs in Sentry
> EID-1463: Log missing single IDP params as warn rather than error

- app/controllers/single_idp_journey_controller.rb
For some reason, transaction entity ID is sometimes missing from the session. Check the session is valid and show error page if not.
> BAU: Fix Single IDP journey missing transaction entity ID errors

- public/robots.txt
We have `noindex` HTML tags on some pages to prevent them from being indexed. Robots need to be able to access those pages to see the tag.
Google thinks some of our pages are being blocked by `robots.txt` whilst we're actually allowing all robots on all pages.
Maybe an explicit Allow directive will fix this.
_Tested with Google's robots.txt tester tool_
> BAU: Explicitly allow robots to index all pages

- app/helpers/application_helper.rb
- app/views/feedback/disabled.html.erb
- app/views/feedback/index.html.erb
- app/views/feedback_landing/index.html.erb
Setting the meta tag is not enough on error pages as Googlebot doesn't read it.
This uses the existing flag to append the the response headers.
I also considered using the nginx rules, but it would be a bit more complex with the
conditions as we actually control which pages to index from frontend.
Also removed some of the flags on pages which I don't believe should be indexed. Like the feedback form?
> BAU: Ban robots from indexing

- app/controllers/partials/user_errors_partial_controller.rb
Add logging to test whether we have enough information to perform partial reecovery when users are shown the 'something has gone wrong' page. If this shows a good number of users could be helped, we'll redirect to a more helpful error page. Otherwise, this experiment should be reverted.
See https://trello.com/c/kl73OxUJ/241-improve-the-something-went-wrong-experience for more information.
> BAU: find out whether errors are recoverable

- app/controllers/partials/user_errors_partial_controller.rb
I think I've discovered how to get the service homepage. It looks as if it ought to be present in the session. This would avoid the need for translations (i.e. `current_transaction`), which seems to be the current primary source of failures.
If this works, I should be able to submit a PR tomorrow to make the requisite change to the user experience. This would entail providing a link to "start again" that pointed at the service homepage.
> BAU: test whether the service homepage is available

- app/controllers/partials/user_errors_partial_controller.rb
Currently, we just log the raw exception. This makes it hard to work out what is causing the error pages to be shown. By introducing a log that includes both the name of the partial and the error message, we should then be able to do a search in the logs that will show us what is causing the errors.
This was prompted by https://github.com/alphagov/verify-frontend/pull/723#issuecomment-507752314
> BAU: log error causes

- app/controllers/partials/user_errors_partial_controller.rb
- app/views/errors/session_timeout.html.erb
- spec/features/user_gets_soft_session_timeout_page_spec.rb
We're inconsistent on when we send users back to the RP. There's a flag which
controls that (CONTINUE_ON_FAILED_REGISTRATION). However, it's not used on the timeout page and the user
gets sent to the RP with error regardless.
This is to make sure users gets sent on non-success scenarios to RPs only if the flag
is enabled.
> XFY6yswN: Change the Start again link on timeout page

- app/controllers/single_idp_journey_controller.rb
We're rendering error page AND redirecting later on, causing
DoubleRenderErrors.
> BAU: Fix DoubleRenderError

- app/controllers/single_idp_journey_controller.rb
We've been seeing exception in the logs where the users get `TypeError: no implicit conversion of nil into String`.
This is caused by invalid session in combination with missing authenticity token (CSRF).
The current protect_from_forgery on the controller is not raising exception and therefore
keeps processing the request and failing further down. We have turned the logic around
(swapped `except` for `only`) so that the controller inherits the forgery protection
from the ApplicationController instead and we only overwrite the single method with skip.
Co-Authored-By: Phil Miller <phillip.miller@digital.cabinet-office.gov.uk>
https://sentry.tools.signin.service.gov.uk/verify/prod-frontend/issues/1147
> BAU: Fix checking for CSRF token

- app/controllers/single_idp_journey_controller.rb
We believe we have resolved the issue with users hitting the SIDP methods without sessions.
Therefore we can now remove the extra validation we've added.
> BAU: Clean up the single IDP validations

- spec/controllers/single_idp_journey_controller_spec.rb
The new rails adds some new logs that interfere with the tests that expect certain logs. The fix is just to allow and ignore all logs that are not the ones we're explictly expecting.
Note: this is only some of the fixes required for Rails 5.1
> BAU: make single IDP tests compatible with Rails 5.1

- app/controllers/redirect_to_country_controller.rb
- app/controllers/redirect_to_idp_warning_controller.rb
The error: ActionView::MissingTemplate: Missing template redirect_to_country/choose_a_country_submit_ajax
Changed render status to head, as head only returns the header whereas render status tries to return a template if body is not recognised
> BAU: Fix unrecognised body trying to return a template

- app/views/static/privacy_notice.en.html.erb
- spec/features/user_visits_privacy_notice_page_spec.rb
I've added some new information about sharing data for fraud and threat intelligence reasons to the 'Cookies and analytics' section.
I've also rewritten the rest of the GOV.UK Verify privacy notice to make sure it meets GDS style.
> Updated 'Cookies and analytics' section

- config/locales/cy.yml
- config/locales/en.yml
New heading "You won’t be able to use GOV.UK Verify" for when user cannot use Verify replaces "GOV.UK Verify will not work for you".
- Welsh translations pending (from Land Registry perhaps?)
- unclear if we should change the title of the page too
https://govuk.zendesk.com/agent/tickets/3622311
https://trello.com/c/GETxCo0p/142-sign-your-mortgage-deed-revision-to-page-content
> New heading for when user cannot use Verify.

- lib/api/hub_response_handler.rb
- spec/lib/api/hub_response_handler_spec.rb
In the case of 502 and 504 error responses with an html error messsage, do not raise an error.
The error status will still be propagated, but with no error message.
Due to an issue with nginx and policy, the `HubResponseHandler` in frontend is receiving many **html** error responses, when expecting json error responses.
i.e.
````
HTTP/2.0 504 Gateway Timeout Error
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
````
These errors are surfacing as frontend sentry alerts, when we are already getting backend alerts for the same issue.
> Do not raise error on 502/504 html error responses

- app/controllers/choose_a_country_controller.rb
In an ideal world we can use the referrer supplied with the request to give the user a route back to the sign-in picker they came from if their country isn't yet available as part of eidas.
Unfortunately, test-rp doesn't exactly mirror the way that the hub interacts with gov.uk so this adds some logging to enable us to see what the referrer looks like in real life.
Once the data's in, we can decide how to proceed.
> EID-1774 Implement eIDAS escape route (exploration)

- lib/api/hub_response_handler.rb
- spec/lib/api/hub_response_handler_spec.rb
Reverts alphagov/verify-frontend#750
Catching these 502 and 504 errors here just meant they were propagated further and still surfaced in frontend logs, continuing to cause sentry events, 😱. 
The actual fix was via https://github.com/alphagov/verify-hub/pull/404, which stopped the 502s and 504s.
> Revert "Do not raise error on 502/504 html error responses"

- app/controllers/application_controller.rb
- app/controllers/partials/user_errors_partial_controller.rb
- spec/controllers/response_processing_controller_spec.rb
We've seen a couple of instances where the frontend received a request with
accept headers "image/*" on various endpoints. These endpoints obviously are
not able to return such a response (i.e. image). Instead of failing with uncaught exception
we now catch the exception and render plain error.
https://govuk.zendesk.com/agent/tickets/3850666
> OnYku8Ji: Handle unexpected headers gracefully

- app/controllers/hint_controller.rb
- config/routes.rb
- spec/controllers/hint_controller_spec.rb
We want to run a test where users are shown a direct link to log in with
the supplier they were last successful with. This is derived from their
cookie. Some JS is being written that will call this endpoint to find
out which IDP that was, and return some information which will be
useful.
> HUH-74 Add last_successful_idp endpoint to HintController

- app/controllers/hint_controller.rb
- spec/controllers/hint_controller_spec.rb
We're showing a hint on GOV.UK if the user has *successfully* verified, but we're currently
reporting if they even *attempted* to verified. This changes the logic to
return true if they successfully verify
so we can use the same tracking.
> HUH-74: Change the hint check from attempted to success

- .gitignore
- app/controllers/authn_request_controller.rb
- app/controllers/partials/viewable_idp_partial_controller.rb
- app/controllers/redirect_to_idp_controller.rb
- config/locales/cy.yml
- config/locales/en.yml
- config/main_routes.rb
- spec/controllers/authn_request_controller_spec.rb
- spec/controllers/redirect_to_idp_controller_spec.rb
- spec/features/redirects_with_journey_hint_authn_request_spec.rb
We're testing a new flow where a journey hint is set on the interstitial
page if it is determined the user has previously signed in successfully.
The hint is the simple_id of the IDP, prefixed with idp_.
These changes allow that hint to be picked up, and the idp selected,
before redirecting the user to the idp.
> HUH-74: Interstitial page sign-in hint: Set session and redirect to IDP

- app/controllers/initiate_journey_controller.rb
- spec/controllers/initiate_journey_controller_spec.rb
We're whitelisting the hint values. We're sending a new one which consists
of idp_ prefix and the name of the IDP. This will allow
to keep the hints when it begins with idp_
> HUH-74: Enable journey hints from gov.uk

- app/controllers/hint_controller.rb
- spec/api_test_helper.rb
- spec/controllers/hint_controller_spec.rb
On the hint endpoint, we need to call the config to obtain
the available IDPs. However, these calls require a transaction entity ID.
For the test we're hardcoding the transaction ID, otherwise we
would have to make another release in the JavaScript code deployed to GOV.UK
> HUB-74: Fix the hinting logic

- app/controllers/hint_controller.rb
- spec/controllers/hint_controller_spec.rb
We've [seen a few errors in Sentry](https://sentry.tools.signin.service.gov.uk/verify/prod-frontend/issues/3791/events/277199/) where the last successful IDP wasn't found in
the list of available IDPs. This will prevent an error being thrown and
log so we can investigate, whilst being invisible to the user.
> HUH-74 Fix bug if last successful IDP not available

- spec/features/user_visits_choose_a_certified_company_variant_c_page_spec.rb
Use user_visits_choose_a_certified_company_page_spec.rb as basis for variant c tests.
Mostly adapting selected_answers to new style hash hash.
Removed tests relating to protected segments as they're not relevant to this variant.
Co-authored by: Lewis Westbury <lewis.westbury@digital.cabinet-office.gov.uk>
> HUH-234 Missing tests for C-Variant

- app/controllers/hint_controller.rb
- app/models/analytics/federation_reporter.rb
- spec/controllers/hint_controller_spec.rb
- spec/piwik_test_helper.rb
This adds Matomo tracking for ajax calls made from GOV.UK.
It will allow us to see the responses whether users have the cookie or not.
> BAU: Track requests for hint

- app/assets/javascripts/analytics.js
- app/assets/javascripts/piwik_event_tracking.js
- app/controllers/application_controller.rb
- spec/features/user_sends_authn_request_spec.rb
- spec/javascripts/piwik_event_tracking_spec.js
Temporary measures to suspend Matomo cookie activity whilst a consent mechanism is put into place.
Push value on to piwikAnalyticsQueue to disable cookies.
Remove code that deposits cookies.  Amend tests so that they aren't broken.
> HUH-253 Disable Piwik (Matomo) cookies [DO NOT MERGE]

- app/models/feedback_source_mapper.rb
If user tries to provide a feedback from the paused registration page
they are presented with 404 Page not found.
This is due to a missing feedback source.
This can be reproduced by trying to visit https://www.signin.service.gov.uk/feedback?feedback-source=PAUSED_REGISTRATION_PAGE (with a valid session)
> BUG: Missing feedback source for paused-registration page

- app/controllers/publish_hub_config_controller.rb
- config/routes.rb
This path is used in integration for self-service to
get into the config service. The config service has two endpoints `/service-status` and
`/config/certificates/...`. This aligns the behaviour with the real config service.
Co-Authored-By: Olakunle Jegede <olakunle.jegede@digital.cabinet-office.gov.uk>
> BAU: Fix the path for self-service talking to integration

- app/controllers/response_processing_controller.rb
We're seeing intermittent timeouts for the `response-processing`
endpoint in the perf tests which inform the ZDD job in the pipeline.
It's quite hard to determine what's causing it as we get no logging back
from the frontend unless the request completes.
> BAU: Temporary logging to diagnose timeouts

- app/controllers/response_processing_controller.rb
This reverts commit 7aa099e46f5bea3ab0d7b297ca6838841db4a197.
Removes some temporary logging that was added in an attempt to diagnose an issue with the perf tests.
> Revert "BAU: Temporary logging to diagnose timeouts"

- app/controllers/choose_a_country_controller.rb
The referrer wasn't URL we were looking for so this logging can now be removed as it has served its purpose.
> Revert "EID-1774 Implement eIDAS escape route (exploration)"

- app/controllers/other_ways_to_access_service_controller.rb
- app/models/feedback_source_mapper.rb
- app/views/choose_a_country/choose_a_country.html.erb
- app/views/other_ways_to_access_service/after_eidas.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/main_routes.rb
- spec/features/user_visits_choose_a_country_page_spec.rb
continuing from @instantiator 's work... 
Users may choose to leave the eIDAS choose-a-country view because their country is not listed.
We have designed a new other ways page for them which provides slightly more relevant information, as some users may still be able to use Verify.
- Adds a new after_eidas action for the OtherWaysToAccessServiceController
- Adds a new route: other_ways_after_eidas
- Allows the user to enter a Verify journey directly from other_ways_after_eidas
- Adds local resource to define the new route, and new text for other_ways_after_eidas
- Pending Welsh wording for the new resources - so currently provides English wording in both en.yml and cy.yml
> EID-1774: Implement new escape route for eIDAS users whose country isn't listed

- app/views/layouts/application.html.erb
- app/views/select_documents/index.html.erb
- config/environments/production.rb
The first bug fix is for the acceptance tests.  Seems there was a typo
in the original PR which wasn't picked up.
The second bug fix is to disable the asset digests to try to fix the
missing assets in the pages.
Finally the is a minor change to the application.html.eb replacing the
html meta tag for view point with a rails tag as suggest by Jakub in
the original PR.
> BUGFIX this PR contains two bug fixes and a change

- .env
- app/controllers/choose_a_certified_company_loa2_controller.rb
- app/controllers/choose_a_certified_company_loa2_variant_c_controller.rb
- app/controllers/select_documents_variant_c_controller.rb
- app/models/identity_provider.rb
- app/models/idp_recommendations/recommendations_engine.rb
- config/initializers/00_configuration.rb
- config/initializers/30_federation.rb
- spec/models/identity_provider_spec.rb
- spec/models/idp_recommendations/recommendations_engine_spec.rb
This is to avoid a timing issue where the button to select an IDP gets rendered shortly before the cut-off time and the user fails to press is before that cut-off time. In that case the user will see an error for a reason completely outside of their control.
Hiding IDPs disconnecting for registration a short period of time before the cut-off time is a crude solution to this as the Hub will still accept requests for those IDPs until the actual cut-off time. This doesn't eliminate the problem completely but given an appropriate time interval it reduces it greatly as most people are not likely to spend more than a few minutes on the picker.
Added a new config value to the `env` file and added logic to the recommendations engine to hide IDPs which have the `provide_registration_until` flag …
> HUB-545: Hide IDPs disconnecting for registration an amount of time before the actual cut-off time

- app/views/about/certified_companies_LOA1.html.erb
- app/views/about/certified_companies_LOA2.html.erb
- app/views/choose_a_certified_company/choose_a_certified_company_LOA1.html.erb
- app/views/choose_a_certified_company/choose_a_certified_company_LOA2.html.erb
- config/locales/cy.yml
- config/locales/en.yml
DO NOT MERGE UNTIL MONDAY 23 MARCH.
Changing content so that the hub is accurate and works for only 2 IDPs. Changes include removing incorrect information about how the companies do their checks, and removing content that was only there because of certain IDPs.
> HUB-521: Update hub content for 2 IDP hub

- app/assets/stylesheets/pages/_slides.scss
- app/views/start/start.html.erb
- config/initializers/00_configuration.rb
- config/locales/cy.yml
- config/locales/en.yml
Only the English version is affected - Welsh remains the same
> BAU: Add a clarification to the Start page for the "sign-up" option

- app/controllers/single_idp_journey_controller.rb
- spec/controllers/single_idp_journey_controller_spec.rb
Currently, if the Single IDP request is invalid, the user gets presented with
the available services and need to pick one.
However, we can streamline this and send them directly to the service's start page.
Saves them a click and another decision.
> BAU: Redirect users to the service start page even when the IDP is disabled

- .env
- app/controllers/choose_a_certified_company_loa2_controller.rb
- app/controllers/test_throttling_cookie_controller.rb
- app/views/static/cookies.cy.html.erb
- app/views/static/cookies.en.html.erb
- config/initializers/00_configuration.rb
- config/initializers/30_federation.rb
- config/initializers/throttling.rb
- config/routes.rb
- lib/cookie_names.rb
- spec/controllers/choose_a_certified_company_loa2_controller_spec.rb
- spec/features/user_visits_choose_a_certified_company_page_spec.rb
- stub/throttling.yml
- this change works with 2 IDPs and allows us to toggle a split between traffic
- this is only a temporary solution to better distribute traffic between the existing IDPs
- it uses a new cookie to remember which IDP has been assigned
- it's using some of the existing AB logic to work out the split
> HUB-551: Enable throttling of traffic

- config/locales/en.yml
DO NOT MERGE UNTIL THE TRAFFIC SPLITTING STUFF IS LIVE.
These are the minimum changes we need to make for the hub to make sense when only showing a user 1 IDP, but also making sure that it works for users being shown multiple IDPs if the situation changes quickly.
The changes are to: 
- remove the '15 minutes' line which is currently nowhere near true 
- remove content about having a choice of companies
- replace 'choose' with 'select' or 'use' to make it look less like you're meant to have a choice but don't
> HUB-552: Update hub content for traffic splitting

- app/views/failed_registration/_continue_rp.html.erb
- app/views/failed_registration/_custom_failed_registration.html.erb
@jakubmiarka reported the following bug in the verify frontend.  This should hopefully fix the issue:
> BUGFIX for missing styles on failed registration

- app/controllers/completed_registration_controller.rb
- app/models/feedback_source_mapper.rb
- app/views/completed_registration/index.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/main_routes.rb
- spec/controllers/completed_registration_controller_spec.rb
If the IDP no longer has the original SAML request for the user, they're not able
to issue a SAML response back to the hub. This new page will allow them to send the
user back. Also the page updates the journey hint to hint the user next time round.
> HUB-555: Added a /completed page for IDPs to return the users

- app/controllers/choose_a_certified_company_loa1_controller.rb
- app/controllers/choose_a_certified_company_loa2_controller.rb
- app/controllers/what_happens_next_controller.rb
- app/models/feedback_source_mapper.rb
- app/views/redirect_to_idp_warning/redirect_to_idp_warning.html.erb
- app/views/what_happens_next/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/main_routes.rb
- spec/controllers/choose_a_certified_company_loa1_controller_spec.rb
- spec/controllers/choose_a_certified_company_loa2_controller_spec.rb
- spec/controllers/what_happens_next_controller_spec.rb
- spec/features/idp_selections_reported_to_piwik_spec.rb
- spec/features/user_visits_redirect_to_idp_warning_page_spec.rb
- spec/features/user_visits_the_choose_a_certified_company_about_idp_page_spec.rb
- spec/features/user_visits_what_happens_next_page_spec.rb
Based on the designs here: https://docs.google.com/drawings/d/1B7vcWXMxTW6CllgNc1Wh4Is24-6XaWddm-Ain-xq5PI/edit
Have created an additional page on the journey. 'What happens next' page.
The original redirect-to-idp-warning page has changed content to show information regarding the long wait time
ticket: https://govukverify.atlassian.net/secure/RapidBoard.jspa?rapidView=144&projectKey=HUB&modal=detail&selectedIssue=HUB-553
> HUB-533: Update hub to prepare users for IDP queueing

- config/locales/en.yml
Change from "several hours or more" to "a while" because this is more accurate given the queues now.
> Change queue warning time

- app/views/failed_registration/_continue_rp.html.erb
- app/views/failed_registration/_custom_failed_registration.html.erb
- app/views/failed_registration/_non_continue_rp.html.erb
- spec/features/user_visits_failed_registration_page_spec.rb
This is because due to traffic splitting the user will only ever see one IDP.
This is a temporary measure until we fix the splitting logic to be more clever.
As per https://docs.google.com/document/d/1UsYvR21RATKHG2e2-v-zvx0x8GFQJZBar30g926IxBg/edit#
Also don't show IDP contact details for now.
> BAU: Remove prompt to try with another IDP on registration failure

- app/constraints/select_route.rb
- app/controllers/partials/analytics_partial_controller.rb
- app/models/ab_test/ab_test.rb
- app/models/analytics/federation_reporter.rb
- config/main_routes.rb
- spec/constraints/select_route_spec.rb
- spec/models/ab_test/ab_test_spec.rb
- spec/models/analytics/federation_reporter_spec.rb
Piwik/Matomo tracks what variant the user is in during an AB test. This is achieved by setting a custom
variable for AB_TEST. Currently this gets set by reporting a virtual page view
"The user has started an AB test" at the start of the test.
This change stops using the extra call to piwik, but instead adds the custom variable
our existing array (along with LOA and RP). Which gets reported with a standard page view.
This eliminates the race condition between the virtual page view and a standard page view.
It's using flash on the request, as it's not needed to persist across and is only required
when user visits the routes which are being AB-tested.
Additionally, it also simplifies the set up of the AB test, since we no longer need
two set of constraints for piwik reporting and normal …
> HUB-566: Change how AB test is reported

- config/main_routes.rb
- spec/controllers/about_loa2_variant_c_controller_spec.rb
- spec/controllers/choose_a_certified_company_loa2_variant_c_controller_spec.rb
- spec/controllers/select_documents_variant_c_controller_spec.rb
- spec/features/user_visits_about_page_variant_spec.rb
- spec/features/user_visits_choose_a_certified_company_variant_c_page_spec.rb
- spec/features/user_visits_select_documents_variant_c_page_spec.rb
We want to run a different AB test, so partially tearing the short hub one.
All the code is left, the routes are just put back and tests skipped.
> BAU: Temporary short hub AB test tear-down

- spec/features/user_visits_start_page_variant_spec.rb
Content was removed in a previous PR https://github.com/alphagov/verify-frontend/pull/826, somehow this test managed to get through passing previously. Changed the content to what it should now be.
> BAU: Fix broken test due to content being removed

- app/models/session_validator/session_start_time_validator.rb
- app/models/session_validator/validation_failure.rb
- config/initializers/prometheus.rb
- lib/prometheus.rb
- lib/prometheus/session_timeout_reporter.rb
- spec/features/user_visits_start_page_spec.rb
- spec/features/user_visits_start_page_variant_spec.rb
- spec/lib/prometheus/session_timeout_reporter_spec.rb
- spec/models/session_validator_spec.rb
We'd like to know how long people take to complete and when their session
expire. This adds a prometheus metrics to measure number of timeouts and also
a metric when their session expired (in minutes). Also enhanced the current log message
to include the time as well.
> HUB-579: Enhance tracking of session timeouts

- app/controllers/partials/analytics_partial_controller.rb
The custom variable for AB_TEST has been wrongly build, using the standard
build function instead of build_for_js one. The impact was that the
variant name did not get reported.
> BUGFIX: Incorrect custom variable for JS client

- app/controllers/partials/user_errors_partial_controller.rb
- app/controllers/redirect_to_idp_controller.rb
- app/models/session_validator/validation_failure.rb
- spec/controllers/redirect_to_idp_controller_spec.rb
- spec/features/user_visits_start_page_spec.rb
- spec/features/user_visits_start_page_variant_spec.rb
- the button on the "new" timeout page had a link missing because the instance
variable (`@redirect_to_destination`) did not get set.
- reclassified the HTTP code for session expiry to be
403 Forbidden to be consistent
- render error page when Single IDP cookie is invalid instead of session timeout
> BUGFIX: Missing link to the service on session expired page

- app/controllers/partials/analytics_partial_controller.rb
The function was building itself twice. It should just retrieve the value.
`ab_test_variant` is not the name but the CustomVariable object and we just need the value.
> BUGFIX: AB test custom variable double built

- config/environments/test.rb
- spec/feature_helper.rb
The feature tests do not work when run separately using `bundle exec rspec spec/features/some_feature_spec.rb`
This is due to the fact we introduced multithreading for in our loading_cache.
When Capybara runs it uses a single thread causing a deadlock since the
thread gets lost. This change allows the test boostrap the application including
the cache and threads.
This can also be enabled in the test.rb config globally, however we only need
it for the feature tests, so adding it to the feature_helper.
> HUB-580: Enable running feature tests separately

- app/controllers/partials/viewable_idp_partial_controller.rb
- app/controllers/paused_registration_controller.rb
- spec/controllers/paused_registration_controller_spec.rb
- spec/features/user_visits_paused_page_spec.rb
- spec/features/user_visits_resume_registration_page_spec.rb
Currently, a resume page will show for IDPs who are no longer accepting
registrations. This change is to make a switch to check the IDP against the list of registration
IDPs, instead of the one for sign-in. Similar change is on the paused page.
The IDP's simple ID gets now checked with the registration list and
the behaviour is the same when user types in a non-existent IDP
> HUB-583: Handle not available IDPs on paused/resume pages

- app/controllers/partials/user_cookies_partial_controller.rb
- spec/support/tracking_cookie_examples.rb
Our cookie monster was implemented in Sep 2018. At that time we changed
the structure/schema of the journey hint cookie. It's been cleaning users'
cookie from the old structure/schema. Given the 18 months cookie
expiry, it's now to safe to remove it as there should be no more users with the old
schema.
> BAU: Cookie monster is now no longer needed

- app/controllers/prove_identity_variant_controller.rb
- app/controllers/start_variant_controller.rb
- app/models/analytics/federation_reporter.rb
- spec/controllers/prove_identity_variant_controller_spec.rb
- spec/controllers/start_variant_controller_spec.rb
- spec/models/analytics/federation_reporter_spec.rb
We shouldn't be reporting the whole transaction, but only the transaction simpleID.
The simpleID has been still present as part of the custom variables.
> BUGFIX: When hint ignored, report transaction simpleID

- app/controllers/choose_a_certified_company_loa2_controller.rb
- app/controllers/partials/journey_hinting_partial_controller.rb
- app/views/failed_registration/_continue_rp.html.erb
- app/views/failed_registration/_custom_failed_registration.html.erb
- app/views/failed_registration/_non_continue_rp.html.erb
- app/views/failed_registration/index_LOA2.html.erb
- spec/controllers/choose_a_certified_company_loa2_controller_spec.rb
- spec/controllers/hint_controller_spec.rb
- spec/features/user_visits_choose_a_certified_company_page_spec.rb
- spec/features/user_visits_failed_registration_page_spec.rb
Ignore traffic splitting logic if last status is FAILED
Change the link on the failed page to redirect to the IDP picker page.
Revert changes to the failure page from #821
> HUB-572: Show all IDPs after registration failure while splitting traffic between IDPs

- app/assets/stylesheets/verify-frontend.scss
- app/views/choose_a_certified_company/_idp_option.html.erb
- app/views/paused_registration/resume.html.erb
- app/views/shared/_idp_list.erb
- app/views/sign_in/index.html.erb
- app/views/single_idp_journey/continue_to_your_idp.html.erb
1. Fix the resume page width - https://github.com/alphagov/verify-frontend/commit/b95a49527cfdeb5341422c446085abc5ff103dda
**Before:**
**After:**
=== === ===
2. Fix the sign-in page width and spacing - https://github.com/alphagov/verify-frontend/commit/eff234a46a9a15b55ec760495936ccbd1bb8e6cc
**Before:**
**After:**
=== === ===
3. Fix the single IDP screen width and button colour - https://github.com/alphagov/verify-frontend/commit/dcaa918d51b665eb09ce5db15b4682113b21030f
**Before:**
**After:**
> BAU: Fix styling after design system migration

- app/views/errors/session_timeout.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_encounters_error_page_spec.rb
- spec/features/user_visits_start_page_spec.rb
- spec/features/user_visits_start_page_variant_spec.rb
This page is now used for all session timeouts and the content needs to reflect that.
> HUB-582: Update session_timeout page content

- app/assets/config/manifest.js
With latest uprade to Rails, we need to explicitly link the directories
> BUGFIX: Add GOV.UK fonts to the asset manifest

- app/controllers/partials/user_errors_partial_controller.rb
- app/views/errors/session_timeout.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/api_test_helper.rb
- spec/features/user_encounters_error_page_spec.rb
- stub/api/stub_api.rb
This page is now used for session timeouts and the content needs to reflect that.
> HUB-582: Include service name on the session_timeout page

- Gemfile
- Gemfile.lock
- app/assets/config/manifest.js
- app/assets/javascripts/application.js.erb
After the migration to GOV.UK Frontend 3 (Design System), we no longer
use/need the legacy gems for elements, frontend toolkit and template.
> BAU: Remove old GOV.UK gems

- Gemfile
- Gemfile.lock
This resolves the medium severity vulnerability [CVE-2020-8130](https://github.com/advisories/GHSA-jppv-gw3r-w3q8) in Rake
> HUB-584: Update Rake version

- app/controllers/authn_request_controller.rb
- stub/api/stub_api.rb
- stub/relying_parties.yml
- Currently if any service has LOA1 in their transaction config, then it always appears first in the request. This means the logic which sets the loa in the frontend currently makes sense. However as there will be a new RP where LOA1 comes second and the RP needs to go through the LOA1 hub, then this logic no longer makes sense. 
- Check if any LOA is LEVEL_1 and if it is, then set the LOA in the session to LEVEL_1.
- Add the new loa2_loa1_test_rp to the list of stubs.
> Ensure correct loa is set in session 

- .rubocop.yml
- app/controllers/authn_request_controller.rb
- config/initializers/logging.rb
Since the latest linter changes, we're not logging to logstash. We
suspect it's the linter issue and logstash differentiate between ' and ".
Let's give this a go.
Also removed a `puts` statement...
> BAU: Fix (hopefully) logging to logstash

- config/main_routes.rb
- spec/api_test_helper.rb
- spec/features/user_sends_authn_request_spec.rb
- spec/models/config_proxy_spec.rb
- We want any service that use this ordering of LOAs [LOA2, LOA1] to be able to see the prove identity page when they have eIDAS enabled in their transaction config.
- To achieve this we need to add the prove identity to the LOA1 routes.
> Allow any LOA1 service that has eIDAS enabled to see the prove identity page

- app/controllers/partials/journey_hinting_partial_controller.rb
- spec/controllers/prove_identity_controller_spec.rb
- spec/controllers/start_controller_spec.rb
Set the hint layout in the hint controller so it always gets rendered with the correct styles (i.e. no blue background when rendered on the Start page)
Fix the tests so they correctly verify the hint layout - the `render_template` assertion only takes one argument so needs to be called separately with the expected layout
> HUB-595: Render the hint with the correct layout

- config/main_routes.rb
- spec/controllers/about_loa2_variant_c_controller_spec.rb
- spec/controllers/choose_a_certified_company_loa2_variant_c_controller_spec.rb
- spec/controllers/select_documents_variant_c_controller_spec.rb
- spec/features/user_visits_about_page_variant_spec.rb
- spec/features/user_visits_choose_a_certified_company_variant_c_page_spec.rb
- spec/features/user_visits_select_documents_variant_c_page_spec.rb
We as a team have agreed to pursue the short hub AB test.  This commit is to revert the commit which disabled it in the first place.  That commit was:
https://github.com/alphagov/verify-frontend/pull/823
Jira Ticket: https://govukverify.atlassian.net/browse/HUB-599
> HUB-599 Reverted the removal of short hub

- app/controllers/partials/analytics_cookie_partial_controller.rb
- app/controllers/paused_registration_controller.rb
- app/controllers/redirect_to_idp_controller.rb
- app/controllers/redirect_to_idp_warning_controller.rb
- app/controllers/sign_in_controller.rb
- app/controllers/single_idp_journey_controller.rb
- app/models/policy_endpoints.rb
- app/models/policy_proxy.rb
- lib/cookie_names.rb
- spec/controllers/redirect_to_idp_controller_spec.rb
- spec/features/idp_selections_reported_to_piwik_spec.rb
- spec/features/user_visits_continue_to_your_idp_page_spec.rb
- spec/features/user_visits_redirect_to_idp_warning_page_spec.rb
- spec/features/user_visits_resume_registration_page_spec.rb
- spec/features/user_visits_sign_in_page_spec.rb
- spec/models/policy_proxy_spec.rb
* This PR updates the `analytics_session_id` method in `AnalyticsCookiePartialController` to generate and return its own cookie, distinct from Matomo.
* The cookie holds a random id, with an expiry of 13 months (matching the current behaviour).
* Tests that expect `analytics_session_id` to be `nil` are updated to reflect the fact that this id is always generated.
For context, see:
* [HUB-468](https://govukverify.atlassian.net/browse/HUB-468) (jira)
* [PS-53](https://trello.com/c/CxxaKSUg/53-preserve-ability-to-report-investigate-fraud-using-non-analytics-cookie) (trello)
> HUB-468, PS-53, create new persistent session id

- app/controllers/authn_response_controller.rb
- app/models/saml_proxy_api.rb
- app/models/saml_proxy_endpoints.rb
- spec/api_test_helper.rb
- spec/controllers/authn_response_controller_spec.rb
- spec/models/saml_proxy_api_spec.rb
**What**
- When we receive a response from a IDP at the frontend, we want to add on the analytic id and journey type before sending it on to saml proxy. This will allow us to log each of these attributes in policy.
**Why**
- Because we're not currently doing it and it is resulting in Policy logging null for these attributes. It would be useful to see the journey type and analytic id in the responses. This will allow us to filter in kibana based on if a user has come back from a sign-in or registration journey etc.
> Send analytic id and journey type to saml proxy on IDP response

- app/assets/javascripts/select_documents_checkbox_management.js
- app/controllers/select_documents_variant_c_controller.rb
- app/models/analytics/federation_reporter.rb
- app/views/select_documents_variant_c/index.html.erb
- spec/controllers/select_documents_variant_c_controller_spec.rb
- spec/features/user_visits_select_documents_variant_c_page_spec.rb
- spec/javascripts/select_documents_variant_c_spec.js
- spec/models/analytics/federation_reporter_spec.rb
see https://govukverify.atlassian.net/browse/HUB-235
**What**
We need to measure a bunch of things as part of the short hub ABC test. Some of those things will require additional tracking.
The user will be asked to select what evidence they have, and may return to that page for several attempts. For example, if the user does not select enough evidence the first time, they get to an ‘other ways’ page, but may use their back button / click “try again” and have another attempt, in which they confess to having a passport.
We think we want to be able to track (in priority order):
evidence selection on submission of the new evidence checkbox page (/select-documents) - what combinations of evidence do users select on each attempt.  (If each combination of ticked evidence becomes a virtual page …
> HUB-235: Add additional tracking to short hub variant c abc test

- Gemfile
- Gemfile.lock
The old version is not compatible with the recent upgrades to other test libraries.
We can't use the newest version because we're not on the latest version of Rails and this causes dependency conflicts.
> BAU: Upgrade web-console

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_select-documents-advice.scss
- app/controllers/select_documents_variant_c_controller.rb
- app/views/select_documents_variant_c/advice.html.erb
- app/views/select_documents_variant_c/prove_your_identity_another_way.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_visits_select_documents_advice_page_spec.rb
These are changes to fix comments from Beth, in addition changed Summary list to Ul list due to HTML validation issue, where Summary list require 'dt' tag
Some of the kick out pages have the columns the wrong way round. These are the ones for:
- driving licence + phone
- driving licence + card
-  phone + card
1. They all have the 'things you do not have with you' column first. This is confusing if a user has been back and forth a couple of times, and are expecting that column to be the same as the other pages.
2. The 'none of the above' version of the kick out page does not include the correct content - it should be like the 'none of the above' row of the table in this document: https://docs.google.com/document/d/1wDXEkqigqcy4q5-_xhFffO6kFCFdR559i-_gKuhVR8Q/edit#heading=h.p5rhhpvlqt6k
3. …
> Hub 636 bau change short hub logic and kick out pages

- app/views/select_documents_variant_c/advice.html.erb
- spec/features/user_visits_select_documents_advice_page_spec.rb
Minor content tweaks, for when you select 'None of the above' check box on the Select Document page under short hub variant (short_hub_2019_q3-preview_variant_c_2_idp_short_hub) and click on continue
- make bullet list start with lower case
- Remove spaces above bullet list
**Before**
**After**
> BAU: document advice page layout

- app/controllers/paused_registration_controller.rb
- app/models/config_proxy.rb
- lib/api/eidas_error.rb
- lib/api/session_error.rb
- lib/api/session_timeout_error.rb
- lib/api/upstream_error.rb
- spec/api_test_helper.rb
- spec/controllers/paused_registration_controller_spec.rb
see: https://govukverify.atlassian.net/browse/HUB-518
From https://sentry.tools.signin.service.gov.uk/verify/prod-frontend/issues/4309/?query=is:unresolved
https://www.signin.service.gov.uk/paused
Api::Error: Unexpected error whilst trying to communicate wth the Hub. Received 404 with error message: 'NONE', type: 'NONE' and id: 'NONE', Referer: ''
The Hub may be unreachable. Check all services are running and are accessible
This is (now) an expected case: the user has a pause-and-resume cookie indicating an RP using an entity ID that no longer exists.
We are seeing these because of a change to HMRC’s entity id’s.
We should catch these exceptions and the user should get the same behaviour as when they go to that URI with no pause-and-resume cookie.
We think that the function where we might …
> Hub-518: crash on paused frontend endpoint

- config/main_routes.rb
- spec/controllers/about_loa2_variant_c_controller_spec.rb
- spec/controllers/choose_a_certified_company_loa2_variant_c_controller_spec.rb
- spec/controllers/select_documents_variant_c_controller_spec.rb
- spec/features/user_sends_authn_request_spec.rb
- spec/features/user_visits_about_page_variant_spec.rb
- spec/features/user_visits_choose_a_certified_company_variant_c_page_spec.rb
- spec/features/user_visits_prove_your_identity_another_way_page_spec.rb
- spec/features/user_visits_select_documents_advice_page_spec.rb
- spec/features/user_visits_select_documents_variant_c_page_spec.rb
- stub/ab_test.yml
Don't deploy this until the corresponding config has been updated!
Remove '-preview' from `SHORT_HUB_2019_Q3` constant.
Update `stub/ab_test.yml` to reflect new constant
Don't remove long dead tests from `stub/ab_test.yml` because it turns out they're used in some of the tests.
> BAU Make the non-preview shorthub AB test live [DO NOT MERGE]

- config/locales/cy.yml
`service_name` should have been changed to `service` in cy.yml as well as en.yml.
> BAU Fix an interpolation variable name in cy.yml

- config/initializers/00_configuration.rb
See : https://govukverify.atlassian.net/browse/HUB-613
Redis client's timeout will need to change to something smaller than 30 seconds. The timeout among hub services would be 
Redis client = 20s, saml-engine=24 < policy = 26 < saml-proxy = 28 < frontend = 30secs
Also see: https://github.com/alphagov/verify-hub/pull/458
> HUB-613: reduce frontend timeout to 30secs

- Gemfile
- Gemfile.lock
- app/assets/javascripts/00-cookies.js
- app/views/layouts/application.html.erb
- config/application.rb
We've already fixed the Ruby SameSite cookie issue.  This is the first cookie to try to fix the SameSite cookie issue which results from cookies set using JavaScript.
The command and output for generating the hash.
```
echo "'sha256-"$(echo -n "document.cookie = 'seen_cookie_message=yes; expires=' + new Date(new Date(Date.now()).setMonth(new Date(Date.now()).getMonth() + 1)) + ';SameSite=None;secure'" | openssl dgst -sha256 -binary | openssl enc -base64)"'"
'sha256-XtNXdOiMcIxK6AyojaxR2Nyuq+9yD49R6eC2CJf1mcQ='
```
> Fix for JavaScript SameSite issue

- Gemfile
- Gemfile.lock
After upgrading Ruby to 2.6.6, the gem ffi got updated to a newer version that requires a version of the system library `/usr/lib/libffi.dylib` that's not available on MacOS Mojave. This commit reverts the gem to a previous version that works with the library available on our dev machines.
Ideally we'd be running everything in Docker and this wouldn't be an issue but as a temporary solution we can use an older version of the library to make this work on our machines.
> BAU: Fix Ruby 2.6.6 expecting a newer version of system library

- config/main_routes.rb
- spec/feature_helper.rb
- spec/features/user_submits_start_page_form_spec.rb
* Amends the routes, pulling the `start_ignore_hint` route out of the LOA2 constraint, and up to root-level.
* Adds `default_session_loa1` to `feature_helper.rb` so as to make it trivial to test under LOA1 circumstances.
* Adds 2 tests to `user_submits_start_page_form.spec` which, technically, isn't quite the right place because this isn't a form submission, it's a simple anchor click - but it still seems like the most theme-appropriate place to put them. They test that the ignore-hint link correctly takes the user to the start page, rather than the 404 (as seen previously).
_Also manually tested without the route fix to show that under LOA1 circumstances, the routing fails and the user sees a 404._
> BAU Repair the ignore hint route for LOA1

- spec/features/user_sends_authn_request_spec.rb
- stub/ab_test.yml
This file hasn't been maintained but it is used by verify-local-startup and should be maintained, ideally with the same config we have in production.
> HUB-720 Align the ab_test.yml with prod

- app/views/choose_a_country/choose_a_country.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Update the content on the country picker page to include Brexit transition messaging, in Welsh and English. Screenshots of changes that indicate the new intended text:
> EID-2069 Brexit transition messaging on country picker page

- app/assets/javascripts/will_it_work_for_me.js
- spec/javascripts/will_it_work_for_me_spec.js
Typo in element identifier will_it_work_for_me_form_not_resident_reason_movedrecently
causes error in javascript.
> BAU: fixed error in javascript

- config/initializers/00_configuration.rb
- lib/configuration.rb
- spec/lib/configuration_spec.rb
Add `option_datetime` method to enable parsing of date time environment variables
Write tests to ensure method is working to story spec.
> EID-2077 configure frontend with `eidas_disabled_after` from env var

- app/controllers/authn_request_controller.rb
- spec/controllers/authn_request_controller_spec.rb
If EU exit date is set in config, and in the past, then controllers will route to pages without eIDAS content.
Follows on from the [PR to set an EU exit date in frontend](https://github.com/alphagov/verify-frontend/pull/910).
Co-authored-by: Amrit Sidhu <amrit.sidhu@digital.cabinet-office.gov.uk>
> EID-2065 Controllers don't route to eIDAS content after EU exit

- .rubocop.yml
- Gemfile
- kill-service.sh
- startup.sh
- Remove the `-d`(aemonize) option removed in version 5. Use the bash background task management instead. Append `&` to run the server in background when frontend is run as part of the full hub configuration. If running as stub API, run in foreground so it can be stopped by pressing Ctrl+C
- Create the `tmp` folder if it doesn't exist. Puma/Rake needs this folder to hold its state. If it doesn't exist, the process will quit immediately without printing any error message
- Don't print error message from `rm` when killing the service. Running `kill` removes the pid file under certain conditions
- Reorder gems in the Gemfile to be in alphabetical order to appease Rubocop
- Exclude the Gemfile from the `StringLiterals` Rubocop check
> BAU: Fix local startup after Puma upgrade

- app/controllers/partials/eidas_validation_partial_controller.rb
- spec/controllers/choose_a_country_controller_spec.rb
- spec/controllers/redirect_to_country_controller_spec.rb
Alter eidas_validation_partial_controller.rb to check whether eIDAS shutdown time has passed and act accordingly.
Add tests.
> EID-2067 Don't accept SAML requests once eIDAS has been shut down

- app/views/select_documents/advice.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_visits_select_documents_advice_page_spec.rb
- spec/features/user_visits_select_documents_page_spec.rb
The accessibility audit turn up duplicate titles on the select documents and select documents advice page.  This PR is to fix this minor issue.
> BAU Fix title on select document advice page

- app/controllers/choose_a_certified_company_about.rb
- app/controllers/choose_a_certified_company_loa2_controller.rb
- app/controllers/partials/failed_registration_partial_controller.rb
- app/controllers/select_documents_controller.rb
- app/models/idp_recommendations/recommendations_engine.rb
- spec/features/user_visits_choose_a_certified_company_page_spec.rb
- spec/models/idp_recommendations/recommendations_engine_spec.rb
The journey now looks like this:
This fixes a bug in the frontend. If a user failed to register with an
IDP and their AuthnResponse was returned with a "FAILED" state, they
would be directed via a landing page and a link back to the choose a
company page.
The logic on that page would retrieve a list of IDPs from the
recommendation engine, including the IDP they just failed with. If they
the selected that IDP again, it's entity ID would be compared to a
separate list of available IDPs - this time with any IDPs the user had
already failed with removed. This caused an error.
This change ensures the recommendation engine doesn't return an IDP the
user has failed with, and so it's not presented to them on the choose an
IDP page.
The rendered partial never uses it, so there is no need to pass …
> HUB-783: Failed registration bug

- app/controllers/paused_registration_controller.rb
We've been getting a constant trickle of errors in Sentry from the
PausedRegistration controller. The errors are kicked when we try to
render the "with_user_session" paused registration view with a
NotViewableIdentityProvider. The view calls the `display_name` method on
the IDP object, but that doesn't exists for non viewable IDPs.
We get this error after trying to retrieve the users IDP from their
journey hint cookie. We attempt this as we've already determined that
their session isn't valid so can't retrieve it from there. Unfortunately
we jump through a lot of hoops which could all return nil (and so force
a non viewable IDP from the IDP decorators `correlate_display_data`
method), which makes determining the exact issue difficult.
This commit catches a non viewable IDP before we pass …
> HUB-740: Log info when PausedRegistration IDP not viewable

- app/views/static/privacy_notice.en.html.erb
The GOV.UK Verify Privacy Team email address is no longer being used. I've swapped this out for the GDS Privacy Team email address.
> Removed reference to GOV.UK Verify Privacy Team

- app/controllers/paused_registration_controller.rb
[This PR ](https://github.com/alphagov/verify-frontend/pull/924)to diagnose a bug introduced a new bug. You can't call `render` twice in the same controller action. `render` doesn't return, so you need to call it yourself.
> HUB-740: Fix double render

- app/views/static/privacy_notice.cy.html.erb
- app/views/static/privacy_notice.en.html.erb
There is some eIDAS content on the [Verify Privacy Notice page](https://www.signin.service.gov.uk/privacy-notice), which we should remove.
Remove both the English and Welsh content.
> BAU Remove eIDAS content from Verify Privacy Notice page

- app/views/layouts/application.html.erb
When I was logging into Verify I noticed the skiplink on the /start page doesn't work because it's URL doesn't point to the id of the main content area.
This should fix it for that and other pages I think. I chose to change the skiplink URL rather than the main content area id because:
- www.gov.uk uses that id for its one
- I can't find anything in this repository using the 'main-content' id
> Make skiplink anchor link to main content area

- app/controllers/paused_registration_controller.rb
To help check that users aren't being sent to the pause page by IDPs
that no longer offer registrations.
> HUB-740: Log referer on pause page

- Dockerfile
This PR updates the Dockerfile to provide sentry with the current release information as an environment variable.
> HUB-744 Provide release infomration to Frontend

- config/initializers/00_logging.rb
This PR makes sentry look at the SENTRY_RELEASE environment variable which is provided by our Pipeline and in our Dockfile.  This standardise the name of the variable across our projects.  Sadly the Sentry Gems aren't automatically configured from environment variables.
> HUB-744 Make Sentry look at the correct envvar

- app/controllers/paused_registration_controller.rb
The logic as stands was causing the text `Unable to serve the requested
format` to be rendered.
This should solve.
> BAU: Fix rendering error

- app/assets/stylesheets/pages/_company.scss
- app/views/choose_a_certified_company/_idp_option.html.erb
- app/views/choose_a_certified_company/choose_a_certified_company_LOA1.html.erb
- app/views/choose_a_certified_company/choose_a_certified_company_LOA2.html.erb
see: https://govukverify.atlassian.net/browse/HUB-792
Moving the about link to a secondary button placed
on the right hand side of the choose button this
should fix the accessibility issue.
> HUB-792: Turn about link to Secondary button

- app/assets/stylesheets/pages/_company.scss
- app/views/choose_a_certified_company/_idp_option.html.erb
I am hoping this align the IDP logo with the buttons an attempt to line up the Idp logo with buttons
Currently it looks like this
This change
> HUB-792: Align idp logo with button

- app/controllers/partials/journey_hinting_partial_controller.rb
- app/controllers/partials/user_cookies_partial_controller.rb
- app/controllers/paused_registration_controller.rb
- app/views/paused_registration/idp_no_longer_providing_registrations.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/controller_helper.rb
- spec/controllers/authn_response_controller_spec.rb
- spec/controllers/paused_registration_controller_spec.rb
We get a few errors coming through for users attempting to restart
journeys with IDPs that are no longer providing registrations. The
cookie that informs this last for 18 months.
This will show users a new page if their paused journey is for an IDP
that no longer offers registrations and advise them to go back to their
service and try again.
This PR needs a content review as well as Welsh translations.
This new page is a new variant for an existing endpoint. The two screenshots below show what happens if the IDP is still offering registrations - the difference between them is whether the user had a session or not at the time of the page load. The new page is for when the IDP is no longer offering registrations.
> HUB-740: Handle paused journeys for sign in only IDPs

- app/controllers/further_information_controller.rb
`@seconds_to_timeout` and the method `get_seconds_to_timeout` which populated it are no longer used now that the modal dialog has been removed so they have been removed also.
> HUB-794 Tidy up redundant variables and method

- pre-commit.sh
I couldn't help myself.  Bash has a a sensible way of handling command line options which I think should generally be followed so I have updated the pre-commit script to follow this pattern.
> BAU Fix options in pre-commit script

- app/assets/stylesheets/pages/_company.scss
- app/views/choose_a_certified_company/_idp_option.html.erb
This PR is the 3rd refinement of this
- Horizontally center buttons and buttons same width
- Center table rows vertically
- Reduce space between primary and secondary buttons
**when in mobile view**
- Also attempted to fix who do you have an identity account with?
The buttons are now relatively the same width and only wrap if
the text is really very long
Other buttons are not affected by this change
> BAU: fix alignment issues on picker page

- app/views/start/start.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Christopher Thomas took a look at hub as a part of UCD feedback for the short hub, before it was famous. (The variant formerly known as "C".)
* The hub's start page is missing a legend.
* It should contain the question that the user is being asked.
* In this case, that's "Have you used GOV.UK Verify before?"
* Also, Welsh.
> HUB-809 add legend to start page

- app/views/sign_in/warn_idp_disconnecting.html.erb
- config/locales/cy.yml
- config/locales/en.yml
To be compliant with accessibility and also to make smoke tests pass
> HUB-853: Change IDP disconnecting warning page title to be the same as the heading

- config/locales/cy.yml
* Adds welsh warning text to the IDP warning page for decommissioning IDPs.
_Weirdly unable to test locally - so don't review until tests pass._
> HUB-853 add welsh translation to IDP warning page

- app/views/sign_in/warn_idp_disconnecting.html.erb
- config/locales/cy.yml
- config/locales/en.yml
One of the recent PRs broke the link on the IDP warning page.  This PR fixes this broken link so it display correctly
> BAU Fix for broken link on warning page

- app/controllers/partials/viewable_idp_partial_controller.rb
- spec/controllers/sign_in_controller_spec.rb
This is a draft PR to hide IDPs 2 hours before they are due to be disconnected.
> HUB-859 Show IDP as no longer available at 2 hours

- spec/features/user_visits_idp_warning_page_spec.rb
This adds the functional test for the new IDP disconnecting warning page.
> HUB-853 Add functional test for new warning page

- app/assets/stylesheets/pages/_company.scss
The company logo on the "last company selected" page is squashed. This
reverts the height to what it was previously, which resolves.
The original change was brought in [here.](https://github.com/alphagov/verify-frontend/commit/c24065e4b3ba702cde3c4b1da73d1c615bafb577)
> BAU: Fix squashed logo

- README.md
* The changes in mimemagic 0.3.8 to keep it MIT licensed mean there's an additional prerequisite to install on OS X now.
* I also added mention of verify-local-startup as an option for running the frontend.
> HUB-891 Update README to reflect new prerequisite for OS X

- app/views/static/accessibility.en.html.erb
Context: Our recent accessibility audit raised some issues which we have fixed, including previously known problems. We have a legal obligation to make our website accessible and we are now fully compliant with Web Content Accessibility Guidelines version 2.1 AA standard. This PR updates our accessibility statement to say this. 
Accessibility fixes include:
- [Making page titles accessible](https://github.com/alphagov/verify-frontend/pull/939)
- [Removing modal timeout](https://github.com/alphagov/verify-frontend/pull/936)
- [Removing duplicate page titles](https://github.com/alphagov/verify-frontend/pull/922)
- [Colour contrast and other fixes](https://github.com/alphagov/verify-frontend/pull/736)
> HUB-726 Statement updated to reflect accessibility fixes

- app/models/config_endpoints.rb
We're getting TypeErrors in Sentry which are implying that the
transaction ID retrieved from the users session is nil. We have a
validator however that should be preventing requests without this value
in their session from being accepted.
This logging will allow us to inspect the session in these cases to
determine what is actually happening.
> HUB-920: Add logging to help diagnose issue

- app/controllers/partials/viewable_idp_partial_controller.rb
- app/models/config_endpoints.rb
- app/models/config_proxy.rb
- spec/api_test_helper.rb
The session object is not available in a model (confusingly it is when
running tests...).
The only reasonable way to get that information into the model is to
pass it in from the controller.
> HUB-920: Fix logging

- config/locales/cy.yml
The heading is currently appearing in English on the Welsh version of
the page, as the key is wrong.
> HUB-863: Fix key for Welsh certified_companies_disconnected heading

- app/controllers/completed_registration_controller.rb
- app/controllers/paused_registration_controller.rb
- spec/controllers/completed_registration_controller_spec.rb
- spec/controllers/paused_registration_controller_spec.rb
In the PausedRegistration controller we were skipping session
validation, except for the `resume` action. This was so that users
returning after pausing, via the #index or #from_resume_link actions,
who's sessions may have expired, weren't booted to the usual error page.
We were explicitly still validating the `resume` action however. This
action is accessed with a GET request. The `resume_with_idp` and
`resume_with_idp_ajax` actions are accessed with POST requests made from
the `resume-registration` page rendered by the `resume` action. We were
not validating the session on theses POSTs.
We've seen occurrences of a users session becoming invalid in between the
initial GET for `resume` and then the following POSTs. We should
validate the POSTs too to capture this.
Hopefully this will …
> BAU: Fix a couple of bugs

- config/locales/cy.yml
The arg key had been translated too.
Fixes https://sentry.io/organizations/gds-verify/issues/2440058223/?environment=production&project=549439
> HUB-863: Fix bug with Welsh translation

- app/controllers/about_controller.rb
- app/views/about/documents.html.erb
- app/views/about/how_verify_works.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_visits_about_documents_spec.rb
- spec/features/user_visits_may_not_work_if_you_live_overseas_spec.rb
- spec/features/user_visits_sign_in_page_spec.rb
- spec/features/user_visits_why_might_this_not_work_for_me_page_spec.rb
- spec/features/user_visits_will_it_work_for_me_page_spec.rb
Preparing for a single IDP world we've been asked to make some content changes to the How Verify Works page.  This commit introduces an if statement to the view which renders the existing content if there is more than one page or the new content if only 1 IDP is present.
Multiple IDP Jounrey:
Single IDP Journey:
> HUB-1117: One IDP updates to How Verify Works Page

- app/controllers/cancelled_registration_controller.rb
- app/views/cancelled_registration/cancelled_registration.html.erb
- spec/controllers/cancelled_registration_controller_spec.rb
- spec/features/user_visits_cancelled_registration_page_spec.rb
This is the last change for single ISP world which removes the option to try another IDP on the cancel registration controller.
> HUB-1118 Last page update for the single idp world

- app/controllers/partials/journey_hinting_partial_controller.rb
- app/controllers/sign_in_controller.rb
- spec/feature_helper.rb
Avoid a Nil reference when reporting a sign_in journey hint.
Log the entity that cannot be found in the set of active and disconnected idps.
> BAU Avoid Nil reference when reporting a sign_in journey hint

- app/views/shared/_transaction_list.html.erb
- As there are few services currently connected, we don't need to group them under the taxon name. Instead just list the services all together.
> HUB-1155 - Refactor verify services page

- Dockerfile
- app/views/shared/_transaction_list.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_encounters_error_page_spec.rb
- spec/features/user_visits_prove_your_identity_page_spec.rb
- spec/features/user_visits_start_page_spec.rb
The list of services on [this page](https://www.signin.service.gov.uk/verify-services) currently reflects which ones are still connected in the config. 
We need to stop this from happening, and just show the list of services in here as plain text that we’ll manually update in future. 
We’re going to let some services stay technically connected to Verify even after they’ve switched off sign ups/ins, just in case something goes wrong and they need to revert to using Verify. 
We don’t want this page to be misleading for users, or the journalists who use this page as a source of truth.
> stop auto generating services page

- app/views/static/privacy_notice.en.html.erb
Self-assessment no longer uses GOV.UK Verify.
> Remove self assessment link

- Gemfile
- Gemfile.lock
Reverts alphagov/verify-frontend#1016
This PR blocks the pipeline. We will temporarily revert it, in favour of higher priority ITHC updates.
> Revert "Bump prometheus-client from 0.10.0 to 4.0.0"
