- LICENSE
> Copyright notice should be Crown Copyright

- app/models/api_client.rb
- spec/models/api_client_spec.rb
It would be nice to do this globally without having a private method
to configure the client, but this works.
Pair: WillPa
> bau: set a custom user agent for client

- config/locales/en.yml
> bau: match header text in prod

- README.md
> BAU: fix link markdown in README

- app/controllers/cookies_controller.rb
- app/controllers/privacy_notice_controller.rb
- app/views/cookies/index.html.erb
- app/views/layouts/application.html.erb
- app/views/privacy_notice/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
Redirect to old frontend
Pair: WillPa
> bau: add standard links to footer

- packaging/postinst.sh
This post install will no longer control restart of the service as that will be handled by the meta package.
Solo: conor
> 3431: frontend packaging

- packaging/postinst.sh
tidy up this postinst with exit codes
> 3431 - frontend packaging

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- config/initializers/raven.rb
Adding the raven-sentry gem to frontend, so it can report error
logs to sentry.
@yolinas
> 3344 : adding sentry to frontend

- config/locales/en.yml
This change was suggested as part of the mock service assesment
> 3518 Update about text

- config/initializers/configuration.rb
Adds defaults for configuration that is shared across environments.
This should allow us to trim down the config files
> 3517: add more sensible defaults for config

- app/models/analytics/federation_reporter.rb
- spec/models/analytics/federation_reporter_spec.rb
- stub/locales/rps/headless-rp.yml
- stub/locales/rps/loa1-test-rp.yml
- stub/locales/rps/test-rp-noc3.yml
- stub/locales/rps/test-rp-repudiation.yml
- stub/locales/rps/test-rp.yml
Rename analyticsDescription -> analytics_description to bring it into line with the other keys
Add other_ways_text and other_ways_description for remaining RPs
> Bau snake case analytics description

- config/routes.rb
- spec/features/user_visits_no_mobile_phone_page_spec.rb
This reverts commit 847ed42f105050fbd70b7c88402eb8ed9c1cc8ab.
> Revert "Revert "3531: Enable localised route for no mobile phone""

- app/controllers/why_might_this_not_work_for_me_controller.rb
- app/views/why_might_this_not_work_for_me/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
- spec/features/user_visits_why_might_this_not_work_for_me_page_spec.rb
- spec/features/user_visits_will_it_work_for_me_page_spec.rb
This is a PR for why-this-might-not-work-for-me page. The other dead end pages on story #3532 will have separate PRs.
> 3532 why might this not work for me

- app/controllers/may_not_work_if_you_live_overseas_controller.rb
- app/views/may_not_work_if_you_live_overseas/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
- spec/features/user_visits_may_not_work_if_you_live_overseas_spec.rb
PR for the may-not-work-if-you-live overseas page
> 3532 may not work if you live overseas

- config/application.rb
At present these headers are added by nginx.
> 3566 Disable default Rails headers

- app/views/select_documents/index.html.erb
- app/views/select_phone/index.html.erb
- app/views/will_it_work_for_me/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_visits_select_documents_page_spec.rb
- spec/features/user_visits_select_phone_page_spec.rb
- cy.yml is updated as part of this.
- config locale specific text is yet to be updated.
Authors: @veda
> 3564: Adding officially translated welsh text.

- config/locales/cy.yml
- config/routes.rb
- spec/features/user_visits_choose_a_certified_company_page_spec.rb
- spec/features/user_visits_no_mobile_phone_page_spec.rb
- spec/features/user_visits_select_phone_page_spec.rb
- spec/features/user_visits_why_companies_page_spec.rb
- spec/features/user_visits_why_might_this_not_work_for_me_page_spec.rb
- spec/features/user_visits_will_it_work_for_me_page_spec.rb
Copied the .yml file from an email @srinivasmurty forwarded me.
Replaced non-ASCII characters in routes with their closest ASCII
equivalents.
Solo: Rich
> bau: Update welsh translations

- config/locales/en.yml
- spec/features/user_encounters_a_404_spec.rb
- spec/features/user_visits_may_not_work_if_you_live_overseas_spec.rb
- spec/features/user_visits_no_mobile_phone_page_spec.rb
- spec/features/user_visits_unlikely_to_verify_page_spec.rb
- spec/features/user_visits_why_might_this_not_work_for_me_page_spec.rb
- spec/features/user_visits_will_not_work_without_uk_address_page_spec.rb
- stub/locales/idps/stub-idp-three.yml
- stub/locales/idps/stub-idp-two.yml
- stub/locales/rps/headless-rp.yml
- stub/locales/rps/loa1-test-rp.yml
- stub/locales/rps/test-rp-noc3.yml
- stub/locales/rps/test-rp-repudiation.yml
- stub/locales/rps/test-rp.yml
> BAU: Replace straight quotes with curly quotes

- app/controllers/cookies_controller.rb
- app/views/cookies/index.cy.html.erb
- app/views/cookies/index.en.html.erb
- app/views/cookies/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
- spec/features/user_visits_cookies_page_spec.rb
This ports the cookie page. English and Welsh have their own static pages.
solo: @oswaldquek
> 3528: Port cookie page

- app/assets/stylesheets/elements/_tables.scss
- app/views/cookies/index.cy.html.erb
- app/views/cookies/index.en.html.erb
Rather than editing elements files we should use the class it provides.
> Small fonts for cookies table

- app/assets/stylesheets/_application.scss
- app/assets/stylesheets/_govuk-elements-overrides.scss
- app/assets/stylesheets/pages/_confirm_your_identity.scss
- app/assets/stylesheets/pages/_select-documents.scss
- app/views/confirm_your_identity/index.html.erb
- app/views/select_documents/index.html.erb
- app/views/select_phone/index.html.erb
- app/views/will_it_work_for_me/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Make sure the question pages all have appropriate headings. Text and design courtesy of @alextea.
The only translation needed is the new heading on /will-it-work-for-me. The rest was just shuffling around.
> 3636: new headings

- app/assets/stylesheets/pages/_choose_a_certified_company.scss
- app/views/choose_a_certified_company/_idp_option.html.erb
These links are only used in the non-recommended IdPs section at the
moment, so they're not that prominent.
> BAU: Style "button-link"s to have pointer cursors

- app/views/other_ways_to_access_service/index.html.erb
- app/views/select_documents/unlikely_to_verify.html.erb
- app/views/select_phone/no_mobile_phone.html.erb
- config/locales/cy.yml
- config/locales/en.yml
> bau: Other ways title and heading are common

- app/views/static/privacy_notice.cy.html.erb
- config/locales/cy.yml
- spec/features/user_visits_confirm_your_identity_page_spec.rb
- spec/features/user_visits_confirmation_page_spec.rb
> 3564: Added welsh translations

- app/views/static/privacy_notice.cy.html.erb
> 3564: Updated to curly apostrophe in welsh privacy-notice content

- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
> 3642: localize other ways page

- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
> 3322: Localise response processing

- app/views/redirect_to_idp/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
- spec/features/user_visits_sign_in_page_spec.rb
> 3568: Localise redirect-to-idp page

- app/views/static/forgot_company.cy.html.erb
- config/locales/cy.yml
- spec/features/user_visits_failed_registration_page_spec.rb
- spec/features/user_visits_failed_sign_in_page_spec.rb
- spec/features/user_visits_forgot_company_page_spec.rb
- spec/features/user_visits_other_ways_to_access_page_spec.rb
- spec/features/user_visits_response_processing_page_spec.rb
> 3564: Incorporate welsh translations sent as of May 27th.

- app/views/choose_a_certified_company/_idp_option.html.erb
- app/views/choose_a_certified_company/_select_idp_form.html.erb
- app/views/choose_a_certified_company/about.html.erb
- app/views/confirmation/index.html.erb
- app/views/failed_registration/index.html.erb
- app/views/failed_sign_in/index.html.erb
- app/views/redirect_to_idp_warning/_non_recommended.html.erb
- app/views/redirect_to_idp_warning/_recommended.html.erb
- app/views/redirect_to_idp_warning/index.html.erb
- app/views/shared/_idp_list.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_visits_confirmation_page_spec.rb
- spec/features/user_visits_failed_sign_in_page_spec.rb
- spec/features/user_visits_redirect_to_idp_warning_page_spec.rb
Its display_name everywhere now.
Authors: @veda
> 3692: Fixed idp display name inconsistencies.

- config/environments/production.rb
> bau: log at :warn and above in prod-like environments

- app/views/feedback/index.html.erb
- app/views/select_documents/index.html.erb
- app/views/select_phone/index.html.erb
- app/views/start/index.html.erb
- app/views/will_it_work_for_me/index.html.erb
- spec/features/user_visits_select_documents_page_spec.rb
- spec/javascripts/select_documents_spec.js
- spec/javascripts/will_it_work_for_me_spec.js
@accessiblewebuk discovered some problems on the select documents page with JAWS on IE. This helps users correctly understand what each radio button does.
> 3747: select documents problems with JAWS

- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_visits_select_documents_page_spec.rb
- spec/javascripts/select_documents_spec.js
The Verify DCS does accept provisional licenses for Verification and in fact the Rugby job centre gives UC claimants money to get a provisional license.  This is not clear in the hub question.
Pair: @srinivas
> 3775: Update drivers license question text

- Gemfile
- Gemfile.lock
No major or breaking changes here, but should bring in a few performance
improvements
> bau: use httprb 2.0.2

- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
/furhter-information-cy will now be accessible if you're on a welsh journey
> 3332: add localisation support for /further-information

- README.md
All user facing pages are now in this frontend, update the docs to
reflect that.
Pair: WillPa
> bau: new frontend is not new anymore

- Gemfile.lock
- app/controllers/static_controller.rb
- config/routes.rb
- public/humans.txt
- spec/features/user_visits_humanstxt_spec.rb
- stub/api/Gemfile.lock
> bau: fix humans.txt

- pre-commit.sh
- stub/api/Gemfile.lock
> BAU: Run bundle for stub API before specs

- app/controllers/select_documents_controller.rb
- app/controllers/start_controller.rb
- app/views/select_documents/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_visits_start_page_ab_test_spec.rb
- spec/features/user_visits_start_page_spec.rb
- stub/ab_test.yml
front-end changes to support new questions in document selection for A/B test
Verification of results t.b.d. in piwik with drop off rates
Authors: @DataMinerUK @sfkamath
> 5179: for new A/B test on document picker page

- .env
- app/controllers/choose_a_certified_company_controller.rb
- app/views/select_documents/index.html.erb
- config/initializers/configuration.rb
- config/initializers/idp_eligibility_b.rb
- spec/features/user_visits_start_page_ab_test_spec.rb
- stub/ab_test.yml
- stub/idp-rules-b/stub-idp-demo.yml
- stub/idp-rules-b/stub-idp-four.yml
- stub/idp-rules-b/stub-idp-no-docs.yml
- stub/idp-rules-b/stub-idp-one.yml
- stub/idp-rules-b/stub-idp-three.yml
- stub/idp-rules-b/stub-idp-two.yml
- stub/idp-rules-b/stub-idp-unavailable.yml
- bank details and credit/debit cards profiles now considered for AB test
Pair: @DataMinerUK @sfkamath
> 5179 : A/B test for document selection

- app/controllers/feedback_controller.rb
- app/controllers/feedback_sent_controller.rb
- app/views/feedback_sent/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/controllers/feedback_sent_controller_spec.rb
- spec/features/user_submits_feedback_page_spec.rb
- spec/rails_helper.rb
We will send the user back to the page they came from, after submitting feedback, unless it's an error page. In this case, we will send them to the start page.
> 5262 feeback page enhancement

- app/controllers/about_controller.rb
- app/views/about/choosing_a_company.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_visits_about_choosing_a_company_page_ab_test_spec.rb
- spec/features/user_visits_start_page_spec.rb
- stub/ab_test.yml
Change to Finding right company slide for 50-50 ab test
> 5501 finding right company ab test

- app/views/errors/session_timeout.html.erb
- spec/api_test_helper.rb
- spec/features/user_gets_soft_session_timeout_page_spec.rb
> bau: make the start again link look like a button

- .adr-dir
- Gemfile.lock
- app/assets/javascripts/application.js.erb
- app/assets/javascripts/other_documents.js
- app/assets/javascripts/photo_documents.js
- app/assets/stylesheets/pages/_select-documents.scss
- app/controllers/configurable_journey_controller.rb
- app/controllers/other_identity_documents_controller.rb
- app/controllers/select_documents_controller.rb
- app/models/feedback_source_mapper.rb
- app/models/idp_eligibility/evidence.rb
- app/models/other_identity_documents_form.rb
- app/models/photo_documents_form.rb
- app/views/other_identity_documents/index.html.erb
- app/views/select_documents/photo_identity_documents.html.erb
- architecture-decisions/0001-record-architecture-decisions.md
- architecture-decisions/0002-implement-ab-testing.md
- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
- spec/features/user_visits_other_documents_page_ab_test_spec.rb
- spec/features/user_visits_select_documents_page_ab_test_spec.rb
- spec/features/user_visits_start_page_spec.rb
- spec/javascripts/other_documents_ab_test_spec.js
- spec/javascripts/select_documents_ab_test_spec.js
- spec/models/other_identity_documents_form_spec.rb
- spec/models/photo_documents_form_spec.rb
- stub/ab_test.yml
AB test for splitting documents question
> TT-356 split questions again

- .adr-dir
- architecture-decisions/0001-record-architecture-decisions.md
- architecture-decisions/0002-implement-ab-testing.md
Added an ADR for the current ab test setup
Author: @DataMinerUK
> BAU: Add architectural decision record for AB testing

- app/controllers/confirmation_controller.rb
- app/views/confirmation/confirmation_LOA1.html.erb
- spec/controller_helper.rb
- spec/controllers/confirmation_spec.rb
- spec/feature_helper.rb
- spec/features/user_visits_confirmation_page_spec.rb
Finished controller and feature tests for confirmation journey
Authors: @naseerashraf
> TT-355: Completed confirmation page for LOA1 journey

- spec/features/user_visits_choose_a_country_page_spec.rb
> eid-73 : test cases to showcase that a disabled country is handled

- spec/features/user_visits_sign_in_page_spec.rb
> TT-665: Fixed lint spacing problem

- app/assets/javascripts/validation.js
- app/assets/javascripts/vendor/jquery.validate.js
- app/views/select_proof_of_address/select_proof_of_address.html.erb
- spec/controllers/select_proof_of_address_controller_spec.rb
Fixes bug that presents when using previous version (v1.15.0).
Group validation will now work correctly with 3 and more fields
In addition:
- controller test added for select proof of address
- minor bugfix
Author: @cobainc0
> TT-681: Update jQuery Validation Plugin to latest version

- app/assets/stylesheets/helpers/_verify-logo.scss
> TT-811: Fix css selector for hiding logo

- app/views/redirect_to_idp_question/idp_wont_work_for_you.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- stub/locales/idps/stub-idp-one.yml
> TT-721:  Removed IDP-specific comments

- app/controllers/will_it_work_for_me_controller.rb
- spec/controllers/will_it_work_for_me_controller_spec.rb
At present there are some cases whereby the user is not being directed to the correct "will it work for me" page following the age and location questions. This will introduce some new test cases to encompass all potential outcomes, then addresses the previous failures with new logic around the handling of the form.
Authors: @MichaelWalker @callumknights @javindo
> TT-859 Fix will it work for me logic

- app/assets/stylesheets/helpers/_verify-logo.scss
- app/controllers/start_controller.rb
- app/models/ab_test/ab_test.rb
- app/models/analytics/federation_reporter.rb
- app/views/redirect_to_service/redirect_to_service.html.erb
- app/views/response_processing/index.html.erb
- spec/controllers/sign_in_controller_spec.rb
- spec/controllers/start_controller_spec.rb
- spec/features/user_submits_start_page_form_spec.rb
- spec/models/ab_test/ab_test_spec.rb
- spec/piwik_test_helper.rb
- stub/locales/rps/test-rp-no-ab-test.yml
Report RP to Piwik on the start page and when reporting AB test name
Authors @michaelwalker @hugh-emerson
> TT-869: Fix inconsistencies in AB testing data

- app/assets/stylesheets/helpers/_available-languages.scss
- app/views/layouts/application.html.erb
- spec/features/localisation_set_from_different_sources_spec.rb
- spec/features/user_submits_feedback_page_spec.rb
- spec/features/user_visits_confirm_your_identity_page_spec.rb
[JIRA TT-941](https://govukverify.atlassian.net/browse/TT-941)
Added language selection to the bottom, CSS classes added to show/hide language selection and updated tests.
> TT-941: Move welsh translation to the bottom on mobile

- app/models/config_endpoints.rb
- spec/api_test_helper.rb
- spec/controller_helper.rb
- spec/feature_helper.rb
- spec/models/session_proxy_spec.rb
- stub/api/stub_api.rb
> TT-963: update tests to stub and use the transaction entity id

- app/assets/stylesheets/pages/_company.scss
- app/views/choose_a_certified_company/_idp_option.html.erb
- app/views/choose_a_certified_company_variant/_idp_option.html.erb
- app/views/choose_a_certified_company_variant_no_bank_account/_idp_option.html.erb
[JIRA TT-943](https://govukverify.atlassian.net/browse/TT-943)
- updated picker layout on mobiles as per the requirement
- added 'alt' tag to the IDP logos on the picker page
- changed the logo to be clickable
> TT-943: Fix picker page layout

- app/constraints/select_route.rb
- app/controllers/application_controller.rb
- Adding require cookie to dependent files to fix bug
Authors: @cobainc0 @mahmudh @hugh-emerson
> TT-1131 LOA1 Shortened Hub Journey AB(C) Test

- app/views/redirect_to_idp_question/redirect_to_idp_question_LOA1.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_visits_redirect_to_idp_warning_page_spec.rb
Small text change to the interstitial heading.
Authors: @rachelthecodesmith @jakubmiarka
> TT-1259: LOA1 interstitial question text changes

- config/locales/cy.yml
Updated a couple of missing welsh translations and made formatting more consistent (removed " and ' when not neccessary)
Authors: @jakubmiarka @rachelthecodesmith
> BAU: Updated missing welsh translation

- app/views/choose_a_certified_company_variant_create_account/choose_a_certified_company_LOA1.html.erb
- config/locales/cy.yml
- config/locales/en.yml
current LOA1 experiment.
Solo: @cobainc0
> TT-1309 Adding content to company picker for the

- app/views/redirect_to_idp_warning/redirect_to_idp_warning.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/idp_selections_reported_to_piwik_spec.rb
- spec/features/user_visits_redirect_to_idp_warning_page_spec.rb
- Changed heading and CTA text
Authors: @mahmudh @cobainc0
> TT-1395: Update post picker interstitial page

- config/locales/cy.yml
- config/locales/en.yml
- spec/features/service_retrieves_metadata_spec.rb
We have a few old TODOs in the code base. I've gone through and raised
JIRA tickets for some of them, and linked the TODOs back to those tickets.
Author: @michaelwalker
> BAU: Link TODO's to JIRA tickets.

- .pre-commit-config.yaml
- README.md
Add pre-commit config and readme instructions for using the new verify travis yaml linter.
Solo: @swilson96
> TT-1487 Add pre-commit script for travis yaml

- app/models/cycle_three_attribute_response.rb
- app/models/further_information_service.rb
- app/models/policy_endpoints.rb
- app/models/policy_proxy.rb
- app/models/session_endpoints.rb
- app/models/session_proxy.rb
- config/initializers/30_federation.rb
- spec/api_test_helper.rb
- spec/features/user_visits_further_information_page_spec.rb
- spec/models/further_information_service_spec.rb
- spec/models/policy_proxy_spec.rb
- spec/models/session_proxy_spec.rb
Now calls Policy directly for cycle 3.
> TT-1568: remove dependency on frontend api for cycle 3 endpoints

- app/assets/javascripts/application.js.erb
- app/assets/javascripts/clever_questions/select_documents.js
- app/assets/stylesheets/_govuk-elements.scss
- app/assets/stylesheets/pages/_select-documents.scss
- app/controllers/clever_questions/select_documents_controller.rb
- app/models/clever_questions/select_documents_form.rb
- app/views/clever_questions/select_documents/index.html.erb
- app/views/clever_questions/select_documents/unlikely_to_verify.html.erb
- app/views/clever_questions/will_it_work_for_me/index.html.erb
- app/views/clever_questions/will_it_work_for_me/may_not_work_if_you_live_overseas.html.erb
- app/views/clever_questions/will_it_work_for_me/why_might_this_not_work_for_me.html.erb
- app/views/clever_questions/will_it_work_for_me/will_not_work_without_uk_address.html.erb
- config/clever_questions_ab_test_routes.rb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/clever_questions/user_visits_select_documents_page_spec.rb
- spec/javascripts/clever_questions/select_documents_form_spec.js
- spec/models/clever_questions/select_documents_form_spec.rb
- stub/ab_test.yml
clever questions AB test
Authors: @NasAshrafThoughtworks @jakubmiarka
> TT-1606: Add passport expired option to select documents page for the

- app/assets/javascripts/application.js.erb
- app/assets/javascripts/clever_questions/select_proof_of_address.js
- app/controllers/clever_questions/select_documents_controller.rb
- app/controllers/clever_questions/select_proof_of_address_controller.rb
- app/models/clever_questions/select_proof_of_address_form.rb
- app/models/feedback_source_mapper.rb
- app/views/clever_questions/select_proof_of_address/select_proof_of_address.html.erb
- config/clever_questions_ab_test_routes.rb
- config/locales/cy.yml
- config/locales/en.yml
- spec/controllers/clever_questions/select_documents_controller_spec.rb
- spec/controllers/clever_questions/select_proof_of_address_controller_spec.rb
- spec/features/clever_questions/user_visits_proof_of_address_page_spec.rb
- spec/features/clever_questions/user_visits_select_documents_page_spec.rb
- spec/javascripts/clever_questions/select_proof_of_address_spec.js
- spec/models/clever_questions/select_proof_of_address_form_spec.rb
Author: @NasAshrafThougthworks
> TT-1606: Add proof of address page in clever questions AB test journey

- app/models/clever_questions/select_documents_form.rb
- spec/models/clever_questions/select_documents_form_spec.rb
for passport expiry caused an unhandled exception resulting in a rails
error page
Author: @NasAshrafThoughtworks
> TT-1606: Fix bug where an impossible calendar date (e.g. 31st November)

- app/assets/javascripts/ab_test_selector.js
- app/assets/javascripts/analytics.js
- app/views/layouts/application.html.erb
- spec/javascripts/ab_test_selector_spec.js
Pair: @jakubmiarka @MichaelWalker
> TT-1755: IE8 syntax error

- app/controllers/about_loa1_controller.rb
- app/controllers/choose_a_certified_company_loa1_controller.rb
- app/models/config_endpoints.rb
- app/views/about/certified_companies_LOA1.html.erb
- app/views/about/certified_companies_LOA2.html.erb
- spec/controllers/about_loa1_spec.rb
- spec/controllers/choose_a_certified_company_loa1_controller_spec.rb
- spec/features/user_visits_about_certified_companies_page_spec.rb
- stub/api/stub_api.rb
NOTE: **Do not merge until corresponding hub changes have been released**
> Loa1 certified companies

- app/assets/stylesheets/pages/_start-idp-focused-variant.scss
- app/controllers/start_controller.rb
- app/controllers/start_idp_focused_variant_controller.rb
- app/views/start_idp_focused_variant/start.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/main_routes.rb
- spec/features/server_sends_analytics_spec.rb
- spec/features/user_sends_authn_request_spec.rb
- spec/features/user_visits_start_page_idp_focused_variant_spec.rb
- stub/ab_test.yml
Updated the layout for the variant to reflect the new iteration, renamed AB test, updated tests and renamed old routes, as well as adding new ones to prevent returning users erroring out.
Authors: @jakubmiarka @callumknights
> Hub-2 Iteration of AB test

- stub/locales/countries/yy.yml
> EID-344: add locales config file for stub country

- .env
- app/controllers/choose_a_certified_company_loa2_variant_controller.rb
- config/initializers/00_configuration.rb
- config/initializers/30_federation.rb
- config/main_routes.rb
- spec/controllers/choose_a_certified_company_loa2_variant_controller_spec.rb
- spec/features/user_sends_authn_request_spec.rb
- stub/ab_test.yml
- stub/idp-rules-mobile-segments/stub-idp-demo.yml
- stub/idp-rules-mobile-segments/stub-idp-four.yml
- stub/idp-rules-mobile-segments/stub-idp-loa1-with-interstital.yml
- stub/idp-rules-mobile-segments/stub-idp-loa1.yml
- stub/idp-rules-mobile-segments/stub-idp-no-docs.yml
- stub/idp-rules-mobile-segments/stub-idp-one-doc-question.yml
- stub/idp-rules-mobile-segments/stub-idp-one.yml
- stub/idp-rules-mobile-segments/stub-idp-three.yml
- stub/idp-rules-mobile-segments/stub-idp-two.yml
- stub/idp-rules-mobile-segments/stub-idp-unavailable.yml
- stub/idp-rules-mobile-segments/verify-eidas-bridge.yml
> HUB-30: Implement changes for the mobile segments AB test

- public/google7abe5aa505b89660.html
- public/googlee6ac195426fef3bb.html
Update the Google Search Console verification file
> TT-1783: Visibility of Verify journey pages to search engines

- app/controllers/partials/journey_hinting_partial_controller.rb
- app/controllers/sign_in_controller.rb
- app/controllers/test_journey_hint_cookie_controller.rb
- app/views/test_journey_hint_cookie/index.html.erb
- spec/controllers/sign_in_controller_spec.rb
- spec/feature_helper.rb
- spec/features/user_visits_sign_in_page_spec.rb
Updates behaviour to only show hint on sign in IDP picker page for the last IDP succeeded with (sign in or registration).
> Hub-125 IDP reminder on success

- app/views/static/privacy_notice.en.html.erb
- spec/features/user_visits_privacy_notice_page_spec.rb
Copy change for static privacy notice page. English only for the time being while we await Welsh translation.
Solo: @rachelthecodesmith
> HUB-141: Text change for privacy notice

- app/controllers/other_identity_documents_controller.rb
- app/controllers/select_documents_controller.rb
- app/controllers/select_phone_controller.rb
- app/controllers/will_it_work_for_me_controller.rb
- spec/controllers/other_identity_documents_controller_spec.rb
- spec/controllers/select_documents_controller_spec.rb
- spec/controllers/select_phone_controller_spec.rb
- spec/controllers/will_it_work_for_me_controller_spec.rb
- spec/features/user_visits_select_phone_page_spec.rb
- spec/support/will_it_work_for_me_examples.rb
Removes duplicated piwik reporting
Co-Authored-By: Callum Knights <callum.knights@digital.cabinet-office.gov.uk>
> Hub-111 Remove unnecessary Piwik reporting

- app/assets/javascripts/piwik_idp_picker_tracking.js
- app/views/choose_a_certified_company/_idp_option.html.erb
- app/views/choose_a_certified_company/choose_a_certified_company_LOA1.html.erb
- app/views/choose_a_certified_company/choose_a_certified_company_LOA2.html.erb
We'd like to see if people select IDP based on the position on the IDP
picker page or based on the brand recognition. This is introducing adding
an index to the buttons and tracking using JS piwik client as events.
> HUB-173: Record IDP position

- app/views/static/cookies.cy.html.erb
- app/views/static/cookies.en.html.erb
Super quick change to update the cookie information on https://www.signin.service.gov.uk/cookies
> HUB-177: Update cookie page

- app/controllers/partials/idp_selection_partial_controller.rb
Small change to how journey hint followed details is set to fix bug.
Co-Authored-by: Jakub Miarka <jakub.miarka@digital.cabinet-office.gov.uk>
> BAU: Fix bug in piwik reporting

- app/controllers/partials/transactions_partial_controller.rb
- app/models/config_endpoints.rb
- app/models/config_proxy.rb
- app/models/display/rp/service_list_data_correlator.rb
- spec/api_test_helper.rb
- spec/controllers/metadata_controller_spec.rb
- stub/api/stub_api.rb
Change service to read from new Config service endpoint that includes the entityId
> HUB-216: Build List of Services Refactor

- app/views/paused_registration/with_user_session.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Co-authored-by: Callum Knights <callum.knights@digital.cabinet-office.gov.uk>
> HUB-172: Show pause page to users within Verify session

- stub/locales/idps/stub-idp-demo-one.yml
- stub/locales/idps/stub-idp-demo-two.yml
- stub/locales/idps/stub-idp-four.yml
- stub/locales/idps/stub-idp-no-docs.yml
- stub/locales/idps/stub-idp-three.yml
- stub/locales/idps/stub-idp-two.yml
- stub/locales/idps/stub-idp-unavailable.yml
- stub/locales/idps/stub-idp-zero.yml
- stub/locales/idps/verify-eidas-bridge.yml
The missing translations may be causing KOs on staging when deploying frontend
Author: @CharlesIC
> BAU: Add missing Welsh translations in display-locales for the new stub-idp-demos

- app/controllers/application_controller.rb
- app/controllers/partials/transactions_partial_controller.rb
- app/models/display/rp/display_data_correlator.rb
- app/views/prove_identity/prove_identity.html.erb
- spec/models/display/rp/display_data_correlator_spec.rb
Also, removes an unnecessary call to Config
> bau: remove duplicated code

- app/controllers/partials/transactions_partial_controller.rb
- app/controllers/partials/viewable_idp_partial_controller.rb
- app/controllers/single_idp_journey_controller.rb
- app/models/config_endpoints.rb
- app/models/config_proxy.rb
- app/views/test_single_idp_journey/index.html.erb
- config/initializers/30_federation.rb
- spec/api_test_helper.rb
- spec/controllers/metadata_controller_spec.rb
- spec/controllers/single_idp_journey_controller_spec.rb
- spec/features/user_sends_authn_request_spec.rb
- spec/features/user_visits_continue_to_your_idp_page_spec.rb
- stub/api/stub_api.rb
- stub/identity_providers.yml
- stub/relying_parties.yml
-Update single idp controller to use new endpoint
-Remove old endpoint for service list to use new endpoint
> HUB-271: Following change to move config from front to hub

- app/controllers/partials/journey_hinting_partial_controller.rb
- app/controllers/partials/retrieve_federation_data_partial_controller.rb
- app/controllers/paused_registration_controller.rb
- app/controllers/single_idp_journey_controller.rb
- spec/api_test_helper.rb
- spec/controllers/paused_registration_controller_spec.rb
Add view for users without valid session but with the journey hint
cookie state to allow them to proceed to the RP service start page.
> HUB-175: User can hit pause page without session and be redirected to rp

- app/controllers/paused_registration_controller.rb
- app/models/config_proxy.rb
Fixed error where I had put the endpoint rather than the method for the
endpoint for the rp name.
> BAU: Bug fix for rp display name

- app/views/static/cookies.cy.html.erb
- app/views/static/cookies.en.html.erb
Update cookie policy Welsh and English pages with details on the single
idp cookie if the feature flag for Singlie IDP is on.
> HUB-265: English and Welsh cookie policy for Single IDP

- app/controllers/authn_request_controller.rb
- app/controllers/partials/journey_hinting_partial_controller.rb
- app/controllers/partials/user_cookies_partial_controller.rb
- app/controllers/paused_registration_controller.rb
- app/controllers/test_journey_hint_cookie_controller.rb
- app/models/transaction_response.rb
- app/views/paused_registration/with_user_session.html.erb
- app/views/test_journey_hint_cookie/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/api_test_helper.rb
- spec/controllers/paused_registration_controller_spec.rb
- spec/feature_helper.rb
- spec/features/user_sends_authn_request_spec.rb
- spec/features/user_sends_authn_response_spec.rb
- spec/features/user_visits_other_ways_to_access_page_spec.rb
- spec/features/user_visits_paused_page_spec.rb
- spec/features/user_visits_resume_registration_page_spec.rb
- stub/api/stub_api.rb
Alter pause page so button redirects to RP's headless start page, if present.
> HUB-264: Add Headless Redirect Links

- app/views/static/privacy_notice.en.html.erb
- This can be reviewed by checking against the content in the google doc, which can be found from the Jira ticket. 
- To review, it may be easier to start the service locally and view it on the UI. 
- You can find the "Privacy Notice" link at the bottom of any page whilst in Verify.
> EID-998 - Update verify privacy notice for eIDAS

- app/controllers/authn_request_controller.rb
- app/controllers/authn_response_controller.rb
- app/controllers/partials/journey_hinting_partial_controller.rb
- app/controllers/partials/user_cookies_partial_controller.rb
- app/controllers/partials/viewable_idp_partial_controller.rb
- app/controllers/paused_registration_controller.rb
- app/controllers/test_journey_hint_cookie_controller.rb
- app/views/paused_registration/from_resume_link.html.erb
- app/views/test_journey_hint_cookie/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/main_routes.rb
- spec/controllers/paused_registration_controller_spec.rb
- spec/feature_helper.rb
- spec/features/user_visits_an_idp_emailed_link_to_paused_page_spec.rb
- spec/features/user_visits_resume_registration_page_spec.rb
Add new endpoint to PausedRegistrationController to start a new journey based on IDP name passed in URL.
> HUB-185: Add Resume Links to Pause and Resume

- .env
- .env.test
- app/controllers/authn_request_controller.rb
- config/initializers/00_configuration.rb
- config/initializers/30_federation.rb
Remove feature flag from 00_configuration and 30_configuration
Remove all references to feature flag
> HUB-304: Enable Pause and Resume and remove the feature flag

- app/controllers/single_idp_journey_controller.rb
This PR does two small things:
* fixes this issue: we were not checking that the request params were not nil before starting the request verification (that was causing the `valid_request?` method to fail)
* prepares the ground for adding logging, mainly by restructuring the `redirect_from_idp` method to be a "series of filters", which will be able to easily trigger a specific log message if something goes wrong.
A note:
The `redirect_from_idp` method has got a few return points - which may not be ideal - however, in this case, I feel that is making the flow more understandable and will make it easier to add specific logging w/o using nested if statements.
> Refactor the redirect_from_idp method

- app/controllers/initiate_journey_controller.rb
- app/models/config_proxy.rb
- config/routes.rb
- spec/controllers/initiate_journey_controller_spec.rb
- spec/models/config_proxy_spec.rb
https://govukverify.atlassian.net/browse/HUB-376
Add new 'initiate-journey' route and controller
> HUB-376: Cookie Based Journey Hinting - Add New Endpoint

- app/controllers/authn_response_controller.rb
- app/controllers/confirmation_loa1_controller.rb
- app/controllers/confirmation_loa2_controller.rb
- app/views/confirmation_loa1/confirmation_LOA1.html.erb
- app/views/confirmation_loa2/confirmation_LOA2.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/main_routes.rb
- spec/controllers/authn_response_controller_spec.rb
- spec/controllers/confirmation_loa1_controller_spec.rb
- spec/controllers/confirmation_loa2_controller_spec.rb
Co-authored-by: Olakunle Jegede <olakunle.jegede@digital.cabinet-office.gov.uk>
Co-authored-by: Amrit Sidhu <amrit.sidhu@digital.cabinet-office.gov.uk>
> redirect for non matching journey

- config/locales/cy.yml
- config/locales/en.yml
Not to affect the performance report, it can't start with "You'll be redirected"
> BAU: Rename page title for extra question

- config/locales/cy.yml
- spec/features/user_visits_continue_to_your_idp_page_spec.rb
Add missing Welsh translations to config/locales/cy.yml
> HUB-400 add missing Welsh translations

- app/controllers/partials/viewable_idp_partial_controller.rb
Include both the simple Id and passed entity id in log message
> BAU: Improve Error Message "Unrecognised IdP simple id"

- app/controllers/single_idp_journey_controller.rb
Attempt to use slightly more idiomatic Ruby patterns.
> BAU: Tidy up single IDP controller a little

- app/assets/stylesheets/pages/_company.scss
- app/views/shared/_disconnected_idp_list.erb
- app/views/shared/_disconnected_suggested_idp_list.erb
- app/views/sign_in/index.html.erb
Line up the box around the disconnection hint with the boxes below around the other IDPs for signin.
> EameHr58: Align disconnected hint div with others on page

- app/views/select_documents/index.html.erb
- config/locales/en.yml
- spec/features/user_visits_about_page_spec.rb
- spec/features/user_visits_may_not_work_if_you_live_overseas_spec.rb
- spec/features/user_visits_why_might_this_not_work_for_me_page_spec.rb
> hub content quick fixes

- README.md
- config/initializers/00_configuration.rb
> BAU: Update README

- config/locales/cy.yml
Update errors.proxy_node_error.start_again with provided Welsh translation.
> EID-1473 Add Welsh tranlsation to proxy-node error page

- config/application.rb
> BAU: Appease Rubocop

- app/controllers/single_idp_journey_controller.rb
- spec/controllers/single_idp_journey_controller_spec.rb
validate the entity_id parameter, if its empty then show the user the something wrong page.
> EID-1463: check the entity_id parameter

- .env
- app/assets/stylesheets/pages/_company.scss
- app/controllers/choose_a_certified_company_loa2_variant_controller.rb
- app/views/choose_a_certified_company/_idp_option_variant.html.erb
- app/views/choose_a_certified_company/choose_a_certified_company_LOA2_variant.html.erb
- config/initializers/00_configuration.rb
- config/initializers/30_federation.rb
- config/locales/cy.yml
- config/locales/en.yml
- config/main_routes.rb
- spec/controllers/choose_a_certified_company_loa2_controller_variant_spec.rb
- spec/features/user_sends_authn_request_spec.rb
- stub/ab_test.yml
- stub/idp-rules-variant/stub-idp-demo.yml
- stub/idp-rules-variant/stub-idp-four.yml
- stub/idp-rules-variant/stub-idp-loa1-with-interstital.yml
- stub/idp-rules-variant/stub-idp-loa1.yml
- stub/idp-rules-variant/stub-idp-no-docs.yml
- stub/idp-rules-variant/stub-idp-one-doc-question.yml
- stub/idp-rules-variant/stub-idp-one.yml
- stub/idp-rules-variant/stub-idp-three.yml
- stub/idp-rules-variant/stub-idp-two.yml
- stub/idp-rules-variant/stub-idp-unavailable.yml
- stub/idp-rules-variant/verify-eidas-bridge.yml
Variant version will present recommended 2 top IDPs more prominently and not
recommended ones a bit less to test user interaction
if the recommendation model would be deployed.
> [MERGE ON 17 JUNE] EID-1519: Prepare IDP recommendation AB test

- app/views/static/privacy_notice.cy.html.erb
- app/views/static/privacy_notice.en.html.erb
- spec/features/user_visits_privacy_notice_page_spec.rb
Update privacy notice with new content.
Welsh translation to follow in a separate PR.
> EID-1516 Update privacy notice

- Gemfile.lock
> BAU - Update bundle

- config/locales/en.yml
!!! This should not be merged until the connection with Italy has been established !!!
Doc containing the content can be found here: https://docs.google.com/document/d/1oTiaBVHEFLFFG0elap1Bp_QwudSmkM021tWqLo5R7ds/edit
Italy will soon be connecting to the eDIAS connector-node. We need to
update the content to reflect this.
> EID-1650 Update eIDAS sign in content

- app/models/feedback_source_mapper.rb
- app/views/layouts/application.html.erb
- app/views/static/accessibility.en.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/main_routes.rb
- spec/features/user_visits_accessibility_page_spec.rb
https://docs.google.com/document/d/1xE2hmC3HJnGoLkeZ4tbLv4w3WwHLL-1Kzf4QJs0ehEA/edit#heading=h.11c7xesi1kvy
> Add accessibility statement

- app/views/static/privacy_notice.en.html.erb
Explained what information is shared with the rest of GDS using Google Analytics. I've also updated the 'Last updated' date.
We'll arrange for the new content to be translated into Welsh next week.
> Updated 'Cookies and analytics' section

- app/assets/javascripts/analytics.js
- app/assets/javascripts/piwik_event_tracking.js
- app/controllers/application_controller.rb
- spec/features/user_sends_authn_request_spec.rb
- spec/javascripts/piwik_event_tracking_spec.js
* This reverts commit a6b5f5490f8c976d28dec641e9bef4308820d911.
* Matomo cookies are required.
> Revert "HUH-253 Disable Piwik (Matomo) cookies"

- app/views/static/accessibility.en.html.erb
We need a little more time to implement the new design system in Verify,
which will address the issues.
> HUB-450: Update completion date on accessibility page

- Dockerfile
- Dockerfile.heroku
- Rakefile
- config/environments/production.rb
- lib/tasks/copy_govuk_dependencies.rake
Now we've confirmed some thoughts on this we need to undo this change.
> BUGFIX Undo change to digest config

- lib/tasks/copy_govuk_dependencies.rake
We've added extra logging info to try to see whats going on.
> BUGFIX added extra logging to new rake tasks

- lib/node_modules/govuk-frontend/govuk/all.js
- lib/node_modules/govuk-frontend/govuk/components/button/_button.scss
- lib/node_modules/govuk-frontend/govuk/components/character-count/macro-options.json
- lib/node_modules/govuk-frontend/govuk/components/character-count/template.njk
- lib/node_modules/govuk-frontend/govuk/components/checkboxes/template.njk
- lib/node_modules/govuk-frontend/govuk/components/date-input/macro-options.json
- lib/node_modules/govuk-frontend/govuk/components/date-input/template.njk
- lib/node_modules/govuk-frontend/govuk/components/error-summary/macro-options.json
- lib/node_modules/govuk-frontend/govuk/components/footer/_footer.scss
- lib/node_modules/govuk-frontend/govuk/components/footer/template.njk
- lib/node_modules/govuk-frontend/govuk/components/header/_header.scss
- lib/node_modules/govuk-frontend/govuk/components/hint/README.md
- lib/node_modules/govuk-frontend/govuk/components/label/README.md
- lib/node_modules/govuk-frontend/govuk/components/radios/_radios.scss
- lib/node_modules/govuk-frontend/govuk/components/radios/template.njk
- lib/node_modules/govuk-frontend/govuk/components/skip-link/_skip-link.scss
- lib/node_modules/govuk-frontend/govuk/components/summary-list/template.njk
- lib/node_modules/govuk-frontend/govuk/components/tabs/tabs.js
- lib/node_modules/govuk-frontend/govuk/components/tabs/template.njk
- lib/node_modules/govuk-frontend/govuk/objects/_width-container.scss
- lib/node_modules/govuk-frontend/govuk/template.njk
- lib/node_modules/govuk-frontend/govuk/vendor/polyfills/Element/prototype/nextElementSibling.js
- lib/node_modules/govuk-frontend/govuk/vendor/polyfills/Element/prototype/previousElementSibling.js
- lib/node_modules/govuk-frontend/package.json
- lib/package-lock.json
- lib/package.json
This fixes an issue affecting firefox with it reporting the font files are broken.
> BUGFIX Fix for broken font files

- app/views/layouts/application.html.erb
- config/application.rb
This fixes the blocking of the cookie script in FireFox
> BUGFIX Fixes unsigned cookie script in FireFox

- app/assets/stylesheets/pages/_company.scss
- app/views/choose_a_certified_company/choose_a_certified_company_LOA2.html.erb
- app/views/choose_a_certified_company_variant_c/choose_a_certified_company_LOA2.html.erb
Final tweaks, we hope, to implement the design system styles.
https://govukverify.atlassian.net/browse/HUB-415
> HUB-415 additional fix for styles on company picker

- config/locales/cy.yml
[This is the Translation required for new Eidas escape route](https://govukverify.atlassian.net/browse/EID-1914) i.e. [Implement new escape route for eIDAS users whose country isn't listed](https://govukverify.atlassian.net/browse/EID-1774)
> EID-1914 Welsh translation new eidas escape route

- app/views/redirect_to_idp_question/redirect_to_idp_question_LOA2.html.erb
This a quick bug for for a bug fix noticed by barclays and reported
to us via ZenDesk
> ZEN-3915938 Fix for broken interstital question

- app/views/other_ways_to_access_service/after_eidas.html.erb
- config/locales/cy.yml
Update the css the reflect the design system
Fix missing bracket
> EID-1914: fix styling and formatting of the EIDAS other ways page

- app/controllers/single_idp_journey_controller.rb
- spec/controllers/single_idp_journey_controller_spec.rb
This downsizes Single Idp Journey error to warning level see
https://sentry.tools.signin.service.gov.uk/verify/prod-frontend/issues/4490
> bau: Downsize SIDP error to warning

- app/views/errors/session_timeout.html.erb
- config/locales/en.yml
Beth requested some changes to the session timeout page. These are those changes.
Take 2 :lion:
> HUB-557: Requested content changes to timeout page

- app/controllers/hint_controller.rb
- spec/controllers/hint_controller_spec.rb
> BAU: Fix the HMRC's entity ID

- app/models/session_validator/session_start_time_validator.rb
- spec/features/user_visits_start_page_spec.rb
- spec/features/user_visits_start_page_variant_spec.rb
- spec/models/session_validator_spec.rb
I forgot to include the session length :facepalm:
> BAU: Fix the session expiry calculation

- .rubocop.yml
- config/initializers/logging.rb
Reverts alphagov/verify-frontend#852
Nah, doesn't fix anything, but we might be on something...
> Revert "BAU: Fix (hopefully) logging to logstash"

- Dockerfile
- Dockerfile.heroku
- README.md
- update readme so that people know it's there and how to use it
- still work to do, to make it easy to update dependencies inside the container
> Fix the Dockerfile and add some notes about using it

- README.md
pipelines have moved ... update the links
> update pipeline links

- Gemfile
- Gemfile.lock
Undid my previous versions and settled on using this Gem which should do what we need it to.  The Gem's homepage can be found at:
https://github.com/pschinis/rails_same_site_cookie
Jira Ticket: https://govukverify.atlassian.net/browse/HUB-679
> HUB-679 Fix for the SameSite cookie issue

- Dockerfile
- Dockerfile.heroku
These changes were made to try to fix our pipeline.  We narrowed down the issue to an issue in verify-infrastructure-config which has now been fixed and merged in.
> Reverted changes to dockerfile as they weren't needed

- app/controllers/select_documents_variant_c_controller.rb
- app/views/select_documents_variant_c/advice.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/user_visits_select_documents_advice_page_spec.rb
Changes were request to the Short hub which resulted in a bit of a logic change. 
Jira Ticket: https://govukverify.atlassian.net/browse/HUB-702
> HUB-702 Fixes for the Short Hub Content

- config/initializers/logging.rb
Update Verify-fronted, so that sentry reports environment
Co-authored-by: Amrit Sidhu <amrit.sidhu@digital.cabinet-office.gov.uk>
> HUB-733: Updating frontend so sentry reports env

- app/assets/javascripts/piwik_idp_picker_tracking.js
Fix piwik idp picker tracker error due to typo in identifier
> BAU: Fix piwik idp picker tracker error

- config/locales/cy.yml
See the translations spreadsheet here: https://docs.google.com/spreadsheets/d/1HZt4cyiFiNmz_4tdZw6_z62zlukM1sQZ/edit#gid=2108675687
> HUB-740: Add Welsh translation

- app/assets/stylesheets/pages/_company.scss
- app/views/choose_a_certified_company/_idp_option.html.erb
- Horizontally center buttons
- Table row centering
- Reduce space between primary and secondary buttons
when in mobile view
(cherry picked from commit ef6dd94630b55b2323765d94163cdec5d782b397)
> BAU: Horizontally center buttons

- app/assets/stylesheets/pages/_company.scss
- app/views/choose_a_certified_company/_idp_option.html.erb
Reverts alphagov/verify-frontend#946
> Revert "BAU: Horizontally center buttons"

- app/assets/stylesheets/pages/_company.scss
Current master is looking like this in mobile view
This PR correct's this
> BAU: Fix who do you have account with in mobile

- app/views/choose_a_certified_company/_idp_option.html.erb
I have added govuk-width-container to allow left and right margins, to prevent the buttons being flushed right up to the edges
> BAU: Add left right margins to picker in mobile view

- app/views/static/accessibility.cy.html.erb
- config/locales/cy.yml
- spec/features/user_visits_about_page_spec.rb
Various Welsh translations.
Also fixes an issue with the wrong key name in the Welsh locales file.
> HUB-863: Welsh translations

- app/views/shared/_transaction_list.html.erb
- Ensure each service is listed using bullet points
> HUB-1155 - Bullet point each service

- Gemfile
- Gemfile.lock
Reverts alphagov/verify-frontend#1051
> Revert "Bump webdrivers from 4.7.0 to 5.0.0"

- app/assets/javascripts/vendor/jquery.validate.js
Replacing the existing jquery-validate file with the latest
> BAU: Update to the latest version of jquery-validate
